### ISSUE TITLE
template.createViewModel is not a function

### ISSUE THREAD

**Issue by artin-phares** [ManuelDeLeon/viewmodel#100]
I recently faced the issue with view model, and reading error dropped to the console does not give me any clue what is wrong.

Error in console:
```
Exception from Tracker recompute function:
debug.js:41 TypeError: template.createViewModel is not a function
    at null.<anonymous> (hooks.coffee:70)
    at template.js:116
    at Function.Template._withTemplateInstanceFunc (template.js:437)
    at fireCallbacks (template.js:112)
    at null.<anonymous> (template.js:192)
    at fireCallbacks (view.js:267)
    at Object.Tracker.nonreactive (tracker.js:560)
    at view.js:264
    at Object.Blaze._withCurrentView (view.js:523)
    at Object.Blaze._fireCallbacks (view.js:263)
```

Trace:

![c008993237d0c3d295d5e15382ed2e44](https://cloud.githubusercontent.com/assets/671082/9442246/8d2d8574-4a83-11e5-88bf-ac5f9b216a5a.png)

template == 'app' string.
'app' is name of my top level template. It tries to createViewModel from string...

I have a list with items and popup with selected item.
I select one of items from the list - it pops up successfully first time. Second time I select item from list - error thrown.

Could you please give me any direction from this only? Or let me know and I will provide more precise context.

**Comment by ManuelDeLeon** [comment]
You're going to have to make a repro because at that point `template` shouldn't be a string. It should be the Blaze template object.

![image](https://cloud.githubusercontent.com/assets/4257750/9443855/bd4b781c-4a40-11e5-9e2c-f0d5618f9719.png)
![image](https://cloud.githubusercontent.com/assets/4257750/9443868/d28dd918-4a40-11e5-8ce6-0649f109df74.png)

**Comment by artin-phares** [comment]
Ok, so.. simplifying...

I have two nested templates: 'app' and 'card'.

'app' template is top level template with list and selected item:

```jade
template(name='app')
  +itemsList (items=items)
  
  if selectedItem
    div.fog
    +card (item=selectedItem)
```
```javascript
Template.app.viewmodel('app', {
     items: function() { return Items.find() },
     selectedItem: function() {
          return Recipe.findOne({id:this.selectedItemId()});
     },
     selectedItemId: function() {
          return Session.get('selectedItemId');
     }
});
```

'card' is template for selected item popup:

```jade
template(name='card')
    if item
      #{item.name}
```
```javascript
Template.card.viewmodel('card', function(data) {
     return {
        recipe: data.item,
        inEditMode: data.inEditMode,
        onUrl: ['inEditMode'] // <-- this is bad guy
     }
});
```

While investigating I've figured out that it has something to do with <code>onUrl</code> feature on my nested template. Everything works fine when I comment that line.

Any idea?

**Comment by ManuelDeLeon** [comment]
Holy closures Batman! `onUrl` is overriding the `template` variable =(

I'll fix it ASAP.

**Comment by artin-phares** [comment]
Thanks!

**Comment by ManuelDeLeon** [comment]
Update to 1.9.5

Thanks for helping.

**Comment by artin-phares** [comment]
Wow. That's reactive bug fixing. =)
Works nicely now. Much appreciated.
