### ISSUE TITLE
Issue after update from 1.9.6 to 1.9.7

### ISSUE THREAD

**Issue by zimt28** [ManuelDeLeon/viewmodel#101]
Meteor has just updated the viewmodel package to `1.9.7`, which causes strange behavior: I have some input fields with value binding. When I now render the template and type into one of those fields, the first time I press a key, the letter will just disappear again. So I press a letter -> the field resets -> I can type normally.

**Comment by ManuelDeLeon** [comment]
Sorry about that. I'll check it out.

**Comment by ManuelDeLeon** [comment]
I can't reproduce it. Please make a repro so I can fix it. Thanks.

**Comment by zimt28** [comment]
Sure: https://github.com/zimt28/vm-issue
I noticed that it only happens when you give the viewmodel a name

**Comment by Anima-t3d** [comment]
Also, seems that **content** is now a reserved property/method key. 
Prior to updating to 1.9.7 this code worked:
In VM:

    content: ['element1','element2'],

After update it shows a 
>Exception from Tracker recompute function:
>meteor....ddc0aaf (line 888)
>Error: {{#each}} currently only accepts arrays, cursors or falsey values.
>meteor....ddc0aaf (line 888)
>badSequenceError@http://localhost:8080/packages/observe-sequence.js?0532a9dd76dd78f543eb4d79a1e429df186d8bde:179:1

It took me 2 hours to find that out (just showing blank page), hopefully this will help other people.
Perhaps mention it in the changelog/history?

Thank you for your efforts!

**Comment by ManuelDeLeon** [comment]
@zimt28 Your issue only happens with Flow Router. I'll find out why.

@Anima-t3d ViewModel doesn't use the word 'content'. Please make a repro.

**Comment by ManuelDeLeon** [comment]
@zimt28 Update to 1.9.8, I fixed an issue with .extend. That bug only came to light because Flow Router has a bug of itself. It triggers a dependency change for `Template.currentData()` on every keystroke.

**Comment by Anima-t3d** [comment]
Finally found the cause of the issue.
The update to 1.9.7 which inherits properties from context, inherited `content` from `BlazeLayout.render` which takes the string as a name to render a dynamic template in the region I named content...
```javascript
loggedIn.route('/', {
	name: 'Home',
	action: function() {
		return BlazeLayout.render('MainLayout', {
			header: "Header",
			content: "Dashboard",
			footer: "Footer"
		});
	}
});
```
