### ISSUE TITLE
localised custom binding

### ISSUE THREAD

**Issue by peonmodel** [ManuelDeLeon/viewmodel#103]
how do i create custom binding for view model that is local to a particular package?

i have been using viewmodel for several different packages, in which one package have the 'onfocusout' binding

ViewModel.addBind('onfocusout', function (p) {
	var params = p.property.split('|');
	var func_key = params.shift();
	return p.element.focusout(function () {
		var input_value = p.element.val();
		var element = p.element['context'];
		p.vm[func_key](input_value, element);
	});
});

however, i realised that 'onfocusout' binding works for the entire project, not localised to a particular package or template

how may i create custom binding only to a particular viewmodel instance?

**Comment by ManuelDeLeon** [comment]
Unfortunately that's how Meteor packages work. As far as I know the only solution is to give it an 'internal' name.
