### ISSUE TITLE
Is there a way that one method in the VM can override another method in the same VM?

### ISSUE THREAD

**Issue by Anima-t3d** [ManuelDeLeon/viewmodel#104]
I want to override a method defined in the VM based on another method.

e.g. In the same VM:

    showMsg: function () {console.log('Original function definition');}
    alterMsg: function() {
        this.showMsg(function () {console.log('Orginal function is now altered!')});
    }

Practical purposes would be re-use of templates and bind different click events. Perhaps I am just not using the VM as you intended and should I make more use of child VMs?

**Comment by ManuelDeLeon** [comment]
You're almost there...

```js
showMsg: function () {console.log('Original function definition');}
alterMsg: function() {
    this.showMsg = function () {console.log('Orginal function is now altered!')};
}
```

**Comment by avalanche1** [comment]
That should be in the docs.
