### ISSUE TITLE
Question: Is there an analogue to the $scope.$apply() of AngularJS?

### ISSUE THREAD

**Issue by convexset** [ManuelDeLeon/viewmodel#105]
I'd like to notify viewmodel of "outside mutation" in the manner of $scope.$apply()?

Incidentally... What qualifies as a change to the data context that viewmodel will react to? (Pointers to documentation would be helpful.)

**Comment by ManuelDeLeon** [comment]
> I'd like to notify viewmodel of "outside mutation" in the manner of $scope.$apply()?

You have to give me an example because something like `$scope.$apply()` isn't needed.

> What qualifies as a change to the data context that viewmodel will react to?

Again I'm not sure what you mean. All properties are reactive.

**Comment by convexset** [comment]
Thanks for prompt response. Pls ignore stupid questions. =(
