### ISSUE TITLE
ToJS() and Reset() do not work when using the viewmodels for properties

### ISSUE THREAD

**Issue by fpw23** [ManuelDeLeon/viewmodel#106]
see this forum post for details

http://viewmodelboard.meteor.com/posts/JrTMzNdn5ta46rWwS/how-to-build-reusable-form-elements-components

when trying to share viewmodel properties between two templates by assigning functions to the sharing viewmodel's properties, the ToJS() and Reset() functions on the sharing viewmodel stop working.

**Comment by ManuelDeLeon** [comment]
I can't reproduce it. Please make a repro.

**Comment by fpw23** [comment]
here is an example repo:

https://github.com/fpw23/viewmodeltemplateerror

**Comment by ManuelDeLeon** [comment]
That's the expected behavior. toJS and reset only work for the given view model. They don't cascade.

In your case `formJS` is acting on the body view model. It only has the `age` property. The sub view models (`textInput`) do have id, label, and maybe text & error.

![image](https://cloud.githubusercontent.com/assets/4257750/9668281/e6cff442-523d-11e5-8eb4-66af1d75dc8b.png)

![image](https://cloud.githubusercontent.com/assets/4257750/9668291/f2a6cc14-523d-11e5-9a20-a4e58aa902bc.png)

**Comment by fpw23** [comment]
but the point of the sub view models is to wrap up the html needed to build a smart field that will show its own error.  I would like be be able to have fields on the parent view model be passed to the child viewmodel/template and bound to them so that I can have, like in the example, a text template, a text area template, a combo template, etc.  Just like the original forum poster wanted to achieve.

**Comment by ManuelDeLeon** [comment]
You can't get that automagically (ViewModel has no way of knowing what you want to share between templates). Here's how I would do it in your case:

```js
  Template.body.viewmodel({
    firstText: '',
    firstTextHelper: function(){
      return this.firstText;
    },

    // rest of the vm

  }, 'firstTextHelper');
```

```html
{{> textInput id='body.firstName' label='First Name' text=firstTextHelper}}
```

That works for one field. For multiple fields you probably want to 'bundle' them:

```js
  Template.body.viewmodel({
    firstText: '',
    lastText: '',
    fields: function(){
      return {
        'body.firstName': this.firstText,
        'body.lastName': this.lastText
      }
    },

    // Rest of the vm

  }, 'fields');
```

```html
            {{> textInput id='body.firstName' label='First Name' fields=fields}}
            {{> textInput id='body.lastName' label='Last Name' fields=fields}}
```

And on `Template.textInput.viewmodel` change `text: data.text,` for `text: data.fields[data.id],`

**Comment by fpw23** [comment]
hmm, so is there no way to make the field that gets declare on the parent viewmodel passable to other viewmodels?  I am coming from a Knockout JS background and in that world all properties are observables, I can pass an observable reference from one viewmodel to the next without needing to do any special treatment.  It looks like from the source code you take the 'firstText' and 'lastText' and turn them into functions that are reactive.  Instead of you doing that automatically could I to that when declaring them with a helper method like I get with Knockout?  Then could I somehow use that so that my template markup can look like this:

     {{> textInput label='First Name' field=firstText }}

**Comment by ManuelDeLeon** [comment]
> hmm, so is there no way to make the field that gets declare on the parent viewmodel passable to other viewmodels?

Isn't that what I just did?

> Then could I somehow use that so that my template markup can look like this:  `{{> textInput label='First Name' field=firstText }}`

You can't because the view model (and thus firstText) isn't ready by the time Blaze resolves the contents of `{{ }}`

**Comment by ManuelDeLeon** [comment]
> but the point of the sub view models is to wrap up the html needed to build a smart field that will show its own error. I would like be be able to have fields on the parent view model be passed to the child viewmodel/template and bound to them so that I can have, like in the example, a text template, a text area template, a combo template, etc. Just like the original forum poster wanted to achieve. 

Now that I re-read this I'm more confused. Isn't that what you have in your example? (A reusable control)

**Comment by fpw23** [comment]
I guess if feel like the sharing of viewmodels between templates via the ViewModel.all global variable is dirty.  I am still new to meteor and am having some growing pains, in server side request/response globals and session state is frowned upon but it seems to be the correct way in meteor.  I will work with the examples that you have provided as they do meet my needs, I just need to change my philosophy on globals.  Thanks for all the help

**Comment by ManuelDeLeon** [comment]
The scoping could be a hair better but the result would be the same.

```js
    firstName: function () {
      return ViewModel.byId("body.firstName");
    },
```

vs

```js
    firstName: function () {
      return this.child("body.firstName");
    },
```
