### ISSUE TITLE
'change' event breaks 'returnKey' on sibling element

### ISSUE THREAD

**Issue by luisreyes** [ManuelDeLeon/viewmodel#108]
## Problem
At first the `input` and `returnKey` work as expected by calling **onUpdate** when the *enter key* is pressed, but after triggering the `change` event on the `select` the input's `returnKey` starts behaving as a `change` event by triggering on every keystroke.
## Example
```html
<template name="myTemplate">
    <!-- Call 'onUpdate' on ENTER key -->
    <input type="text" data-bind="value: name, returnKey: onUpdate"/>
    <!-- Call 'onUpdate' on 'change' event -->
    <select data-bind="options: getOptions, value:option, change: onUpdate"></select>
</template>
```
```javascript
Template.myTemplate.viewmodel({
  name: '',
  option: '',
  getOptions: function() {
    return ['Option 1', 'Option 2'];
  },
  onUpdate: function() {
    // do something
  }
});
```

***I tested this on two inputs and the same bug happens***
```html
<input type="text" data-bind="value: name, returnKey: onUpdate"/>
<input type="text" data-bind="value: email, change: onUpdate"/>
```
I tried looking through the code but I am not a coffee lover unless it's in my cup. :) I'll try to looking at it some more and if anything comes up maybe expect a PR.

***Great work on this package by the way! Very clean implementation.***

**Comment by ManuelDeLeon** [comment]
Please make a repro because I get the expected behavior with the following:
```html
<body>
  <input type="text" data-bind="value: name, returnKey: onUpdate"/>
  <input type="text" data-bind="value: email, change: onUpdate"/>
</body>
```

```js
Template.body.viewmodel({
  name: '',
  email: '',
  onUpdate: function () {
    console.log(new Date());
  }
});
```

onUpdate only gets called when I hit enter on the name or type something on the email.

**Comment by luisreyes** [comment]
> onUpdate only gets called when I hit enter on the name or type something on the email.

Now go back to name type something. Does the name input trigger events on change?  This is the issue that I'm encountering.

**Comment by ManuelDeLeon** [comment]
Nope, I can type on name again and onUpdate doesn't get called unless I
press enter.

**Comment by luisreyes** [comment]
Ok thanks for looking. I'll have to look more into it to find what I did to
cause it.
