### ISSUE TITLE
[Blaze Event] 'change select' being triggered on bind()

### ISSUE THREAD

**Issue by luisreyes** [ManuelDeLeon/viewmodel#109]
## Problem
Whether I use **Template Events**
```javascript
Template.myTemplate.events({
  'keypress input, change select':function(){
    // do something
  }
});
```
or I use **blaze_events**
```javascript
Template.myTemplate.viewmodel({
  blaze_events:{
    'keypress input, change select':function(){
      // do something
    }
  }
});
```
These are being triggered on the `bind()` of the viewmodel. This is causing me a bit of issues since for the rest of my application is using a common pattern of using the Template events. 

The temporary solution was to ***not*** use either and use a viewmodel function called from the element's `data-bind` attribute with the change property. Which is what brought me to issue #108 . 

**Is there a better way to do this?** I need to be able to call the same method for both interaction `keypress` & `change` and have it not be triggered on initial `bind()`.

**Comment by ManuelDeLeon** [comment]
I don't understand the problem. What's wrong with `data-bind="change: doSomething"`?
