### ISSUE TITLE
_ undefined when using viewmodel within another package

### ISSUE THREAD

**Issue by peonmodel** [ManuelDeLeon/viewmodel#110]
i am writing unit tests for a package i created which depends on View Model, but kept having ReferenceError: _ is not defined in the viewmodel's .coffee file
despite having added underscore in my package itself and its onTest

the best resource i found that is similar to the issue: https://github.com/dburles/meteor-collection-helpers/issues/7

**Comment by ManuelDeLeon** [comment]
Are you using Meteor 1.2?

**Comment by peonmodel** [comment]
i am using Meteor 1.1.0.3

**Comment by ManuelDeLeon** [comment]
These issues are always painful. Try using ViewModel's source and adding an onTest section in its package.js file that references underscore.

**Comment by peonmodel** [comment]
I added
api.use('underscore');
api.use('tracker');
api.use('session');
to a fakeviewmodel package and i stopped having the _ is undefined issue
the code that had the issue was 
"var testtemplate = Template.FileInfoItem.createViewModel({_id: 'lll'})" which the trace leads to viewmodel.coffee

**Comment by ManuelDeLeon** [comment]
give me a repro

**Comment by peonmodel** [comment]
https://github.com/peonmodel/verdant-moo
just the packages folder and console logs

**Comment by peonmodel** [comment]
problem still persist in Meteor 1.2.0.2

**Comment by ManuelDeLeon** [comment]
Ack! Sorry (I forgot about this). Please update to 1.9.13
