### ISSUE TITLE
Call function from within grandchild VM

### ISSUE THREAD

**Issue by Anima-t3d** [ManuelDeLeon/viewmodel#111]
I would like to find out the **best way** to be as **loosely coupled and DRY** using viewmodel in meteor.

## Problem
I would like to call a function from the grandparent VM within a VM. For example I have a main template (A) with VM, which includes a subtemplate (B) with VM and that one includes another subtemplate (C) with VM. I want to pass the context from A to C via B, where B needs to add to the context it receives in order to give C an extended context from A.

### Example
If needed I can provide a basic theoretical code sample but a practical example would be as follows:
* Have a main template that has 3 buttons (add book, add magazine, add newspaper) and displays a list of added items for each type
* Have subtemplates for each type
* They all have some different properties, but the common thing is title
* So I add a _addTitle partial subtemplate with an input field for title and 2 buttons (cancel and add). 
* I want to dynamically change the button text depending on which parent implements it (template of generation B) E.g Cancel/Add book, Cancel/Add Magazine, Cancel/Add Newspaper
* I want to dynamically change the function called depending on which parent implements it (template of generation B) E.g Add book -> calls A.addBook(), Add Magazine -> A.addMagazine(), Add Newspaper -> A.addNewspaper()

## Issues
Using the documentation below I encountered the following issues:
- Calling A.addBook() from C would result in missing this.bookCollection()
- I can't pass a context that is this from B to C that includes the extended A+B? In this case the button texts and which function to call on click.
- I could use `ViewModel.byId()` from within parent or use `this.parent().parent()` from within the grandchild but that seems too tightly coupled?
- Perhaps the best way to go about this is a recursive `viewmodel.children(function(vm) { return vm.property() === 1 })` as this returns direct children only? As seen here: http://viewmodel.meteor.com/#childrenBk

## References
I read through:
* http://viewmodel.meteor.com/#dataContextBk
* http://viewmodel.meteor.com/#extendBk

And possibly related to:
* https://github.com/ManuelDeLeon/viewmodel/issues/74
* https://github.com/ManuelDeLeon/viewmodel/issues/82

**Comment by ManuelDeLeon** [comment]
> I can't pass a context that is this from B to C that includes the extended A+B?

Why not? You can pass 1 or more references from A -> B, then pass 1 or more from B -> C

I would probably just reference B from C via `.parent()` and A from C via `ViewModel.byId("A")` and call it a day.

**Comment by Anima-t3d** [comment]
>Why not? You can pass 1 or more references from A -> B, then pass 1 or more from B -> C

If you look in the code below I can't export `this` (referring to the parent VM) via helper, I have to explicitly  write out all the properties that I want to pass on to the child. Otherwise the child will have a `autorun undefined` error. This might seem minor, but if I want to pass a lot of properties I will be repeating the same thing over and over just routing it through various generations of children. When something changes I have to find and replace the change in each of them. This doesn't seem very DRY to me and is prone to typo's and bugs. An in between solution could be having something like: 
```javascript
parentContext: function () {
    return exportVMProperties(['property1', 'property2']);
}
```
Where behind the screens it gets converted to an object:
```javascript
parentContext: function () {
    // properties passed by reference hence no ()
    return {
        property1: this.property1,
        property2: this.property2
    }
}
```
Also when trying to define the action functions for the grandchild from within the child (so a new parent - child relation) it gives me the error that `this.parent()` is not a function. I basically want to define that the `actionCancel` triggers the `cancelEdit` from the grandparent. Whether or not I wrap it in a function that gets the context or not doesn't seem to make a difference. **Am I doing something wrong?**

### HTML
```html
<template name="LiteratureOverview">
<!--Parent template-->
	<h2>Add Literature</h2>
	<button data-bind="click: showAddBook">Add Book</button>

	{{> AddBook parentContext}}

	<h2>Literature Overview</h2>
	<ul>
		{{#each books }}
			<li>
				<span data-bind="text: title"></span>
				<span data-bind="text: type"></span>
			</li>
		{{/each}}
	</ul>
</template>

<template name="AddBook">
<!--Child template-->
	<div data-bind="visible: isAddingBook">
		<input type="text" data-bind="value: literatureTitle">
		{{> _DualAction }}
	</div>
</template>


<template name="_DualAction">
<!--Grandchild template-->
	<button data-bind="click: actionOk, text: textOk">OK</button>
	<button data-bind="click: actionCancel, text: textCancel">Cancel</button>
</template>
```
### JS
```javascript
Template.LiteratureOverview.viewmodel('LiteratureOverview',
	{
		literatureTitle: '',
		isAddingBook: false,
		books: [],
		addBook: function () {
			this.books().push({
				title: this.literatureTitle(),
				type: 'Book'
			});
		},
		showAddBook: function () {
			this.isAddingBook(true);
		},
		cancelEdit: function () {
			this.isAddingBook(false);
		},
		parentContext: function () {
			//return this;
			return {
				literatureTitle: this.literatureTitle,
				isAddingBook: this.isAddingBook,
				books: this.books,
				addBook: this.addBook,
				showBook: this.showBook,
				cancelEdit: this.cancelEdit()
			};
		}
	}, 'parentContext'
);

Template.AddBook.viewmodel('AddBook',
	function (ctx) {
		return ctx;
	},
	function (ctx) {
		return {
			textOk: 'Add book',
			actionOk: function () {
				console.log('adding book');
			},
			textCancel: 'Cancel adding book',
			actionCancel: this.cancelEdit
		};
	}/*,
	{
		textOk: 'Add book',
		actionOk: function () {
			console.log('adding book');
		},
		textCancel: 'Cancel adding book',
		actionCancel: function () {
			console.log('canceled adding book');
		}
	}*/
);
```

Thanks for your time.

**Comment by ManuelDeLeon** [comment]
I don't know what your real app looks like but there are so many things that raises an eyebrow...

* The template _DualAction seems superfluous and it should just be part of AddBook
* The contents of `#each books` uses properties not found on the view model, just the new context. It should use its own template or just use blaze to display the properties.
* The parent template has properties like literatureTitle which are not used by it. They should be part of the AddBook view model instead.
* The add book button should be in the AddBook template so you can remove showAddBook from the parent and put it on AddBook instead.
* Speaking of showAddBook, you can remove showAddBook and cancelEdit. You only need isAddingBook if you use the toggle binding: `<button data-bind="toggle: isAddingBook">Add Book</button>`

There are others but that should give you an idea of why what you're doing is confusing to me.

**Comment by Anima-t3d** [comment]
> The template _DualAction seems superfluous and it should just be part of AddBook

As I described in the first post, in this slimmed down sample version I would have a AddBook, AddMagazine, AddNewspaper. They all need a "dual action" being cancel or add. Therefore I want to be DRY and keep it in one place in case later on I want to change the structure of the buttons.
> The contents of #each books uses properties not found on the view model, just the new context. It should use its own template or just use blaze to display the properties.

Ok, I didn't get to that part yet because I was stuck with the basic level of parent-child already.
> The parent template has properties like literatureTitle which are not used by it. They should be part of the AddBook view model instead.

LiteratureTitle would be used by all 3 types (book, magazine, newspaper)
> The add book button should be in the AddBook template so you can remove showAddBook from the parent and put it on AddBook instead. 

That would be okay, if not for the fact that I might want to either have the buttons shown on a different part of the page than where the content would be shown. Or use modal windows when clicked on the button.

### Questions
- Is it the expected behaviour that you can not pass context this in the export helper? And instead need to pass all wanted properties by typing them again?
- How come I get this.parent/this.parent() is not a function error?

The questions listed above don't seem to be affected by the remarks you made? Is there something else I am doing wrong? 

I hope I cleared up the situation a bit.

**Comment by Anima-t3d** [comment]
@ManuelDeLeon did you manage to take a look at it? Thanks.

**Comment by Anima-t3d** [comment]
Solved it. 
I did not need parentContext since 1.9.7 it inherits without the need to pass the context.
I needed to add () on properties as VM wraps properties in functions.

## HTML
```html
<head>
	<title>meteorABC</title>
</head>

<body>
	<h1>Welcome to Meteor!</h1>

	{{> LiteratureOverview}}
</body>

<template name="LiteratureOverview">
<!--Parent template-->
	<h2>Add Literature</h2>
	<button data-bind="click: showAddBook">Add Book</button>

	{{> AddBook}}

	<h2>Literature Overview</h2>
	<ul>
		{{#each books }}
			{{> Item }}
		{{/each}}
	</ul>
</template>

<template name="AddBook">
<!--Child template-->
	<div data-bind="visible: isAddingBook">
		<input type="text" data-bind="value: literatureTitle">
		{{> _DualAction }}
	</div>
</template>

<template name="Item">
	<li>
		A <span data-bind="text: type"></span> with title <span data-bind="text: title"></span>
	</li>
</template>

<template name="_DualAction">
<!--Grandchild template-->
	<button data-bind="click: actionOk, text: textOk">OK</button>
	<button data-bind="click: actionCancel, text: textCancel">Cancel</button>
</template>
```
## JS
```javascript
/* global Template: true */

Template.LiteratureOverview.viewmodel('LiteratureOverview',
	{
		literatureTitle: '',
		isAddingBook: false,
		books: [
			{
				title: 'John doe',
				type: 'Book'
			},
			{
				title: 'Jane Tzi',
				type: 'Book'
			}
		],
		addBook: function () {
			this.books().push({
				title: this.literatureTitle(),
				type: 'Book'
			});
		},
		showAddBook: function () {
			this.isAddingBook(true);
		},
		cancelEdit: function () {
			this.isAddingBook(false);
		}
	}, 'books'
);

Template.AddBook.viewmodel(
	{
		textOk: 'Add book',
		actionOk: function () {
			console.log('adding book');
			this.parent().books().push({
				title: this.literatureTitle(),
				type: 'Book'
			});
			this.parent().isAddingBook(false);
		},
		textCancel: 'Cancel adding book',
		actionCancel: function () {
			return this.parent().cancelEdit();
		},
		isAddingBook: function () {
			return this.parent().isAddingBook();
		},
		literatureTitle: ''
	}
);

Template.Item.viewmodel(
	{
		title: function () {
			return this.title;
		},
		type: function () {
			return this.title;
		}
	}
);
```
*I think it is best to include an example like this in the docs as new users will not always understand on how to use the code as you intended it.*

**Is there anything that could have been done better?** 
Thanks!

**Comment by ManuelDeLeon** [comment]
You're good. The only minor thing is that I would use toggle on the add book button: `<button data-bind="toggle: isAddingBook">Add Book</button>` and then get rid of the `showAddBook` and `cancelEdit` methods.

**Comment by Anima-t3d** [comment]
I changed it to use toggle.

## HTML
```html
<template name="LiteratureOverview">
<!--Parent template-->
	<h2>Add Literature</h2>
	<button data-bind="toggle: isAddingBook">Add Book</button>
	{{#if isAddingBook }}
		{{> AddBook}}
	{{/if }}

	<h2>Literature Overview</h2>
	<ul>
		{{#each books }}
			{{> Item }}
		{{/each}}
	</ul>
</template>

<template name="AddBook">
<!--Child template-->
	<input type="text" data-bind="value: literatureTitle">
	{{> _DualAction }}
</template>
```
## JS
```javascript
Template.LiteratureOverview.viewmodel('LiteratureOverview',
	{
		literatureTitle: '',
		isAddingBook: false,
		books: [
			{
				title: 'John doe',
				type: 'Book'
			},
			{
				title: 'Jane Tzi',
				type: 'Book'
			}
		],
		addBook: function () {
			this.books().push({
				title: this.literatureTitle(),
				type: 'Book'
			});
		},
		cancelEdit: function () {
			this.isAddingBook(false);
		}
	}, ['isAddingBook','books']
);
```

**Comment by ManuelDeLeon** [comment]
From what I see you don't need cancelEdit. Just change isAddingBook
directly.

**Comment by Anima-t3d** [comment]
Ok, thanks I updated the code. 

The cancelEdit is what I still need in the actual project as it needs to cancel out all other isAddingx methods.
