### ISSUE TITLE
calling the same viewmodel multiple times doesn't work

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#112]
I'm trying to modularize my code, but keep the modules inside one template. So I have this code:
```jade
textarea(maxlength="1500" name='description' data-bind='value: descrText')

#descrPreview(data-bind='html: descrPreview')
```
```coffee
	T = Template.addPost
	## POST DESCRIPTION ##
	T.viewmodel 'addPost',
		descrText: ""
	T.onRendered -> #initialize textarea logic

	# POST DESCR PREVIEW  #
	T.viewmodel 'addPost',
		descrPreview: ->
			@descrText()
	T.onRendered ->#initialize descrPreview logic
```

And I receive an error:
`Property 'descrText' not found on view model`

**Comment by ManuelDeLeon** [comment]
You're defining the view model for addPost twice.

**Comment by avalanche1** [comment]
ehh... how could I do it correctly? I mean, add properties to already defined viewmodel?

**Comment by ManuelDeLeon** [comment]
You can add to an existing view model with `.extend` but most likely you don't need to do that. It is very rare to use that method.

Why not just do something like the following?

```js
Template.addPost.viewmodel
  descrText: ''
  afterBind: ->
    # initialize stuff
```

`descrPreview: -> @descrText()` is redundant.

btw, I have no clue what you mean by "initialize logic"

**Comment by avalanche1** [comment]
The thing is that I have two different components inside one template: description & description preview (and I wouldn't want to add a separate template for each). Thus I have two logically different blocks of code inside my addPost tpl.
And each of them has some initialization logic in the onRendered callback, that's why I don't want to put them inside the same viewmodel code block - because I want to have them logically separated within tpl.addPost code.

**Comment by avalanche1** [comment]
btw, I tried 
```coffee
T.viewmodel.extend
		descrPreview: ->
			@descrText()
```
and it gives `T.viewmodel.extend is not a function`

**Comment by ManuelDeLeon** [comment]
I still don't know what you're doing but I'm pretty sure you're going about it the wrong way. You rarely need to use extend, blaze events, and callbacks. Blaze helpers are only needed when you're using `{{#if ` or `{{#each `.

Let's back up a sec. Here's an example of a text area and a preview div:

```jade
template(name='addPost')
  textarea(data-bind='value: description')
  #descrPreview(data-bind='html: description')
```
```cs
Template.addPost.viewmodel
  description: ''
```

What are you missing?

**Comment by avalanche1** [comment]
The only solution that worked for me and allowed me to keep my preferred template structure was this:
```coffee
## POST DESCRIPTION ##
	vm = new ViewModel
		descrText: ""
	T.onRendered ->
		vm.bind(this)
		#some code to init textarea-attached popup
## POST DESCR PREVIEW  ##
	vm.extend
		descrPreview: ->
			textLimit = 10
			if @descrText().length > textLimit then return @descrText().substring(0,textLimit) + '...'
			else return @descrText()
	T.onRendered ->
		#some code to init preview-attached popup
```
If there is a better way of doing this, pls advise.
`T.viewmodel.extend` didn't work while logically it should have.
