### ISSUE TITLE
bug with viewmodel name

### ISSUE THREAD

**Issue by peonmodel** [ManuelDeLeon/viewmodel#116]
repo here: https://github.com/peonmodel/adamant-waffle

naming the viewmodel causes a problem in that 'this' is bounded to the wrong instance
not naming the viewmodel avoids the problem

**Comment by Anima-t3d** [comment]
Related to https://github.com/ManuelDeLeon/viewmodel/issues/101
>
zimt28 commented on 1 Sep
Sure: https://github.com/zimt28/vm-issue
I noticed that it only happens when you give the viewmodel a name

**Comment by ManuelDeLeon** [comment]
That's because you're giving the same name to all bugged children. It works if you give a unique name to each (usually the id):

```js
	Template.buggedchild.viewmodel(function(child){
		return child._id;
	}, m);
```

Let me know if you have other problems.
