### ISSUE TITLE
Firefox error

### ISSUE THREAD

**Issue by wallslide** [ManuelDeLeon/viewmodel#119]
I'm getting the following error in Firefox, but not in Chrome/Safari:

```TypeError: arr is undefined1 manuel_viewmodel.js:1349:18```
using ```manuel:viewmodel@1.9.5```

The viewmodel in question is set up like this: 
```javascript
Template.header.viewmodel('vnLanguageSelector', {
  selectedLanguage: 'en',
  languages: [
    {
      name: 'English',
      value: 'en',
    }, {
      name: '简体中文',
      value: 'zh',
    },],
```

and the code in the page:
```html
<select class="form-control"
  data-bind="
    options: languages,
    optionsText: name,
    optionsValue: value,
    value: selectedLanguage">
</select>
````

I'm using Firefox `41.0.1`

**Comment by ManuelDeLeon** [comment]
Works for me... Firefox 41.0.1 / ViewModel 1.9.13

**Comment by wallslide** [comment]
Weird... the error goes deeper.

It looks like the binding in the html is getting pointed to the incorrect viewmodel somehow.  I have a template heirarchy like this:

```
-mainLayout
  -header
```

and it looks like in Firefox the binding code is being bound to the mainLayout viewmodel instead of the header's viewmodel (it works fine in Chrome though, except for one time when it had the same error as Firefox). When it is broken, I get errors like this:

```
Property 'selectedLanguage' not found on view model: manuel_viewmodel.js:1176:13
Object { _vm_id: "_vm_masterLayout", dispose: ViewModel/this.dispose(), _vm_hasId: true, _vm_properties: Array[1], _vm_delayed: Object, _vm_children: Object, children: ViewModel/this.children(), _vm_reservedWords: Array[29], _vm_addDelayedProperty: ViewModel/this._vm_addDelayedProperty(), _vm_addParent: ViewModel/this._vm_addParent(), 13 more… } manuel_viewmodel.js:1177:13
Property 'languages' not found on view model: manuel_viewmodel.js:1176:13
Object { _vm_id: "_vm_masterLayout", dispose: ViewModel/this.dispose(), _vm_hasId: true, _vm_properties: Array[1], _vm_delayed: Object, _vm_children: Object, children: ViewModel/this.children(), _vm_reservedWords: Array[29], _vm_addDelayedProperty: ViewModel/this._vm_addDelayedProperty(), _vm_addParent: ViewModel/this._vm_addParent(), 13 more… } manuel_viewmodel.js:1177:13
Property 'selectedLanguage' not found on view model: manuel_viewmodel.js:1176:13
Object { _vm_id: "_vm_masterLayout", dispose: ViewModel/this.dispose(), _vm_hasId: true, _vm_properties: Array[1], _vm_delayed: Object, _vm_children: Object, children: ViewModel/this.children(), _vm_reservedWords: Array[29], _vm_addDelayedProperty: ViewModel/this._vm_addDelayedProperty(), _vm_addParent: ViewModel/this._vm_addParent(), 13 more… }
```
and when I looked at the viewmodel that was being logged to the console, it was the masterLayout's viewmodel instance.

**Comment by ManuelDeLeon** [comment]
Try to make a repro.

**Comment by wallslide** [comment]
I'm having trouble isolating the issue. It consistently happens in my project that binds in my html are being bound incorrectly to the parent template's viewmodel instead of the current template's viewmodel. When I try to setup a simple project to reproduce the issue, it doesn't happen. 

If I could push the problem project to a live site, would you mind taking a look?

**Comment by ManuelDeLeon** [comment]
That's really tough, even if the site was in debug.

Take your app and start removing  things (js, html, css) until you can't
remove anything else.

**Comment by wallslide** [comment]
I couldn't reproduce it on my staging server either so... I guess since it only happens in development on one browser, it probably isn't a big issue. I'm able to work around it anyways by putting the viewmodels in child templates anyways, instead of putting one in the child and one in the parent.

Thanks.
