### ISSUE TITLE
toJS exports non-context properties

### ISSUE THREAD

**Issue by peonmodel** [ManuelDeLeon/viewmodel#121]
```
// var data = {_id: 'string1', name: 'string2', some_property: true};
Template.test.viewmodel({
canEdit1: function(){return true;},
canEdit2: data.some_property,
changeCanEdit1: function(){this.canEdit1(false)},  // this doesnt work
changeCanEdit2: function(){this.canEdit2(false)}, // this works but...
submitData: function(){
var new_data = this.toJS();  // problem is that new_data 
// is now:{_id: 'string1', name: 'string2', some_property: true, canEdit2: false}
// i dont want the canEdit2 property in my new_data
doSomething(new_data);
},
});
```
suppose i have something like the above, how should i export the updated data?
currently i been using data.hasProperty(h) and loop/compare it against this.toJS() to only get my keys back

**Comment by ManuelDeLeon** [comment]
canEdit1 is a tautology.it doesn't matter what you call it with,it will
always return true.

Tojs returns canedit2 because its part of the viewmodel.is ypu don't want
it there you have to pluck the values you need.

**Comment by peonmodel** [comment]
ok, i would suggest a feature that plucks the values that is also in my initial data context, i think that be useful
in my use case, i have a form that populate from existing data and allow users to edit them, which i then need to update the changed values to my collection
