### ISSUE TITLE
Property not found on model if data-bind is set to other than 'text' and is a collection item

### ISSUE THREAD

**Issue by PeterSchumacher** [ManuelDeLeon/viewmodel#122]
Here's part of my template, (item is a collection item)
```html
        <p data-bind="text: item.image"></p>
        <img data-bind="attr: {src: item.image}" />
        <img data-bind="src: item.image" />
```

I expected a paragraph and two identical images but only got the paragraph.
```html
https://s3.amazonaws.com/uifaces/faces/twitter/meln1ks/128.jpg
````
In debug console,
Property 'item.image' not found on view model:
Property 'item.image' not found on view model:

Am I doing something wrong here? 
If I assign 'item.image' to a viewmodel property called 'image' and use that instead it works.

Thanks!

**Comment by ManuelDeLeon** [comment]
Update to 1.9.15

**Comment by PeterSchumacher** [comment]
Thanks!

**Comment by ManuelDeLeon** [comment]
Please test again with 1.9.16
I've already included this case in my tests but test it just in case.
