### ISSUE TITLE
optionsValue and optionsText does not invoke viewModel getters via getProperty

### ISSUE THREAD

**Issue by tuxbear** [ManuelDeLeon/viewmodel#124]
When using a viewModel as an option it seems like the text and value properties are not resolved in the usual way, but rather they are read directly from the options object.

If the option happens to be a view model, the properties are functions, and the value and text is the function text.

Is this by design? Looks like its these lines 163-165 in binds.coffee that should be using getProperty to resolve the text and value to use for the options

    for o in arr
      text = _.escape(if optionsText then o[optionsText] else o)
      oValue = _.escape(if optionsValue then o[optionsValue] else o)

**Comment by ManuelDeLeon** [comment]
If I understand you correctly then you're right. Please make a small repro with both cases so I can make sure we're on the same page. Thanks.

**Comment by ManuelDeLeon** [comment]
Sorry for the (exceptionally) late reply. My dog ate my homework and I was consumed with the release of ViewModel 2. 

This has been fixed in v1.9.17

**Comment by tuxbear** [comment]
Sweet, thanks for your work! Take good care of your dog, he seems hungry ;)

Happy holidays ;)
