### ISSUE TITLE
Blaze #each - no reactivity on context?

### ISSUE THREAD

**Issue by dnish** [ManuelDeLeon/viewmodel#125]
Hey Manuel,
just using your package "ViewModel" and find out, that there are some issues with the reactivity of a given context. For example, I'm using the following Template:

notification.js
````
Template.notification.helpers({
notifications: function() {return Notifications.find({}); }
});
````
notification.html
````
{{#each notifications}}
{{>notification_item}}
{{/each}}
````

notification_item.js
````
Template.notification_item.viewmodel(function(data) {
return {
likeCount: function() {return data.likes; }
}; });
````

So, when I receive a new like, "likeCount" doesn't get updated. At the moment, I'm using this fix:

notification_item.js
````
Template.notification_item.viewmodel(function(data) {
return {
doc: function() { return Notifications.find(data._id); }
likeCount: function() {return this.doc().likes; } //Now reactive
}; });
````

But is that the correct way? I'm just wondering if there are any performance issues when I do it like this way?

**Comment by ManuelDeLeon** [comment]
```js
Template.notification_item.viewmodel(function(data) {
  return {
    likeCount: function() {return data.likes; }
}; });
```

In this case `likeCount` is returning a constant. That's why it doesn't get updated. The notification_items view model inherits (so to speak) the likes and it's reactive so you can just use `likes`:

```js
Template.notification_item.viewmodel({
  printLikes: function() {
    console.log( this.likes() );
  }
});
```

**Comment by dnish** [comment]
Thank you very much :).

**Comment by dnish** [comment]
Sorry to ask you again, but is there any possibility to use this package (https://github.com/dburles/meteor-collection-helpers) with the method above? The helpers aren't defined within the ViewModel when I try to call <code>this.myHelper()</code> within my notification_item viewmodel.

**Comment by dnish** [comment]
Okay, the thing with the context is getting worse. I want to use a method also as a helper. Just reading some docs of my Stats collection:

````
    {{#each currentStats}}
        {{>earning_card}}
    {{/each}}
````

Defining a new view model and add a helper:

````
Template.earning_card.onCreated(function() {


    this.vm = new ViewModel({

        isCurrent: function() { return (moment().month() + 1) == this.month(); },
        formatDate: function() { return moment(this.createdAt).format("MMMM YYYY"); }
    }).addHelper('isCurrent',this);
});

Template.earning_card.onRendered(function() {
    this.vm.bind(this);
});
````

So, no properties of the "stat document" are available on the VM object. I've to call <code>this.vm.extend(this.data)</code> to add them to the VM object, but this will crash the template helper, because the template helper doesn't read the properties as a function, so in the case above I'll get an "this.month() is not a function" error. Uff...

**Comment by ManuelDeLeon** [comment]
I'm closing this one because it's an old question. If you're still having problems please open up a new ticket.
