### ISSUE TITLE
'enable' binding  to take a function

### ISSUE THREAD

**Issue by lucidprogrammer** [ManuelDeLeon/viewmodel#127]
Enable to take a function.

Please see the example and the requirement in the following code. Or is there any other way I am missing in this new version (2.0.0)? 

```

<template name="login">
  <form>
    <input type="email" name="email" placeholder="Username" pattern="[^@]+@[^@]+\.[a-zA-Z]{2,6}" required>
    <input type="password" name="password" placeholder="Password" required>
    <!-- Example @https://viewmodel.meteor.com/docs/bindings#enable works fine if we use a direct binding. However, sometimes we need to use a function as in this example. -->
    <button type="submit" class="primary" {{b "onclick: login, enable: enablePrimaryButton"}}>Login</button>
  </form>
</template>

Template.login.viewmodel({
  //using http://jqueryvalidation.org/
  //onRendered works perfectly fine and validates the form etc.
  onRendered: function(){$("form").validate();},
  //this really does not enable or disable the button.
  enableLoginButton: function(){return $("form").valid();},
  login: function(event){
    event.preventDefault();
    //do login action
  },
  autorun: function() {
    if(this.enableLoginButton()){
      console.log("button should be enabled now - but it does not do using view model template and the template");
      //Need to uncomment the following jquery for reactive enabling or disabling
      //$("button.primary").attr("disabled",false);
    } else{
      console.log("button should be disabled now - but it does not do using view model template and the template");
      //Need to uncomment the following jquery for reactive enabling or disabling
      //$("button.primary").attr("disabled",true);
    }
  }

});
```

**Comment by Anima-t3d** [comment]
You should not use `.attr()` anymore, use `.prop()` instead:
```javascript
// Disable #x
$( "#x" ).prop( "disabled", true );
 
// Enable #x
$( "#x" ).prop( "disabled", false );
```
Source: https://learn.jquery.com/using-jquery-core/faq/how-do-i-disable-enable-a-form-element/

>Attributes vs. Properties

>The difference between attributes and properties can be important in specific situations. Before jQuery 1.6, the .attr() method sometimes took property values into account when retrieving some attributes, which could cause inconsistent behavior. As of jQuery 1.6, the .prop() method provides a way to explicitly retrieve property values, while .attr() retrieves attributes.

Source: http://api.jquery.com/prop/

**Comment by lucidprogrammer** [comment]
Thanks @Anima-t3d, that's good info.

However, the purpose of my question is to see if I can avoid that part of the code inside autorun all together and the following alone can do the job

```
<button type="submit" class="primary" {{b "onclick: login, enable: enablePrimaryButton"}}>Login</button>
```

**Comment by ManuelDeLeon** [comment]
The problem is that `$("form").valid()` isn't reactive. You have to create a function that validates the contents of the form. There are many ways of doing it:

1) Check the properties explicitly
```
isValid: function() {
  return this.prop1() && this.prop2();
}
```

2) Adding validation to each property onCreated and then using it on isValid:
```
Template.example.viewmodel({
  prop1: '',
  prop2: '',
  onCreated: function() {
    var prop1 = this.prop1; // by reference
    prop1.valid = function() {
      return prop1(); // has data 
    };
    // Same for prop2
  },
  isValid: function() {
    for(var prop in this) {
      if (this[prop] && this[prop].valid && !this[prop].valid() )
        return false;
    }
    return true;
  }
})
```
Or my personal favorite:
3) Create a custom control. See https://viewmodel.meteor.com/docs/misc#controls
You create the custom controls that have a validation method and on the parent form you loop through the properties like on example 2.

**Comment by lucidprogrammer** [comment]
Thanks, that answers it, thank you, I guess I will go with the second approach for now.
