### ISSUE TITLE
{{b}} and {{on}} together in one element

### ISSUE THREAD

**Issue by brajt** [ManuelDeLeon/viewmodel#128]
Let's say we've got a following element:

`<input {{on'focus:focused(true), blur:focused(false)'}} {{b 'value:val, keyup:check'}}>`

Unfortunately, `{{on}}` gets overwritten by `{{b}}`. If I switch them, `{{b}}` gets overwritten by `{{on}}`. Is there a way to make them work together in one element?

I use `{{on}}` in this particular case because with `{{b 'focus:focused(true)', blur:focused(false)'}}` focused automatically becomes true when I create the template, even if I've got it defined as `focused: ''`.

**Comment by ManuelDeLeon** [comment]
That should work. I'll check it out.

Is there a reason why you're not using `focus`?

```html
<input {{b 'value:val, keyup:check, focus: focused'}}>
```

Btw, `keyup:check` is a smell. Most likely you don't need it and you can just check/validate `val` directly. For example:

```js
Template.example.viewmodel({
  val: '',
  valid: function() {
    return checkTheValueOf( this.val() );
  }
})
```

**Comment by ManuelDeLeon** [comment]
yep, it works:

```html
<input type="text" {{b "value: name" }} {{on "focus: focused(true), blur: focused(false)"}}>
```

```js
Template.body.viewmodel({
  name: '',
  focused: false,
  autorun: function() {
    console.log( "Focus is now: " + this.focused() );
  }
});
```

But again, you should just use `focus`:
```html
<input type="text" {{b "value: name, focus: focused" }}>
```

**Comment by ManuelDeLeon** [comment]
err... scratch that. You're right =p

I'll see what's going on and fix it.

**Comment by brajt** [comment]
Focus: focused was a great advice, thanks! Somehow I didn't realize this could be done so easily, even if I used to do it this way in Angular before switching to Meteor/Blaze. I'm still trying to make it work without keyup but if you say it should work, I'll sooner or later find it out.

**Comment by brajt** [comment]
I did make it work without keyup. Thanks again! Turned out I was just editing js and html of different templates. In moments like that I appreciate js and html being in one file in React. ;-)

**Comment by ManuelDeLeon** [comment]
Okay, v2.1.1 fixes the issue using `{{b` and `{{on` at the same time.

Thanks for the heads up and let me know if you have any questions.
