### ISSUE TITLE
Using global template helper?

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#129]
Suppose I have a global template helper:

~~~
Template.registerHelper do
  \myGlobalHelper
  ->
     doSomething!
~~~

How to use myGlobalHelper in binding like those defined in VM?

Tried:
~~~
span.drawin-badge.bg-red($b="text: myGlobalHelper()")
~~~

But VM complained the VM doesn't have a property called 'myGlobalHelper'.  Is it possible, if so how?

**Comment by ManuelDeLeon** [comment]
Without knowing anything about your app I'd do the following:

```html
<span>{{myGlobalHelper}}</span>
```

That said, I wouldn't use global helpers unless it's absolutely necessary. I suggest you use mixins instead: https://viewmodel.meteor.com/docs/viewmodels#mixin

**Comment by daveeel** [comment]
Ha I am trying too hard to use VM. Need to pull back a bit. Shall take a look again at mixing. Thanks.
