### ISSUE TITLE
Case Study: this & scope

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#130]
Hi @ManuelDeLeon , I have a case which is quite confusing but could be worked around. Just wondering if there's easier / cleaner way in VM.

The VM structure is like this with workaround
~~~
Template.playView.viewmodel do
  autorun: ->
    fa = this.fa
    fb = this.fb
    d3.xml do
      ...
      (d) ->
         fa(fb) # <--- falling this.fa() will fail. that's why a reference is declared above
  fa: (fb) ->
    # declare like: fb = this.fb won't work here since fa lost it's VM scope when called inside d3.xml ?
    fb() # <--- calling this.fb() will fail. also declaring reference won't work. that's why I pass it via param 
  fb: ->
    ...
~~~

I could understand calling VM property / function need reference inside another object with async operation ( d3.xml in this case ). But why declaring reference of fb inside fa also failed?

**Comment by ManuelDeLeon** [comment]
The problem is that you're grabbing a reference to `fa` and then using it in another context (that of `d3.xml`. You need to grab a reference to the view model and it will work as expected.

```js
Template.playView.viewmodel({
  autorun: function() {
    var vm = this;
    d3.xml(function() {
      console.log( vm.fa() );
    });
  },
  fa: function() {
    return this.fb();
  },
  fb: function() {
    return "From FB";
  }
});
```

**Comment by daveeel** [comment]
I see. Shall go through the doc again. Thanks.
