### ISSUE TITLE
toJS / fromJS ?

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#131]
Hi @ManuelDeLeon , I learn from your previous cast: https://www.meteorcasts.net/ep/6 that you use toJS/fromJS for replay style state management. However these functions seems removed from V2. My question is how to achieve the same in V2?

Thanks.

**Comment by ManuelDeLeon** [comment]
I renamed them to .data() and .load()

They better represent what happens when you use them.

**Comment by daveeel** [comment]
Great! So in future you'll have documented API, right?
