### ISSUE TITLE
class / text conditional switching

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#133]
I have something like the following. It's simply to switch different icon on one condition
~~~
.item-media
  i($b="class: {ion-locked: gameLocked, ion-unlocked: gameOpen}")
~~~
gameLocked and gameOpen are simple opposite conditions. Is it possible to do something like:
~~~
.item-media
  i($b="class: {ion-locked: gameLocked, ion-unlocked: not gameLocked}")
~~~

**Comment by daveeel** [comment]
Also, is there a similar conditional binding for text? i.e. show different text based on different conditions.
Not sure if custom binding is the way to go. An example will be great.

**Comment by ManuelDeLeon** [comment]
Most of the time you need to think of the view and the view model as two sides of the same coin.

For class:

```jade
i($b="class: gameStatus")
```
```coffee
Template.example.viewmodel
  gameLocked: false
  gameStatus: -> if @gameLocked() then 'ion-locked' else 'ion-unlocked'
```

The same for text:

```jade
label($b="text: greeting")
```
```coffee
Template.example.viewmodel
  isDay: true
  greeting: -> if @isDay() then 'Good Day' else 'Good Evening'
```
> Is it possible to do something like (not gameLocked)

```jade
i($b="class: { ion-unlocked: !gameLocked }")
```

**Comment by daveeel** [comment]
This style is preferred, since I'd like to keep UI stuff at template instead of putting them inside logic:
~~~
i($b="class: { ion-unlocked: !gameLocked }")
~~~
That's enough for binary condition. It's even better if there's facility for multi-condition (>2) switch. Thus we could avoid those many ugly "if else" statements at template level.

Same reasoning goes for text. It's preferable to leave text, say some i18n translation strings at UI template instead of putting them inside code. The best I could think of is like:
~~~
div($b="text: greeting( { a: 'i18n_s1', b: 'i18n_s2', c: 'i18n_s3' } )")
~~~
~~~
Template.example.viewmodel
   condition: \a
   greeting: (obj) ->
      obj[ @condition! ] # need key checking here...
~~~
Would love to see if there's more elegant alternatives. Thanks.

**Comment by daveeel** [comment]
Just tested and found that parameters of vm function call at binding only accepts string. Object is always undefined and array will results in unexpected token error. Are they true function call or sanitised ?

**Comment by ManuelDeLeon** [comment]
> I'd like to keep UI stuff at template instead of putting them inside logic

And in doing so you end up with logic in your template implemented in a clunky way.

As I said before the view and the view model are two sides of the same coin. Just like it's okay to sprinkle an `if` or `each` (logic) on your template, it's okay to use a class name on your view model.

Think about a vm as "the model of the view". When put that way it's perfectly fine to have a property that returns the correct class for an element.

**Comment by daveeel** [comment]
The current VM facilities are enough for what I want to  simplify my code, say, keeping all i18n strings at template level.

I understand your reasoning. Thanks for your reply.
