### ISSUE TITLE
Viewmodel 2 doesn't work with Jade anymore

### ISSUE THREAD

**Issue by satyavh** [ManuelDeLeon/viewmodel#135]
I'm really excited by viewmodel, but the new syntax doesn't work in Jade. Or at least, I can't get it to work. Also if you try the new syntax in the html to jade compilers, it messes up (example: http://html2jade.vida.io/). 
So I think Jade can't handle it, which means Viewmodel 2 forces devs to use plain html.

example viewmodel 1 with jade
`.div(data-bind="if: show")`

example viewmodel 2 with jade (not working
`.div({{b "if: show"}})`

it gives this error
````Jade syntax error: Unexpected character } expected ` `, `\n`,
   `,`, `!` or `=````

Thing is, in Jade this syntax will only work if the outcome of that helper is assigned to a valid html attribute. So `data-bind` worked perfect. But the outcome of the new `b` helper doesn't get assigned to anything.

Any chance the old syntax will be supported as well again?

**Comment by ManuelDeLeon** [comment]
See
https://forums.meteor.com/t/viewmodel-2-a-new-level-of-simplicity/13581/10

**Comment by satyavh** [comment]
thanks a lot! Got that part working :-)
