### ISSUE TITLE
Cannot pass child data context to parent function within binding

### ISSUE THREAD

**Issue by fvpDev** [ManuelDeLeon/viewmodel#137]
Ok...so I'm not quite sure how to do this and need help:
I'll start with my code.

page.js:
```
Template.page.viewmodel({
...
	isCurrentSection: function (sectionSlug) {
		console.log('sectionID: ' + this.sectionID() + ', sectionSlug: ' + sectionSlug);
		return this.sectionID() == sectionSlug;
//		return this.sectionID() == sectionSlug ? 'active' : '';
	},
...
});
```

page.html:
```
<template name="page">
...
			<div class="ui right aligned basic padded segment" id="{{ pageID }}Menu" {{ b "unless: this.sections == false" }}>
				<div class="thin ui massive horizontal link list">
					{{#each section in sections}}
						<a class="item" href="/{{ pageID }}/{{ section.slug }}" {{ b "class: { active: isCurrentSection(section.slug) }"}}>{{ section.name }}</a>
					{{/each}}
				</div>
			</div>
...
</template>
```

In my browser console I keep getting `undefined` for the `sectionSlug` but when I pass a text value like `isCurrentSection('slug')` I get the correct output.
I have also unsuccessfully tried
```
<a class="{{isCurrentSection section.slug}} item" href="/{{ pageID }}/{{ section.slug }}">{{ section.name }}</a>
```
but in this case regardless of what I pass to the helper function, whether it be `'slug'` or `section.slug` the helper doesn't seem to work at all. Can I not pass data to a method via a helper?

What would be the best solution/approach for this?

**Comment by ManuelDeLeon** [comment]
Don't use `{{#each section in sections}}` use `{{#each sections}}` instead. The reason is that Blaze doesn't change the context when you use `item in collection`. Then use `this.slug` inside the `#each`. See https://viewmodel.meteor.com/docs/viewmodels#this

I'll update the documentation to say "don't use `item in collection`"

**Comment by fvpDev** [comment]
Oh...yeah, I read that part when I read the docs for v2...trying now. I presume it doesn't matter which approach I use then?

**Comment by ManuelDeLeon** [comment]
Whatever is simplest :)

**Comment by fvpDev** [comment]
Ok, I tested both and it works beautifully. Thank you so much for your quick responses and the reminder lol, I appreciate it greatly.

**Comment by fvpDev** [comment]
Woah...actually I think I misread the console; the helper approach doesn't work but binding does. I tried
`class="{{isCurrentSection 'slug'}} item"` and `class="{{isCurrentSection this.slug}} item"` and neither work, so it looks like I can't pass a var to a helper function?

**Comment by ManuelDeLeon** [comment]
Use the class binding instead.
