### ISSUE TITLE
Suggestion: Method to convert reactive arra to standard array

### ISSUE THREAD

**Issue by satyavh** [ManuelDeLeon/viewmodel#138]
It's often quite useful to convert reactive arrays generated by Viewmodel to standard arrays, like for saving directly into mongo.

Now you have to do something like this:

```
nonReactiveArray = []

for item in @reactiveArray()
    nonReactiveArray.push item
```

I read properties have methods, like reset(). I think it would be useful for many to have a property method `raw()` that fetches the raw, non-reactive data. Is that an option?

**Comment by ManuelDeLeon** [comment]
reactiveArray.array()

See reactivearray.meteor.com

**Comment by ManuelDeLeon** [comment]
Btw, I think you can just save a reactive array to mongo (it's just a
wrapper). What error were you getting?

**Comment by satyavh** [comment]
Ok you're using that, I know that one.

I don't get an error, it's just being dropped completely. But that could also be Astronomers' fault (http://astronomy.jagi.io/).
