### ISSUE TITLE
Multiple callbacks

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#140]
Hello Manuel!
Does VM2 support multiple onRendered, onCreated, onDestroyed callbacks defined inside the same VM?
```coffee
Template.example.viewmodel
#component1
  name1: "abc"
  onRendered: -> alert this.name1

#component2
  name2: "xyz"
  onRendered: -> console.log this.name2
```
I understand that I can put `alert this.name1` and `console.log this.name2` inside one callback, but I need to logically separate my components.

**Comment by avalanche1** [comment]
Same question goes for events - can I declare them multiple times?

**Comment by ManuelDeLeon** [comment]
mixins and shares should allow for this (they don't right now). I'll make the change.

Now that you mention it, `.viewmodel` should accept more than one initial object. I have to think about it before making this change.

**Comment by ManuelDeLeon** [comment]
Okay, pick 2.6.0:

* .load now accepts an array of objects
* You can now load multiple objects when you define a view model( .viewmodel({ load: objOrArray }) )
* Loaded objects can have their own autorun/onCreated/onRendered/onDestroyed properties.

**Comment by avalanche1** [comment]
Cool!
