### ISSUE TITLE
Bug? Binding not working in contentFor

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#142]
Hi @ManuelDeLeon , I found an unexpected binding behaviour issue. It could be easily reproduced with iron:router and code as below:

route.ls
```livescript
Router.configure do
  layoutTemplate: \layout

Router.route do
  \/
  name: \home
```
layout.html
```html
<template name="layout">
  <div class="navbar">
      {{>yield 'navBarInner'}}
  </div>
    {{>yield}}
</template>
```
home.jade
```jade
template(name="home")
  +contentFor 'navBarInner'
    div This is dynamic content for yield
    div Can you see the binding text? 
    //- Binding not happening
    div($b="text: helloText")
    //- spacebar works
    {{helloText}}
  div binding works outside +contentFor --------------
  div($b="text: helloText")
```

VM code: home.ls
```livescript
home = Template.home
  ..viewmodel do
    hello-text: "Hello Text From VM???"
```

I have a testing project reproducing the issue. Let me know if you'd like to have it.

**Comment by ManuelDeLeon** [comment]
The problem her is that as far as ViewModel is concerned `contentFor` is
just another template so it looks for a view model for it. When it doesn't
find one, it creates an empty one for it. I don't know how one would get
around it given that contentFor is a template, but I'll see what I can do.

Blaze does pick up the value because the context cascades. It's not a good
thing btw, it makes apps harder to read and debug.

**Comment by daveeel** [comment]
I see...

I have blaze conditional statements in the real project that works using the VM properties, so they should be treated by blaze as helper for the same reason you mentioned.

Questions:

1. If I really want to use VM in "contentFor", should I defined it in the "layout" template ?
2. Does VM treat "layout" as parent of "home" if I do so?

Thanks.

**Comment by ManuelDeLeon** [comment]
I'll give you an example tomorrow but just in case you want to play
around...

You need to create a mixin for the entire view model unde contentFor. Then
define a view model for contentFor with a function that takes the string
you call it with on the markup. Based on the string you use the appropriate
mixin. Everything else stays the same.

**Comment by daveeel** [comment]
Would love to see your example.

Basically my use case is a mobile app using the Framework7. I'd like to avoid navBar to re-render on every route change. It's visually faster if I could just have the content inside navBar to change, that's the reason of contentFor. Intuitively, the navBar context is certainly the same as the main content. That's why I end up with this issue.

**Comment by ManuelDeLeon** [comment]
Actually, now that I ran your code I think it is a bug after all. I don't have time right now but I will work on it later.

**Comment by ManuelDeLeon** [comment]
Fixed on v2.5.4

I have to say that's a confusing way to structure apps (adding blocks to one template which aren't displayed in that template but in a completely separate one).

**Comment by daveeel** [comment]
Thanks for the fix.

By "that's a confusing way to structure apps", do you mean the use of "yield" in general?

**Comment by ManuelDeLeon** [comment]
Not yield, how IR handles contentFor. Take a look at this:

```html
<template name="layout">
  <div>layout - start</div>
  <div class="navbar">
    {{>yield 'navBarInner'}}
  </div>
  {{>yield}}
  <div>layout - end</div>
</template>

<template name="home">
  <div>home - start</div>
  {{# contentFor 'navBarInner'}}
    <div>contentFor 'navBarInner'</div>
  {{/contentFor}}
  <div>home - end</div>
</template>
```

It will output:

```
layout - start
  contentFor 'navBarInner'
  home - start
  home - end
layout - end
```

So contentFor is part of the home template but it's displayed on the layout template. That's confusing.

**Comment by daveeel** [comment]
Not sure if I got you, that "output" is displayed at home route, while the layout template is never displayed. 

I'm fine to make sense of this structure with IR so far. I'm hoping to switch to Flow Router but I have too much legacy codebase and package depending on IR now. I'll think about what you mean.

What's your suggested structure for the same result?

**Comment by ManuelDeLeon** [comment]
> Not sure if I got you, that "output" is displayed at home route, while the layout template is never displayed.

Nope, it displays layout and inside layout it displays/yields the home template. But then part of the content of home (contentFor) isn't displayed on home, it's displayed outside on the layout template instead. That's what I find confusing.

If I understand your requirement correctly, you're trying to alter the layout depending on the route. So if you're in home, the header should display something related to home. If that's the case then I think it's much easier to understand if you keep the header logic in the header and say "if route is A then display X, if route is B then display Y". If you need the header to "communicate" with the home template you can always share the properties needed.

That said, if it's working for you then it's all good.

btw, update to v2.5.5

**Comment by daveeel** [comment]
Does your suggestion mean that to have ``<header... > <content...> <footer... >`` structure for all templates of different routes, where ``<header...>`` & ``<footer.. >`` are called? If so then that would be clearer. Downside is that we need to include them even we don't need dynamic change on some routes.

Thanks for the update.

**Comment by daveeel** [comment]
Hi @ManuelDeLeon , I am trying to move some old stuff (since this issue) back to contentFor block, just found that binding still not working ... the same code works if moved out of contentFor block. Interestingly, standard Blaze event handler is NOT working in contentFor as well... I shall take move tests and report back.
