### ISSUE TITLE
"this" inside Blaze "each"

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#144]
Hi @ManuelDeLeon , in the VM doc: https://viewmodel.meteor.com/docs/viewmodels#helpers
you mentioned "this" in #each, I'm not sure if I understand correctly. Here's my case:

```jade
each plays
   //- each play has attribute playId
   if isLastPlay
      //- display last play's stuff
   else
      //- normal stuff
```
Above, "isLastPlay" is a VM property that checks a few conditions that I need to use playId to fetch from other collections. Then in VM def:
```ls
isLastPlay: ->
   playRecord = Plays.findOne(this.playId)
   return ... # some boolean calculations ...
```
Here I'm expecting this.playId to be what I intended, however it's undefined. I also tried in template
```jade
if isLastPlay(playId)
 //- ...
```
That doesn't work as well (seems helpers as condition can't accept arguments in general, which is exactly what I need).

Any VM facility that could help my case ?

Thanks.

**Comment by ManuelDeLeon** [comment]
Inside a view model `this` refers to the view model. On the template it refers to the item from the `#each` block. 

In your case you need to do the following:

```
each plays
  if isLastPlay(this.playId)
    // display
  else
    // normal
```
```
isLastPlay: (playId) ->
   playRecord = Plays.findOne(playId)
   return ... # some boolean calculations ...
```

**Comment by daveeel** [comment]
It turns out if I move the helper to standard Template helpers block and call from template, that works:
```jade
if isLastPlay playId // also works as "this.playId"
```
I'll try again your usage...

**Comment by daveeel** [comment]
I tried putting the helper inside VM and called both "if isLastPlay(this.playId)" and "if isLastPlay this.playId" in jade. However in VM, always complains playId is not defined.

Could it be a bug?

**Comment by ManuelDeLeon** [comment]
Okay, this is weird. `if isLastPlay playId` should work with a view model. I'll take a look.

**Comment by ManuelDeLeon** [comment]
Pick up v2.7.1
`if isLastPlay playId` works now.

**Comment by daveeel** [comment]
Thanks. Now I can further cleanup my Template codes :)

A quick question: 
I have quite some legacy code like this:
```ls
game = Template.gameView
  ..onCreated !->
    @subscribe \game Router.current!params.gameId
```
For that I usually check in Template
```jade
  .page-content
    if Template.subscriptionsReady
```
Will that work the same if I move  the ``onCreated`` code under viewmodel ?

**Comment by ManuelDeLeon** [comment]
yep, use:

```js
Template.gameView.viewmodel({
  onCreated: function(templateInstance) {
    templateInstance.subscribe('game', params);
  }
})
```
