### ISSUE TITLE
Strange behaviour when binding input type=text value

### ISSUE THREAD

**Issue by jsworx** [ManuelDeLeon/viewmodel#145]
Hi,

Might not be a real issue, more of an annoyance.  If you do not include a name="xxx" attribute on the input element, the bindings do not work properly,  it appears to be random  if the bindings are applied to the input element or not.

Thanks

**Comment by ManuelDeLeon** [comment]
Make a repro. It can't be random.

**Comment by jsworx** [comment]
Still looking into whats going on here, 

Turns out the name="xxx" is not relevant, it still appears to be random, but after I added the name="xxx" it bound more frequently, then went back to binding some controls over others.  

I am trying to recreate the issue with as simple example as possible.

**Comment by jsworx** [comment]
I think you can close this issue, I have narrowed it down to a collection.find().fetch(); call that prepares an array of items for the control I'm trying to bind up.    Still can't recreate with a very small example.

Thanks.

**Comment by ManuelDeLeon** [comment]
Reopened? Got a repro?

**Comment by jsworx** [comment]
Just wanted to add some more info if you are interested.  Can't reproduce on example that would be small enough here yet.  I think its a "timing issue".  The templates that are binding up (its basically a list of textboxes) are dependent on a subscription.  If I wait on the subscription before displaying the templates they all work correctly.

**Comment by ManuelDeLeon** [comment]
The thing is that there's nothing I can do if I can't reproduce the problem.

**Comment by jsworx** [comment]
Understood, close it and I will use the work around.  I can't recreate outside of the enter application.
