### ISSUE TITLE
Order of autorun, onCreated, and onRendered calls

### ISSUE THREAD

**Issue by fvpDev** [ManuelDeLeon/viewmodel#146]
With the following:
```
Template.myTemplate.viewmodel({
	autorun: function () {
		console.log('autorun started');
		console.log('autorun finished');
	},
	onCreated: function () {
		console.log('onCreated started');
		console.log('onCreated finished');
	},
	onRendered: function () {
		console.log('onRendered started');
		console.log('onRendered finished');
	}
});
```

I get a console output of:
```
autorun started
autorun finished
onRendered started
onRendered finished
onCreated started
onCreated finished
```

I was just wondering what should be correct...the docs say that onCreated will run as soon as the template instance is created and that onRendered will run after the template has been rendered on the page and all bindings have been applied. Perhaps for my own clarification: rendering happens after creation, right? What are the order in which these functions are called?

**Comment by daveeel** [comment]
+1
It's best if the doc could clarify those run orders together with Blaze template. say, what if I have ``onCreated`` both in viewmodel and blaze, which got run first etc...

**Comment by ManuelDeLeon** [comment]
Good catch. Order of events is now correct (v2.7.2): onCreated -> onRendered -> autorun

**Comment by daveeel** [comment]
Hi @ManuelDeLeon , just tested v2.7.2. The order is:

Blaze onCreated
Blaze onRendered
VM onCreated
VM onRendered

Does it mean if we use VM, it's all better to avoid mixing with Blaze?

**Comment by ManuelDeLeon** [comment]
It depends on what you're trying to do. I never use Blaze's. The view model
onCreated happening after blaze onrendered is because some properties are
created after the render and it would be weird if they weren't available.
Now that I think about it there probably isn't any difference between vm's
onCreated and onRendered =/

I'll look into it.

**Comment by fvpDev** [comment]
Yeah I agree about Blaze... I feel that using its events/etc kinda becomes arbitrary if using ViewModel.
Thanks for the quick fix, good sir Manuel.
