### ISSUE TITLE
make viewmodel prop as private by convention

### ISSUE THREAD

**Issue by HatemJerbi** [ManuelDeLeon/viewmodel#147]
for  example all VM prop starting with "__ " are not returned by data() function.

**Comment by ManuelDeLeon** [comment]
Which property is being returned by .data() which shouldn't have?

**Comment by HatemJerbi** [comment]
take the example when populating the viewmodel with load() function, and then add some extra props by declaring them in the viewmodel. it will be very helpfull if there is the possibilty to get only the loaded props.

**Comment by HatemJerbi** [comment]
i think you can add an extra arg to .data() to specify excluded prop (regx or startwith)

**Comment by ManuelDeLeon** [comment]
Right now you can pass an array of names/strings that you want from .data
