### ISSUE TITLE
clear hot code pushes across different _id used by the same template

### ISSUE THREAD

**Issue by MeKarina** [ManuelDeLeon/viewmodel#148]
helloo,,

someone recommend this packages related my issue here...
https://forums.meteor.com/t/destroy-or-re-create-template/16032/

i read the docs that this packages is possible to `identifies view models by template name, parent (if any), location on page, and _id and vmTag properties (if any)`

is this mean that this packages possible to clear hot code pushes across different _id used by the same template..??

i implement below but not working...
```
Template.myTemplate.viewmodel({
  showCommentForm: false,
  persist: false
});
```

when i change `showCommentForm` into `true`,, and then move into another page which use the same template `myTemplate` but different `_id` data context,,, the current state remain `true`

any further explanation how to clear hot code pushes across different _id used by the same template..??

apologize for the question,,,

thank Youu,,,

**Comment by ManuelDeLeon** [comment]
I don't quite understand the question. Can you make a small repro so I can
see what you get and what you expect?

**Comment by MeKarina** [comment]
helloo @ManuelDeLeon  

thanks for Your response...

i'm new in github,,, i don't know how to create repo...

i write question on SO..
http://stackoverflow.com/questions/34689066/how-to-make-reactive-variable-remain-at-the-default-state-when-page-change

i hope you understand what my issue and what i expect...

thank You so muchh,,

**Comment by fvpDev** [comment]
I checked out your stackoverflow link...maybe you can use an `autorun` function?
See here: https://viewmodel.meteor.com/docs/viewmodels#autorun

**Comment by MeKarina** [comment]
@fvpDev thank You for Your recommendation,,,, =))
