### ISSUE TITLE
Problem with standard value

### ISSUE THREAD

**Issue by dnish** [ManuelDeLeon/viewmodel#150]
Hey Manuel,
I'm having an issue with ViewModel in combination with ReactiveArray. For example, I'm having this array:

    var userMessages = [{message:'hello',self:true}, {message:'hey, how are you'}];

Now I'm defining a messagebox viewmodel:

    Template.messagebox.viewmodel({
    messages: function () {
    return userMessages.list();
    }

    });

Template:

    <template name="messagebox">

    <div class="input-div"><input type="text" placeholder="{{_ "holder_text"}}" id="message"> <a class="" id="sendButton" {{b "click:parent.send"}}><i
            class="fa fa-paper-plane pink-text text-darken-1"></i></a></div>
    <div class="messages">

        {{#each messages}}
            {{>message}}
        {{/each}}

    </div>
    </template>

Now a single message:

    Template.message.viewmodel({
    self:false
    });

    <template name="message">
    <div class="message" {{b "class:{me:self}"}}>{{message}}</div>
    <p style="clear:both;"></p>
    </template>

This is what happens: Both messages will be displayed with class "me", but only 1 chat message has "self:true" as property. If I add "self:false" to the other message, everything works fine. I'm just wondering why he sets "self:true" for the message without the self property.

**Comment by ManuelDeLeon** [comment]
The example as you show it doesn't work. This works as expected:

```js
Template.messagebox.viewmodel({
  messages: [{message:'hello',self:true}, {message:'hey, how are you'}]
});
```

```html
<body>
{{> messagebox}}
</body>

<template name="messagebox">
  {{#each messages}}
      {{>message}}
    {{/each}}
</template>

<template name="message">
  <div class="message" {{b "class:{me:self}"}}>{{message}}</div>
  <p style="clear:both;"></p>
</template>
```

**Comment by dnish** [comment]
Mhhh okay, but in my case (just a new example) I got this, each message represents a ViewModel - the left one is correct, but the right one not.

Picture: http://www.tiikoni.com/tis/view/?id=7003070

The collection objects are correct.

**Comment by dnish** [comment]
So if my checks are right, the problem here was the missing Template.subscriptionsReady.

This one seems to work fine:

    {{#if Template.subscriptionsReady}}
                    {{#each messages}}
                        {{>message_text}}
                        {{/each}}
    {{/if}}
              
...and this one fails:


      {{#each messages}}
                        {{>message_text}}
      {{/each}}

I just don't understand this behavior.

**Comment by ManuelDeLeon** [comment]
Make me a github repro that I can clone.

As a side note, I'd put the isMe function in a mixin.

**Comment by ManuelDeLeon** [comment]
Let me know when you have a repro.
