### ISSUE TITLE
Binding does not work when coming form another page

### ISSUE THREAD

**Issue by jebarjonet** [ManuelDeLeon/viewmodel#151]
I have this very simple HTML: 
```handlebars
<img {{b "click: test" }} class="img-thumbnail" src="{{fileUrl picture}}">
```
and for the JS: 
```javascript
Template.index.viewmodel({
    test: function() {
        console.log("hello");
    }
});
```
When I start directly on the index it works correctly (when I click on the image I have my `console.log`) but when I start from another page or when I go on another page then return to the index, nothing happens when I click on the image.
The `b-id="NUMBER"` is still there but nothing happens. Any idea ?

**Comment by ManuelDeLeon** [comment]
Please make a repro. I don't know what you mean by go to another page.

**Comment by jebarjonet** [comment]
I am using the Iron Router. By "go to another page" I mean clicking in the menu to display another page, then clicking on "index" on the menu to go on this page again. I am currently trying out some things here and there, it is working correctly on some other pages I have so...

**Comment by ManuelDeLeon** [comment]
Try to make a small repro and I'll take a look.

**Comment by fvpDev** [comment]
What's the full code for index template .html and .js?

**Comment by jebarjonet** [comment]
You can see it in action here : https://github.com/jebarjonet/demo-viewmodel-broken

I added all the packages I am using on my real project.

The pages are *localhost:3000/test1* and *localhost:3000/test2*. As you can see, the button on **test1** only works when the page is loaded or refreshed. When you move to test2 then go back to test1, it does not work anymore. On the other hand, the button on test2 works all the time.

The only difference between the two is that I have a `data` attribute on the route of test1 (I am using the Iron Router). test2 does not have data coming from the router. Did I miss anything ?

**Comment by ManuelDeLeon** [comment]
I'll fix it later on but man how I hate to put in code to get around Iron Router (it's not the first time I have to put in some hack because of IR).

**Comment by jebarjonet** [comment]
I hope it is no big deal :/ II really appreciate viewmodel and I hope you will be able to solve this soon since almost all of my templates data comes from the `data` attribute of my routes. With this bug freezing bindings when navigating, the whole project is frozen. :(

**Comment by ManuelDeLeon** [comment]
I'm  pretty sure I know how to fix...

**Comment by fvpDev** [comment]
Ok bro, I figured it out...this is what is causing the problem:
```
    progressDelay: 200,
    progressSpinner: false
```

**Comment by ManuelDeLeon** [comment]
Okay, now I'm confused. Why does it work with one route and not the other?

**Comment by fvpDev** [comment]
No idea...but it seems like the package is getting a lot of unsolved issues. I'm considering checking the code out one day if I have time.
Like finding out the why behind this issue: https://github.com/Multiply/iron-router-progress/issues/54
...gotta see how it's written.

**Comment by jebarjonet** [comment]
You are right. By removing the **iron-router-progress** package everything worked well again, especially `onCreated` and `onRendered` that had strange behaviors. So I removed it temporary, it is not a core package but it is pretty nice to show how the page is loading.

**Comment by ManuelDeLeon** [comment]
Closing this one as it's most likely a bug in another package.

**Comment by fvpDev** [comment]
@jebarjonet You should make your own progress displayer and base it off of viewmodel :D
