### ISSUE TITLE
Bind viewmodel to template

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#152]
Is there a way in VM2 to bind ViewModel to a template?
Like in vm1 I used to:
```coffee
vm = new ViewModel 'tplName'
T.onRendered -> vm.bind(this)
```

**Comment by fvpDev** [comment]
The only reason why I would see that you want to do this is to be able to reuse a viewmodel, in which case you can use a "mixin":
Check it out -> https://viewmodel.meteor.com/docs/viewmodels#mixin

Now you can have everything related to viewmodel inside one declaration, including template event hooks like onCreated, onRendered, onDestroyed, autorun.

https://viewmodel.meteor.com/docs/viewmodels#defining

**Comment by avalanche1** [comment]
I need to first create a vm and some time later attach objects to it. Docs say that I can do it with `.viewmodel.load(obj)`, but how do I reference `viewmodel`?

**Comment by ManuelDeLeon** [comment]
You gather the objects you want to load then declare the view model and
pass all objects in an array for load.

**Comment by avalanche1** [comment]
Still, is there a way to reference a viewmodel, attached to a given template?

**Comment by ManuelDeLeon** [comment]
`templateInstance.viewmodel` or most likely `Template.instance().viewmodel`

**Comment by fvpDev** [comment]
Try using the approach of having the viewmodel be the center encapsulation of your module.

**Comment by ManuelDeLeon** [comment]
+1 @fvpDev

**Comment by fvpDev** [comment]
@avalanche1 
Для меня этот метод работает отлично :D

**Comment by avalanche1** [comment]
@fvpDev Привет! А не мог проконсултьировать поподробнее? Через скайп-чат?
Если не против, постучись ко мне: artem shafranov, moscow

**Comment by avalanche1** [comment]
I've tried this and it doesn't work
```coffee
	T.viewmodel
		load:
			message: 'Can it be <b>bold</b>?'
	T.viewmodel
		load:
			message2: 'Can it be <b>thin</b>?'
```
This works:
```coffee
	vm1=
		message: 'Can it be <b>bold</b>?'
	vm2=
		message2: 'Can it be <b>thin</b>?'
	T.viewmodel
		load: [vm1,vm2]
```coffee

**Comment by ManuelDeLeon** [comment]
Yeah, you can only define a view model once and pass the different objects to load in an array. I rarely have to do something like this though (with mixins and shares).

**Comment by fvpDev** [comment]
@avalanche1 I would, but I don't know coffeescript nor jade...
