### ISSUE TITLE
Reactivity from array children ?

### ISSUE THREAD

**Issue by jebarjonet** [ManuelDeLeon/viewmodel#153]
I wonder if I did something wrong here, could you explain why it does not work as I expect it ?

The router sends data to the template : 
```javascript
Router.map(function () {
    this.route("/index", {
        data: function () {
            return {
                items: Items.find().fetch()
            }
        }
    });
});
```
*Items look like : *
```javascript
{
    _id: 123123,
    name: "Apple"
}
```
Template : 
```handlebars
<template name="index">
<div>
{{selected.name}}
</div>

{{#each items}}
<div>
    {{name}}
    <div {{b "click: select(this._id)"}}></div>
</div>
{{/each}}
</template>
```
Javascript : 
```javascript
Template.index.viewmodel({
    selected: undefined,
    select: function (id) {
        this.selected(_.find(this.items(), {_id: id}));
    }
});
```
I am using Lodash here. Then when I click on the `div` with the binding, the item is correctly selected and its name is displayed above.

**Problem :** When I change one of the item in the database, the items list updates reactively, but **not the selected one**. If I click again on the previously selected item, it updates on the selected. If it was really reactive, the selected item should update when the items list updates, should it not ?

**Comment by ManuelDeLeon** [comment]
You're doing a couple of things wrong here.

1) You should use IR just for routing and not subscriptions and data fetching.
2) You're going through all items to find one, use minimongo instead (collections are hashed by _id).
3) You're pushing data into the selected property. It should be a function that returns the item based on the selection.

Here's how it can look:

```js
Router.map(function () {
    this.route("/index");
});
```

```js
Template.index.viewmodel({
  items: function() {
    return Items.find();
  },
  selectedId: '',
  selectedItem: function() {
    return Items.findOne(this.selectedId());
  }
});
```

```html
<template name="index">
  <div>
    {{selectedItem.name}}
  </div>

  {{#each items}}
    <div {{b "text: name, click: selectedId(this._id)"}}></div>
  {{/each}}
</template>
```

That's the usual case, but if you're not going to use the selectedId for anything else, you can simplify it even further:

```js
Template.index.viewmodel({
  items: function() {
    return Items.find();
  },
  selected: null
});
```

```html
<template name="index">
  <div>
    {{selected.name}}
  </div>

  {{#each items}}
    <div {{b "text: name, click: selected(this)"}}></div>
  {{/each}}
</template>
```

**Comment by jebarjonet** [comment]
You are right ! I have still some trouble using viewmodel logic. Until now, I used a lot of route `data` (especially since I was using the router progressbar) and worked as much as I could with that (not much minimongo though). Thank you :)
