### ISSUE TITLE
jquery dependency

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#154]
Hi Manuel,
Is it possible in future versions to drop jquery dependency in favor of vanilla js selectors engine? Or does VM uses jquery not only for dom traversal?

**Comment by ManuelDeLeon** [comment]
I don't see the point since Meteor uses jQuery. I'll drop it when Meteor
does.

**Comment by fvpDev** [comment]
Yes, I am using VM for not DOM-traversal only.

**Comment by ManuelDeLeon** [comment]
I don't understand, can you rephrase it?
