### ISSUE TITLE
How to get raw array from VM props?

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#155]
Hi @ManuelDeLeon, I have some props in VM like:
```ls
  testData: ['a', 'b','c','d','e']
```
Then I'd like to get the the array by
```ls
 @testData!
```
That always gives me
```ls
{"0":"a","1":"b","2":"c","3":"d","4":"e","length":5}
```

I was expecting to get back the raw array but turns out can't do so. Is there a way to get the raw array directly? Is this VM specific?

I could use
```ls
  testData: -> ['a', 'b','c','d','e']
```
But then I'm lost how to set the data ...

**Comment by ManuelDeLeon** [comment]
The array is converted to a reactive array.  You can get the raw one via
@testData().array()
