### ISSUE TITLE
Mixin...mix-match array? #FeatureRequest

### ISSUE THREAD

**Issue by fvpDev** [ManuelDeLeon/viewmodel#156]
Hey, I haven't tried this yet but I didn't see it in the docs.
https://viewmodel.meteor.com/docs/viewmodels#sharemixinscope
"To do so, instead of using a string or array of strings to declare the mixin/share, you use an object."
Can I have a mixin array of strings + objects like so?:
```
Viewmodel.mixin({
	parentMixin: {
		parentProp: 'asdf'
	},
	childMixin: {
		childProp1: 'asdfChild',
		childProp2: function () {},
	}
});
Template.parentTemplate.viewmodel({
	mixin: [
		'parentMixin', 
		{
			child: 'childMixin'
		}
	]
});
```
I want to be able to have "children" within a template but the children DOM will be created by the parent viewmodel onCreated() ... so I don't really need an corresponding childTemplate.html nor a viewmodel in my childTemplate.js.. I just need a child mixin. The rest is arbitrary.

I'm working a lot with http://snapsvg.io at the moment, which is why the children DOM elements will be created by the parent. I want to have the `parentTemplate` mentioned above be my svg and the children be polygons, paths, etc.

**Comment by ManuelDeLeon** [comment]
Pick up v2.8.0
I updated the docs: https://viewmodel.meteor.com/docs/viewmodels#sharemixinscope

**Comment by fvpDev** [comment]
SWEET! Ur awesome man!
