### ISSUE TITLE
Question - Pass a value by reference into a control?

### ISSUE THREAD

**Issue by pigabo** [ManuelDeLeon/viewmodel#161]
I created a generic control called `semanticInput`, which is a reusable input box with semantic UI styling.  However, I am unable to bind the `value` property of the `semanticInput` control **by reference**; in further detail, I created an object called `person` in `parent.js` for storing various input data, such as `firstName`, `lastName`, and `age`.  Ultimately, I want to pass those person fields by reference into the `semanticInput` controls as shown below so that the corresponding input values get stored into the person object with two-way binding.  Currently, they just get passed by value which is not what I desire.

Is there anyway to achieve this with ViewModel?  By doing so, the control is much more reusable and dynamic. Your help is greatly appreciated.

### parent.html
```html
<h1>Form for inserting a person:</h1>
{{>semanticInput label="First Name" valueRef="person.firstName"}}
{{>semanticInput label="Last Name" valueRef="person.lastName"}}
{{>semanticInput label="Age Name" valueRef="person.age"}}
````
### parent.js
```javascript
Template.parent.viewmodel({
  person: {
     firstName: "",
     lastName: "",
     age: ""
  }
})
```

### semanticInput.html
```html
<template name="semanticInput">
  <div class="field" {{b "class: {required: isRequired === true}"}}>
    <label>{{label}}</label>  
    <div class="ui input" {{b "class: {disabled: isDisabled === true}"}}>
      <input type="text" name="{{label}}" placeholder="{{label}}" {{b "value:valueRef"}}>
    </div>
  </div>
</template>
````
### semanticInput.js
```javascript
Template.semanticInput.viewmodel({
  label: "label",
  isRequired: false,
  isDisabled: false,
  valueRef:"" 
})
```

**Comment by ManuelDeLeon** [comment]
Sorry for the late reply. This one fell through the cracks.

The way you're trying to do things is a recipe for a really bad time. Instead of trying to pass a reference to the child (semanticInput) you should just pass (by value) the default value for the input and then reference the semantic input itself.

```html
<body>
  {{> person }}
</body>

<template name="person">
  {{>semanticInput ref='firstName' label="First Name" value=person.firstName }}
  <button {{b "click: logProperties"}}>Log</button>
</template>

<template name="semanticInput">
  <div class="field" {{b "class: {required: isRequired === true}"}}>
    <label>{{label}}</label>
    <div class="ui input" {{b "class: {disabled: isDisabled === true}"}}>
      <input type="text" name="{{label}}" placeholder="{{label}}" {{b "value: value"}}>
    </div>
  </div>
</template>
```

```js
Template.person.viewmodel({
  person: {
    firstName: "",
    lastName: "",
    age: ""
  },
  logProperties: function() {
    console.log( this.firstName.value() );
  }
});

Template.semanticInput.viewmodel({
  label: "label",
  isRequired: false,
  isDisabled: false,
  value: ""
});
```

See: https://viewmodel.meteor.com/docs/misc#controls
