### ISSUE TITLE
Make docs readable on mobile

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#163]
Currently table of contents and code snippets are very small compared to main text.

**Comment by ManuelDeLeon** [comment]
Sorry for the late reply. This one fell through the cracks as I've been busy with v3.0.0

I hate giving a "it works on my machine" kind of answer, but I honestly don't have time to fine tune the docs for all mobile devices, specially when it looks just fine on my phone's Firefox, Chrome, and Opera. Maybe it's the settings I use (full client, not mobile).
