### ISSUE TITLE
How to handle any keypress?

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#165]
Hi @ManuelDeLeon , I've checked the doc and tested in various ways, but can't get VM to handle keypress. So I am falling back to inserting plain inline JS and passing keyCode with Session then get VM to respond to Session change:
```js
    document.body.onkeydown = function(e){ 
     if (e.keyCode === 27 || e.keyCode === 191 || e.keyCode === 83) {
       Session.set('KEYCODE', e.keyCode)
      }
    }
```
Wondering what's the best way ... Thanks!

**Comment by ManuelDeLeon** [comment]
Use `keypress`, `keyup`, or `keydown`

```
<body>
  <input {{b "keydown: logKey"}}>
</body>
```

```
Template.body.viewmodel({
  logKey: function(event) {
    console.log(event);
  }
});
```

See https://viewmodel.meteor.com/docs/bindings#events

**Comment by ManuelDeLeon** [comment]
I assume that's for a given input box. If it's for a keypress on the document (like you have) I'm working on an elegant way to handle such events (stolen from Elm).

**Comment by daveeel** [comment]
Ah yes, I want to handle the document keys. Here's my new toy project for learning Semantic-UI using VM: http://moonlight.meteor.com
There I'd like to try achieving full keyboard navigation. Currently I only have the '/' key to clear input box and focus on it. When the input box is focused, the key sometimes works sometimes not, if it's not working, pressing ESC will do. Maybe it's VM or maybe it's Semantic-UI, I'm not sure...

**Comment by ManuelDeLeon** [comment]
I think you'll like the new solution. Hang on, I should have it ready
today.

**Comment by ManuelDeLeon** [comment]
Okay, update to manuel:viewmodel@2.10.0-beta

Here's a pacman example.

```html
<body>
  {{> pacman }}
</body>

<template name="pacman">
  <!-- x and y are set in the autorun based on what key is pressed -->
  <p {{b "text: 'Pacman Position: ' + x + ',' + y"}}></p>

  <!-- We're using the signal (mousePosition) directly so no autorun is needed -->
  <p {{b "text: 'Mouse Position: ' + mousePosition.x + ',' + mousePosition.y"}}></p>

  <img
    src="https://upload.wikimedia.org/wikipedia/commons/2/26/Pacman_HD.png"
    height="50px"
    width="50px"
    {{b "style: { position: 'fixed', left: x + 'px', top: y + 'px' }"}}>
    <!-- I so hate adding the px's             ^^^^           ^^^^   -->
    <!-- I'm seriously thinking of adding them automagically like React -->
</template>
```

```js
ViewModel.signal({
  keyboard: {
    keydown: {
      target: document,
      event: 'keydown'
    }
  },
  mouse: {
    mousePosition: {
      target: document,
      event: 'mousemove'
    }
  }
});
```

```js
Template.pacman.viewmodel({
  signal: ['keyboard', 'mouse'],
  x: 0,
  y: 0,
  autorun: function() {
    // Depend on the keydown stream
    // (acquired from the 'keyboard' signal)
    var key = this.keydown().which;

    // Get the non reactive values,
    // otherwise the autorun will depend on values
    // that it changes further down (causing an infinite loop)
    var x = this.x.value ;
    var y = this.y.value ;

    if (key === 37) { // left
      this.x( x - 10 );
    } else if (key === 39) { // right
      this.x( x + 10 );
    } else if (key === 38) { // up
      this.y( y - 10 );
    } else if (key === 40) { // down
      this.y( y + 10 );
    }
  }
});
```

I'm still playing with the api so please let me know how it goes on your real world application.

**Comment by daveeel** [comment]
pacman is great :)
will try in my use case soon.

**Comment by daveeel** [comment]
By the way, I tried remove "px", still works on Safari & Chrome on OSX. Sometime ago I read some css optimisation guide mentioned "px" could be omitted.

**Comment by ManuelDeLeon** [comment]
It works for any event so you can just use `touchmove` instead of `mousemove`

**Comment by daveeel** [comment]
The new solution works cleanly for my use case so far. I get all expected behaviour I need. Unpredictability is gone :+1:

**Comment by ManuelDeLeon** [comment]
Mind sharing how you're using it? I want to see what you came up with...

**Comment by daveeel** [comment]
If you mean the running app, it's supposed to be: http://moonlight.meteor.com/ (Can't update now due to meteor.com deployment issue)

For code, I simply follow your pac man pattern. 
Relevant fragments :
```jade
  .ui.right.icon.input(tabindex='0')
    input#search-box(autofocus placeholder="search packages ..." $b="value: search, focus: focusSearchBox, change: limit(defaultLimit)")
    i.search.link.icon($b="unless:search")
    i.remove.link.icon($b="if:search,click:resetSearchBox('')")
```
```ls
ViewModel.signal do
  keyboard:
    keydown:
      target: document
      event: \keydown
```
```ls
lunr-search = Template.lunr
  ..viewmodel do
    signal: <[ keyboard ]>
    focus-search-box: true
    reset-search-box: ->
      $ '#package-detail' .modal \hide
      @search ''
      @focus-search-box true
    autorun: ->
      key = @keydown!which
      # console.log "VM key: #{key}"
      if key == 191
        @reset-search-box!
```

**Comment by daveeel** [comment]
Next, I'd like to handle same key in different elements.

1. If search box has focus, it only respond to `/` or `ESC` for leaving the box. That should be easy with what I know.
2. If search box has no focus, I'd like to press `i` to show info modal.

What I'm not clear is: if search box is focused, pressing `i` will also trigger the `i` key of bigger scope (document). That'd be undesirable. So where should I declare something like `stopPropagation` in the new VM signal handling?

**Comment by ManuelDeLeon** [comment]
My brain is a little fried right now but it seems to me you need to share the focusSearchBox property with whichever view model will handle the `i` and only show the info modal if the search box doesn't have focus.

**Comment by daveeel** [comment]
Just updated http://moonlight.meteor.com . I think the full keyboard functions in my mind are 99% done. That would be much much difficult and tedious without VM, especially the bleeding signal handling :)

And yes,  `i` key for `show-info` is easily handled by checking `unless @focus-search-box!`

**Comment by daveeel** [comment]
One more elegant solution I'm still looking for is scroll to bottom/top detection. Would that be possible to be included in VM, or already easy ?

**Comment by daveeel** [comment]
Too bad the keyboard operation doesn't work on iPad with Wifi keyboard ... the input box even can't blur ...

**Comment by daveeel** [comment]
Hi @ManuelDeLeon , I am trying to use signal in a new project. But I encounter a strange situation. I follow exactly the same setup of the previous working keyboard handling, however I keep having `this.keydown is not a function at ... autorun`  error.

I checked from console that `ViewModel.signals.keyboard.keydown` does exist. And checked many times `signal: ['keyboard']` is the same. What would be the possible cause of signal not shared or attached to the VM? Is there anyway I could manually attach signal to VM on console to debug?

Thanks.

**Comment by ManuelDeLeon** [comment]
Maybe it's a timing issue where the autorun executes before the signal is
loaded. If that's the case then it should be resolved when I check in the
fix for #160 (I'm still working on it).

Make me a repro just in case.

**Comment by daveeel** [comment]
Let me try to send you a working app which could reproduce the error .

If it's a timing issue, then why after everything were loaded, there's still such error when I manually invoke on console like: `ViewModel.findOne('people').keydown()` ?

**Comment by ManuelDeLeon** [comment]
Got a repro?

**Comment by daveeel** [comment]
I've sent an App to your gmail box 2 days ago and you replied to look at it. You must be too busy :)

**Comment by daveeel** [comment]
Let me try 3.0 and see if the issue still exists.

**Comment by ManuelDeLeon** [comment]
Doing my best here =D

**Comment by daveeel** [comment]
Bravo! The expected behaviours are back with 3.0.
