### ISSUE TITLE
How to use dynamic object key in binding?

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#166]
Hi @ManuelDeLeon , I have something like:
```jade
each arts
  span($b="text: lang()")
  span($b="text: this.name.en]")
  span($b="text: this.name[lang()]")
```
`lang` is a shared prop which returns `en` here. Now the 1st & 2nd span are fine. `en` is an attribute of the `name` field of arts record.
However, the 3rd span returns an object and I am stuck to get that language value. I also tried but failed too:
```jade
  span($b="text: this.name['en']")
```
I have quite many fields to show...
The question is , how to make the binding value dynamic according to variable?

**Comment by ManuelDeLeon** [comment]
Viewmodel doesn't parse brackets. I will add it but not soon enough for
you. In the meantime you can create a function I  the same view model which
takes an art, and then pass this to it in the markup.

**Comment by daveeel** [comment]
Thanks. That's also what I thought as last resort. Shall use this way before VM supports the required parsing.

**Comment by ManuelDeLeon** [comment]
I'm closing this one as I don't know when/if I'll have time to work on it.

**Comment by daveeel** [comment]
Thanks. Will there be any suitable place to mark it down like a wishlist for the project?

**Comment by ManuelDeLeon** [comment]
I had one of those on another open source project and it became a guilt
list. That's why I'm closing this one.
