### ISSUE TITLE
How to bind to textarea?

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#167]
The following gives jade error
```jade
textarea($b="text: someValue")
```
binding to `value` also not working. is this a .jade or VM issue?

**Comment by ManuelDeLeon** [comment]
Use value, not text.

**Comment by daveeel** [comment]
`value` doesn't work for me. It give error: `Jade syntax error: Cannot read property 'length' of undefined`
Maybe it's jade issue. Will keep checking.

**Comment by daveeel** [comment]
Just rediscovered that I've reported the issue to https://github.com/dalgard/meteor-jade/issues/4
It's related to: https://github.com/mquandalle/meteor-jade/issues/57
Too bad there's no fix yet ...

**Comment by daveeel** [comment]
`value` is right, just not for .jade. Have to work around by putting the field in a child template.
```html
<template name="aboutField">
  <textarea {{b "value: parent.about"}}></textarea>
</template>
```
