### ISSUE TITLE
How to upgrade to 3.0.0-beta? Not in atmospherejs

### ISSUE THREAD

**Issue by fvpDev** [ManuelDeLeon/viewmodel#168]

**Comment by ManuelDeLeon** [comment]
I pushed the changes by mistake. I usually do it with a release. I still
have to test a few things.

Sorry for the confusion.

**Comment by fvpDev** [comment]
Okie dokie. Thnx for the quick response

**Comment by fvpDev** [comment]
I have a quick question though...with the order of what is loaded when the viewmodels are constructed I thought that mixins would be loaded before the direct props, but it's the other way around. I was hoping to have mixin properties and then diff viewmodels that have diff functions that rely on those mixin properties but I keep getting errors that a certain property hasn't been defined yet. I've had to work around this by making the direct props into mixin objects and then loading it in the vm in order that I need.

**Comment by ManuelDeLeon** [comment]
I admit there's a degree of subjectivity here. I had to make a choice so here's the priority:

1. Direct Properties
2. Load
3. Mixin
4. Share
5. Signal

Regarding mixin vs direct properties. The way I see it if you want a view model to have a property in a mixin you would write:

```js
Template.example.viewmodel({
  mixin: 'container'
})
```

So if you go through the trouble of adding a property to view model with a default value, it's because you *really* want that property to have that default value:

```js
Template.example.viewmodel({
  mixin: 'container',
  propAlsoInMixin: 'n/a'
})
```

And thus direct properties have higher priority than mixins.

**Comment by fvpDev** [comment]
Are direct props referring to the data context that is passed to the template inclusion `{{> example propAlsoInMixin=asdf }}`? I have been assuming `propAlsoInMixin` is an example of a direct prop, yeah? Based on that I decided to define default values and functions of properties within the actual mixins rather than just declaring the property name and the its data type and was hoping whatever direct properties were in the `.viewmodel({})` definition what simply override them like so:
```
ViewModel.mixin({
  container: {
    type: 'default',
    primaryAction: function () {
      // do default action which is nothing
    }
  }
});
Template.jumpingContainer.viewmodel({
  mixin: 'container',
  type: 'jumper',
  primaryAction: function () {
    // jump action
  }
})
```

**Comment by ManuelDeLeon** [comment]
In your example the jumper property and method will override the default.

I forgot about properties passed in the context (asdf in your example),
they will have top priority because even if you give jumper type a default
value, if you call the template and specify a type, then the view model
should respect that value.

**Comment by fvpDev** [comment]
It doesn't seem to be working for me. See the console for
http://sentientrising.meteor.com/services/graphics

It's for the svg element in the middle of the screen.

Also, if I have `mixin: ['mixin1', 'mixin2', 'mixin3']` which one loads first? Each mixin has values that override the previous one. You'll see in the example I have been reserving to defining a mixin for each viewmodel and then just mixing it into the viewmodel as a work-around because the direct props haven't been overriding the mixin values. (problem property is 'className' in the viewmodel).

**Comment by ManuelDeLeon** [comment]
The 3.0.0-beta (not released yet) should give you the expected results. If
not then make a repro.

In your example mixin 2 overrides mixin 1, and mixin 3 overrides mixin 2.

**Comment by fvpDev** [comment]
Can't wait! Haha as soon as it's released I'll be launching my new company website to replace the current, petty one-page http://sentientrising.com

**Comment by fvpDev** [comment]
"In your example mixin 2 overrides mixin 1, and mixin 3 overrides mixin 2."
^ this isn't working for me either in some cases for some reason. Might just be an inline svg thing; it seems to only be messing up in those cases

**Comment by ManuelDeLeon** [comment]
Upgrade to v3.0.0 and let me know how it goes.

**Comment by fvpDev** [comment]
Nope, still not working. I updated http://sentientrising.meteor.com/ as a repre, see console log. (I deployed with --debug)

**Comment by fvpDev** [comment]
Beautiful! Property load behavior is as expected :D
