### ISSUE TITLE
Add meaningful error for .find and .findOne

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#169]
1st off - thanks a bunch for adding this - I was about to file a request for that feature, but you've already done it))
There's a small issue though: find should produce a meaningful error in case it cant find a given vm.
Currently there is:
![image](https://cloud.githubusercontent.com/assets/10534563/12741129/4cf73aba-c993-11e5-95c2-16fe9f57110c.png)

**Comment by ManuelDeLeon** [comment]
Thanks for the heads up. A better outcome is to return `undefined` so you can take action based on it. This is the behavior in v3.0.0

**Comment by ManuelDeLeon** [comment]
I updated the documentation: https://viewmodel.meteor.com/docs/viewmodels#find

Thanks again.

**Comment by avalanche1** [comment]
:+1:
