### ISSUE TITLE
onRendered property doesnt work in vm 3.0

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#170]
Does absolutely nuttin. 
2.9.3 works fine.

**Comment by ManuelDeLeon** [comment]
That's because I was in the middle of working on v3. It should be fine in v3.0.0

**Comment by avalanche1** [comment]
Ah, I see. I cloned your actual repo and it turned out to be 3.0)

**Comment by avalanche1** [comment]
In the end it seems not to work with the code pattern I'm using (gathering objects into array and then loading it with `vm.load`). See repro - https://github.com/avalanche1/test
Same goes for autorun - doesnt work with this pattern either.
2.9.3 works just fine

**Comment by ManuelDeLeon** [comment]
Pick up v3.3.1

**Comment by avalanche1** [comment]
Thank you, works fine
