### ISSUE TITLE
Exception in setTimeout callback

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#171]
I get these on hot code reload
![image](https://cloud.githubusercontent.com/assets/10534563/12742394/bf1ac26e-c99e-11e5-8a5c-84794bfdda64.png)

**Comment by ManuelDeLeon** [comment]
I don't see it. Make a repro.

**Comment by avalanche1** [comment]
Here's a repro: will add in 10 mins
![image](https://cloud.githubusercontent.com/assets/10534563/12822097/d3d67c4c-cb7f-11e5-8922-1dd648e99cac.png)

**Comment by ManuelDeLeon** [comment]
I don't get the error, it reloads fine. Btw the following is an invalid JS object. You can't repeat keys (onRendered)

```coffee
		T.viewmodel
			load: vmPropsArr
			#works only if the next onRendered is commented out
			onRendered: ->alert "Im working only if I'm the only 'onRendered'"
			onRendered: ->alert "Im working always - yay!"
```

**Comment by avalanche1** [comment]
Thanks for the notice!
But it's rather strange that u dont get those errors on HCR. I get them even [here](https://github.com/avalanche1/test2), where there is almost none atmosphere packages installed (which might have caused a collision of some sort)
Maybe that is because I install viewmodel in atypical way - into packages folder (remember, I couldn't install nothing younger than 1.9.3 because I had dependecy resolution probs in meteor v1.1?) - you can see it in the repo.
Could you install viewmodel as a package and test for errors?

**Comment by ManuelDeLeon** [comment]
I pretty much always use ViewModel from a folder. I sometimes get the "could not create unique identifier" error when I'm working on the markup and ViewModel gets "confused" as to which saved data goes where but it's solved with a refresh. It's not something I can reproduce though.
