### ISSUE TITLE
Add error when an event calls nonexistant property

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#172]
Like when ` $b= "change: setLength` and `setLength` doesnt exist.
Currently the console is silent.

**Comment by ManuelDeLeon** [comment]
That's because it adds "setLength" as a property on the fly. This is useful when you're in loops and don't want to create a separate view model for the contents of the loop. For example, the following works without an explicit view model:

```html
<body>
  <input {{b "value: name"}}>
  Hello: <span {{b "text: name"}}></span>
</body>
```

**Comment by avalanche1** [comment]
Ah.. that's smart. Could never guess it myself. Maybe a mention in the docs?
