### ISSUE TITLE
Log errors that occur when executing vm methods

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#173]
```
sometpl.viewmodel
  pwdLength: 0
  setLength: -> pwdLength($pwdField.val().length)
```
When running this code the console is silent.
But typing `ViewModel.findOne('sometpl').setLength()` produces `Uncaught ReferenceError: pwdLength is not defined`.
This error should be shown on runtime.

**Comment by ManuelDeLeon** [comment]
I get `pwdLength is not defined`, make a repro.

**Comment by avalanche1** [comment]
Yep, seems to be working fine in 3.3.2
