### ISSUE TITLE
please push v3.0.0 to atmosphere

### ISSUE THREAD

**Issue by HatemJerbi** [ManuelDeLeon/viewmodel#175]
thx

**Comment by ManuelDeLeon** [comment]
What do you mean?

![image](https://cloud.githubusercontent.com/assets/4257750/12757523/a4754c80-c995-11e5-8608-7233405562fb.png)

**Comment by HatemJerbi** [comment]
when i update the package from meteor (meteor update manuel:viewmodel) i get:
manuel:viewmodel        upgraded from 2.8.0 to 2.9.3
manuel:viewmodel-debug  upgraded from 2.5.1 to 2.6.0

**Comment by ManuelDeLeon** [comment]
That's because v3 is version bump so you have to tell meteor you're sure you want to move to the next version. I don't remember the exact command but it will tell you if you do 
`meteor update manuel:viewmodel`

See: https://github.com/ManuelDeLeon/viewmodel/blob/master/HISTORY.md

> onCreated now runs when the template is created. This means, by the time onCreated is called, the view model will not have properties automatically added from the markup. I don't expect this to affect many people, if at all. You should be able to upgrade without a problem.

**Comment by HatemJerbi** [comment]
ok thx
