### ISSUE TITLE
TypeError: autorun.call is not a function

### ISSUE THREAD

**Issue by fvpDev** [ManuelDeLeon/viewmodel#176]
Receiving the following in the browser console log, v3.0.0 update:
```
Exception from Tracker afterFlush function:
TypeError: autorun.call is not a function
    at results.push.fun (viewmodel.coffee:499)
    at view.js:199
    at Function.Template._withTemplateInstanceFunc (template.js:457)
    at view.js:197
    at Object.Blaze._withCurrentView (view.js:538)
    at viewAutorun (view.js:196)
    at Tracker.Computation._compute (tracker.js:323)
    at new Tracker.Computation (tracker.js:211)
    at Object.Tracker.autorun (tracker.js:562)
    at Blaze.View.autorun (view.js:209)
```

**Comment by ManuelDeLeon** [comment]
How can I reproduce it?

**Comment by fvpDev** [comment]
It's in the link I sent you yesterday... Is it working for you? I'll make a new repro that's simpler and send you the link, however it seems to have happened for each template that is rendered

**Comment by ManuelDeLeon** [comment]
I don't remember, did you send me a private message? If you can, just copy
/paste it here or send it again.

**Comment by fvpDev** [comment]
[vmRepros.zip](https://github.com/ManuelDeLeon/viewmodel/files/114945/vmRepros.zip)

**Comment by fvpDev** [comment]
Sorry bout the above .zip having wrong code and the `/.meteor/local` folder included, here's an update which also included v3.1.1:

[_vmTestRepros.zip](https://github.com/ManuelDeLeon/viewmodel/files/116023/_vmTestRepros.zip)

**Comment by ManuelDeLeon** [comment]
Thanks for the help
Pick up v3.1.2

**Comment by fvpDev** [comment]
You're awesome!

**Comment by fvpDev** [comment]
I noticed in History.md for v3.1.2 you put "Fix onCreated/onRendered/onDestroyed/autorun when using an array of functions"... I remember in the docs that you mention multiple functions only within the section for autoruns. I was wondering: so does this mean we can now have multiple functions (array of funcs) for onCreated/onRendered/onDestroyed as well?

**Comment by ManuelDeLeon** [comment]
Yes, you can now use an array of functions to run on onCreated/onRendered/onDestroyed

**Comment by fvpDev** [comment]
Getting this with viewmodel-react

**Comment by ManuelDeLeon** [comment]
Heh, I'll fix it... =)

**Comment by fvpDev** [comment]
Moving this over to there
