### ISSUE TITLE
Docs - Contents section doesn't scroll

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#177]
I cannot scroll down Contents section (on the left of the page). As you can see in the screenshot, Binding Argument isn't present in Contents section as it doesn't fit on my 16 inch screen.
![image](https://cloud.githubusercontent.com/assets/10534563/12779161/95d2ab36-ca77-11e5-8f11-c8e4f3d3e411.png)

**Comment by ManuelDeLeon** [comment]
That's an artifact of the left menu being fixed. There's nothing I can do there. It isn't that big of deal since you can always click on the last item you see and just scroll down. And that's when you're in a device with a really small screen and it doesn't allow zooming.

**Comment by ManuelDeLeon** [comment]
btw, I hope you understand that I do care about the documentation and I appreciate your help. It's just that my time is limited and I have to pick my battles. For example, adding missing documentation is high priority, clarifying something is lower on the totem pole, something like this (the menu bar on an unusually small desktop screen) isn't worth the time to fix.

**Comment by avalanche1** [comment]
Of course. Still, you could lift off some pressure if you allowed PRs for docs.
Add this css

```
    width: 180px;
    height: 90vh;
    overflow: auto;
    overflow-x: hidden;
```

**Comment by ManuelDeLeon** [comment]
It doesn't seem to do anything. I resize the screen but the menu doesn't scroll.

**Comment by avalanche1** [comment]
I have a nice scrollbar appearing on small screen:
![image](https://cloud.githubusercontent.com/assets/10534563/12941216/b21e5b92-cfe9-11e5-8b4c-fd5e1ad3099f.png)
You sure you have your css right?
I add the aforementioned style directly into devTools:
![image](https://cloud.githubusercontent.com/assets/10534563/12941243/df7d6a38-cfe9-11e5-848c-037e0580f770.png)
