### ISSUE TITLE
When mixin property is function, it is not overwritten...

### ISSUE THREAD

**Issue by fvpDev** [ManuelDeLeon/viewmodel#180]
When mixin property is function, it does not get overwritten neither with direct property nor context input.
Repro: https://github.com/fvpDev/_vmTestRepros
or .zip: [_vmTestRepro_issue_180.zip](https://github.com/ManuelDeLeon/viewmodel/files/119818/_vmTestRepro_issue_180.zip)

**Comment by ManuelDeLeon** [comment]
Pick up v3.3.3

**Comment by fvpDev** [comment]
Ok, so mixins are getting overwritten by direct props, however regardless if the loaded property is a direct prop function or a mixin function, the loaded property does not get overwritten by context input:

Repro: https://github.com/fvpDev/_vmTestRepros/tree/Issue_180_part2
or zip: [_vmTestRepro_issue_180_part2.zip](https://github.com/ManuelDeLeon/viewmodel/files/120129/_vmTestRepro_issue_180_part2.zip)

By the way, which do you prefer, zip or the github link?

**Comment by ManuelDeLeon** [comment]
I'll take a look. I definitely prefer a github repro. I can read it on my
phone.

**Comment by fvpDev** [comment]
Any update on this?

**Comment by ManuelDeLeon** [comment]
I'm back (kinda, haven't had time to work on this).

Pick up 3.3.5

btw, I've never notice the "unknown" commits. It's probably a product of the app I use for git "SmartGit". I'm not bothering to change it for now.

**Comment by fvpDev** [comment]
Perfect timing! :smile:
