### ISSUE TITLE
Invoke something when binding is done?

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#181]
Hi @ManuelDeLeon , I have some selection that I wish to use semantic-ui dropdown. However the options binding is taking some time to be ready. Such that I need an arbitrary timeout:
```ls
on-rendered: ->
  vm = @
  set-timeout vm.semantic-init, 500
```
The semantic-init function is simply `$('.ui.dropdown').dropdown()`
```jade
select.ui.search.dropdown($b="options: countries, optionsValue: code, optionsText: name, value: country")
```
Is there somewhere I could hook to invoke the semantic JS when VM binding is all done?

**Comment by ManuelDeLeon** [comment]
The problem is that the data isn't ready by the time the onRendered runs. It works just fine if you use an array. Use something like the following:

```jade
select.ui.search.dropdown($b="ref: countriesElement, options: countries, ...")
```

Use ref, `$('.ui.dropdown')` is an eyesore.

```coffee
Template.example.viewmodel
  dataReady: false
  onCreated: (t)->
    t.subscribe 'countriesData', => this.dataReady(true)
  autorun: ->
    if this.dataReady()
      this.countriesElement.dropdown()
```

**Comment by daveeel** [comment]
I know subscribe has on-ready hook, however my countries list is not from data subscription, it's computed from a package: `3stack:country-codes` returned from a VM prop like:
```ls
    countries: ->
      CountryCodes.get-country-codes!
        |> map ->
          code: it
          name: CountryCodes.country-name it
```
`ref` is good for single element init. Could multiple elements share one `ref` so that I could init them all at once?

**Comment by ManuelDeLeon** [comment]
It's the same concept. The list of countries is populated asynchronously so
you need to tap into whatever method/event tells you the list is ready.

Ref is specifically designed for single elements. You do need jQuery to
grab all at once. I'll think about it and maybe add something like it.

**Comment by daveeel** [comment]
I understand the async issue. If it's a self-baked method or the method didn't provide hook, there seems to be a racing condition:
e.g.
```ls
countries: ->
  retval = ... some manual calculation ...
  this.data-ready true
  return retval
```
Will `retval` has enough time to populate before `autorun` pickups up the `data-ready` signal? Is there a determined exec order?
That's why I'm still wondering if it's possible for VM to add generic `data-ready` hook/callback for each prop ...

**Comment by ManuelDeLeon** [comment]
fyi, I added the `refGroup` binding on v3.4.0
https://viewmodel.meteor.com/docs/bindings#refgroup

**Comment by daveeel** [comment]
Thanks for saving the eyesore!
