### ISSUE TITLE
Cannot resolve parent-child loop

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#183]
The example is a bit dumb, but I actually need this pattern in my app (it's much more convoluted in there but the pattern is the same).
See repro [here](https://github.com/avalanche1/test2)
I get `undefined `error, plus the `Migration.delete` error
![image](https://cloud.githubusercontent.com/assets/10534563/12943175/e4a7b450-cff8-11e5-87f2-608e0a453753.png)

**Comment by ManuelDeLeon** [comment]
Fixed on v3.4.1

btw, the way you structure your code is very confusing. Try to simplify it a bit on future repros. Something like:

```coffee
Template.parent.viewmodel 
  getChildProp: ->
    console.log @child('child').childProp()

Template.child.viewmodel
  childProp: 'childProp value'
  onRendered: ->
    @parent().getChildProp()
```
