### ISSUE TITLE
Style bindings not working

### ISSUE THREAD

**Issue by fvpDev** [ManuelDeLeon/viewmodel#185]
Repro: https://github.com/fvpDev/_vmTestRepros/tree/Issue_185

**Comment by ManuelDeLeon** [comment]
I'm looking into it.

**Comment by ManuelDeLeon** [comment]
The problem was that style required a string representing an object. I changed it so it accepts semi colons. Pick up 3.4.3

**Comment by fvpDev** [comment]
I coulda sworn I had commas in there... oh well, thanks a bunch!
