### ISSUE TITLE
No data context for bindings in "each X in Y"

### ISSUE THREAD

**Issue by jebarjonet** [ManuelDeLeon/viewmodel#189]
```html
{{#each document in documents}}
<button {{b "click: delete(document._id)"}}>
{{/each}}
```
Where documents is an array of objects. When I do that, the argument passed do the `delete` function is `undefined` for viewmodel, as if `document` from the `each ... in` never existed.

Works well with `each` without `in` (and passing `this._id`) since it changes data context locally.

There may be the same thing when using `let` instead of `with` on templates.

**Comment by ManuelDeLeon** [comment]
ViewModel doesn't work with each in. The reason is that Blaze doesn't
provide the context for me to use it.

**Comment by arggh** [comment]
This might be worth adding to the documentation. I just made a [repro of the issue ](https://github.com/arggh/mvissue2) and was about to post the same problem.

**Comment by ManuelDeLeon** [comment]
I added https://viewmodel.meteor.com/docs/viewmodels#each to the documentation.
