### ISSUE TITLE
strange behaviour with 'ref'

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#190]
```jade
input(tabindex="1" name="phone" $b= "value: phoneInput, change: phoneIsMobile, ref: $phoneInput")
```
```coffee
phoneIsMobile: ->console.log this.$phoneInput
```
Works fine.

If I change to:
```coffee
phoneIsMobile: ->console.log this.$phoneInput.val()
```
`$phoneInput` is no longer being attached to viewmodel and returns `undefined`.

**Comment by ManuelDeLeon** [comment]
You're using the same variable / property name for both value and ref.

**Comment by ManuelDeLeon** [comment]
I didn't notice the $ (don't know what it means) . Make a repro in html .

**Comment by fvpDev** [comment]
Is the $ not a way to pass the reference to `phoneInput` varibale instead of the value of `phoneInput`?

**Comment by ManuelDeLeon** [comment]
No clue what $ is about.

**Comment by avalanche1** [comment]
$ is just a part of variable name. I begin var names with $ to mark them being jquery objects.

**Comment by fvpDev** [comment]
I didn't know we can put ref into the binding declaration... I thought it had to be done in the template call `{{> exampleTemplate ref='refToExampleTemplate'}}`

**Comment by avalanche1** [comment]
https://viewmodel.meteor.com/docs/bindings#ref

**Comment by fvpDev** [comment]
I figured it out: In the binding docs examples you'll notice that he saves interactions with ref and refGroup when the template is rendered and uses onRendered or autorun for the interactions. Here's another way though:

```
if Meteor.isClient
  Template.tpl.viewmodel phoneIsMobile: ->
    console.log (if @refToPhoneInput then @refToPhoneInput else "not rendered yet")
    console.log (if @refToPhoneInput then @refToPhoneInput.val() else "not rendered yet")
    return
```

**Comment by ManuelDeLeon** [comment]
I don't know, that repro works fine. Try updating ViewModel and see if you still get the error.
