### ISSUE TITLE
Parameter of shared object does not updated

### ISSUE THREAD

**Issue by DQvsRA** [ManuelDeLeon/viewmodel#192]
When i update .name parameter on shared object i can't see it's updated on view

![anim](https://cloud.githubusercontent.com/assets/442111/13197447/b5b59fd2-d7fe-11e5-918e-1ae4a7831fc6.gif)

This is how it's set:

![image](https://cloud.githubusercontent.com/assets/442111/13197486/2aee269c-d800-11e5-974b-b49a2012eca0.png)

I try every possible combination with binding, like:
{{b "text: section.name"}}
 {{b "text: name"}} where name is name: this.section().name
 {{b "text: getName()"}} where getName: function(){return ... }

P.S. i forgot to say that this.section() (app.section) it's a shared property

Please help me and tell how to do it right?

**Comment by fvpDev** [comment]
What does the shared object `active` look like?

**Comment by DQvsRA** [comment]
It's a plain ValueObject 
(function(){
   SectionVO = function (input) {
      if(typeof input === "string"){
         _.extend(this, {
               _id         : new Meteor.Collection.ObjectID()
            ,  name        : input
            ,  descr       : ""
            ,  createdAt   : 0
            ,  contains    : 0
            ,  position    : 0
         });
      } else _.extend(this, input);
   }
})()

**Comment by DQvsRA** [comment]
ViewModel.share({
   active: {
      section: new SectionVO("")
   }
});

**Comment by fvpDev** [comment]
Not sure why you are doing it that way but maybe this will work? :
```
ViewModel.share({
    active: {
        section: function () {
            return new SectionVO("");
        }
    }
});
```
I think that the way you have declared `section` is not making a reactive var (just a theory).

Why are you doing it this way anyway? Why not make the SectionVO function into a ViewModel mixin?

**Comment by DQvsRA** [comment]
This shared property SectionVO is setup by menu like that 

Template.menu.viewmodel(function (context) {
   var sectionsCursor = Sections.find();
   var sectionCount = sectionsCursor.count();
   var sectionsArray = sectionsCursor.fetch();

   return {
         share          : "active"
      ,  selectedIndex  : 0
      ,  sections       : sectionsCursor
      ,  select         : function(id) {
            console.log("> Menu -> Item Selected:", id);
            // TODO: NEED TO IMPROVE
            var that = this;
            if(!that.section() || GID(that.section()) != id) {
               sectionsCursor.forEach(function (item) {
                  console.log("ID", item._id._str);
                  if(item._id._str === id) {
                     that.section(item);
                     return false;
                  }
               })
               Session.set(SessionVariables.SELECTED_ID, id);
            }
         }

the "select" called from child (menuItem) view who is hold SectionVO object

This shared section also shared with app template and update it's content every time new section is selected. But not name ...

**Comment by ManuelDeLeon** [comment]
Make a repro out the following (working) example:

```html
<body>
  <div {{b "text: section.name"}}></div>
</body>
```

```js
ViewModel.share({
  test: {
    section: { name: 'A' }
  }
});

Template.body.viewmodel({
  share: 'test'
});
```

That will print "A" as expected and I can change the section in the console and the text will change accordingly:

```js
ViewModel.findOne("body").section({ name: "B" })
```

**Comment by ManuelDeLeon** [comment]
I'll close this in the mean time. Feel free to re open it if you get a repro going.
