### ISSUE TITLE
Is there a way to add autorun as a mixin?

### ISSUE THREAD

**Issue by brajt** [ManuelDeLeon/viewmodel#193]
Is there a way to define autorun function as a mixin? And if there is, is it possible to define multiply autoruns this way for use by one template? F.e. one autorun in mixin A, second in mixin B, third in the template?

I tried this, but it doesn't seem to work for me.

```
ViewModel.mixin({
  test: {
    autorun: function() {
      console.log('name is now ' + this.name());
    }
  }
});

Template.testTemplate.viewmodel({
  mixin: 'test',
  name: 'brajt'
});
```

**Comment by ManuelDeLeon** [comment]
Mixins in general should be self contained. If it needs a property then the mixin should define it. In your case:

```js
ViewModel.mixin({
  test: {
    name: '',
    autorun: function() {
      console.log( this.name() );
    }
  }
});

Template.body.viewmodel({
  mixin: 'test'
});
```

You can always override the mixin's default value in the view model itself:

```js
Template.body.viewmodel({
  mixin: 'test',
  name: 'n/a'
});
```

And yes, you can supply multiple autoruns, onCreated, onRendered, onDestroyed with shared, mixins, load, or directly.

**Comment by fvpDev** [comment]
Update mixin docs?

**Comment by brajt** [comment]
Thanks. Turns out I was still using 2.9, after upgrading to current version, it started to work.

**Comment by ManuelDeLeon** [comment]
I'd still put the property in the mixin because it would be one thing less
to keep in mind when using it.

**Comment by brajt** [comment]
Yeah, I did put it there, thanks a lot for this tip. :)

**Comment by brajt** [comment]
> And yes, you can supply multiple autoruns, onCreated, onRendered, onDestroyed with shared, mixins, load, or directly.

I agree with @fvpDev that it would be great to read that in the docs. The idea of putting my reused onRendered in mixins helped me a lot and to be honest I wouldn't think of it if you didn't mention it here. :)

Thanks once again!

**Comment by ManuelDeLeon** [comment]
I updated the docs to reflect that.
