### ISSUE TITLE
Cannot access Meteor.user in property declaration

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#196]
`Template.name.viewmodel({property:Meteor.userId()})` returns undefined.
Even if I re-run this from console after template is fully rendered.

**Comment by ManuelDeLeon** [comment]
That's because you're invoking the method when the app is loaded. Don't use
the parentheses for userId (haven't tried it but it should work)

**Comment by avalanche1** [comment]
No, I have this template appear only after I click a button - my app is already fully loaded by that time.
And how can I not user parentheses? `Meteor.userId` is a function, is it not?

**Comment by ManuelDeLeon** [comment]
Yes it's a function but you're invoking the function when Meteor loads the
app, not when the template is instantiated. Replace Meteor userId with
console log to see what I mean.

**Comment by avalanche1** [comment]
Ok, I've fixed it with
```
Template.name.viewmodel({
  load:{
    property: Meteor.userId()
  }
})
```
But is there a way to do it without load??

**Comment by ManuelDeLeon** [comment]
Use a function that returns the userId

**Comment by ManuelDeLeon** [comment]
btw, if all you're doing is returning the userId then it's better to put it in a mixin so you can use it on other templates.
