### ISSUE TITLE
Is it possible to extend the current ViewModel?

### ISSUE THREAD

**Issue by dnish** [ManuelDeLeon/viewmodel#197]
Hi Manuel,
is it possible to "extend" the ViewModel with the properties of a collection object, f.e. something like this:

    Template.question.viewmodel({

    autorun:[
        function() {
            var check = Questions.find({id:FlowRouter.getParam("id")});
            if(check.count()) {
                _.extend(this,check.fetch()[0]);
               console.log(this.title());
            }

        }
    ]
    });

A question object would look like this <code>{title:'Hello',userId:1234}</code>

**Comment by ManuelDeLeon** [comment]
Use the load method.

**Comment by dnish** [comment]
Uff... thanks, I've just searched for "extend" in the docs and didn't find anything :D
