### ISSUE TITLE
HCP stopped working

### ISSUE THREAD

**Issue by dnish** [ManuelDeLeon/viewmodel#198]
I'm getting always the following error in console after I've edited a file and a HCP happens:

    Uncaught TypeError: viewmodel[prop] is not a function

It happens in viewmodel.coffee:629

The page isn't updating, I need to to a manually refresh. I've just added Astronomy to my project.

This is my VM:

````
Template.question.viewmodel({

    dbObject: {},
    id() {
     
        return FlowRouter.getParam("id");
    },

    answers() {
        return Answers.find({questionId:this.id()},{sort:{createdAt:-1}});
    },


    onCreated() {

        this.templateInstance.subscribe("question", this.id(), () => {

            this.dbObject(Questions.findOne({id: this.id()}));
        });
    }
});

````

**Comment by ManuelDeLeon** [comment]
Make a repro.

**Comment by dnish** [comment]
@ManuelDeLeon If I got it right, the <code>id()</code> method causes this error. After renaming it, everything works fine.

**Comment by ManuelDeLeon** [comment]
Then make a repro with just the id...

**Comment by dnish** [comment]
I don't know if we need repros for en empty Meteor project with one template and one ViewModel, but here it is:

https://github.com/dnish/viewmodel-id-repro

Just change the template to force a HCP and you'll get the error above.

**Comment by ManuelDeLeon** [comment]
I did need the repro because I thought it was a problem with FlowRouter. Anyway, update to 3.4.7

Thanks for the heads up.
