### ISSUE TITLE
Problem with changing values VM

### ISSUE THREAD

**Issue by dnish** [ManuelDeLeon/viewmodel#200]
Hey Manuel,
it's me again, I've faced with another problem. I've added a search to our project.

Now this is what happens: Type in a title into the search input and click f.e. on the second item. After that, the conversion should start. Then change your search to another title and click on the new second item again. This doesn't work anymore. You can click on all other items, but not on the second one. 

This also happens if you click at the beginning on the first item and after a change of the search title again on the first, etc....

This is the part of my template where I generate the item models:

      {{#if results}}
            <ul>
                {{#each results}}
                    {{>search_item}}
                {{/each}}

            </ul>
        {{/if}}

I don't know why this happens, I get no error console message.

**Comment by ManuelDeLeon** [comment]
This isn't enough. I need a repro.

**Comment by dnish** [comment]
Okay, will try to make a repo. The only thing I now see is that the failed ViewModel still has the same porperties, f.e. if I do

    ViewModel.find("search_item")[0].started()

...is it always true, even if I get new results. The default value for a new VM is false.

**Comment by dnish** [comment]
I'm seeing that on a new search <code>onRendered()</code> isn't executed on any of the new items.  Also all ViewModels still have the same id's, even if results change. Do you know any situation where this can happen?

**Comment by dnish** [comment]
@ManuelDeLeon Repro is available here: https://github.com/dnish/vm-search-repro


1. Type in a search title
2. Click on a item, you should see STARTED on that item.
3. Change the search title
4. STARTED stays on the item you've clicked on, so the ViewModel wasn't destroyed when you've changed the title.

**Comment by dnish** [comment]
It "works" when you add a timeout:

    Template.index.viewmodel({

    search:null,
    results:null,

    doSearch() {
       Meteor.call("getResults", (err,res) => {

           this.results(null);
            window.setTimeout(() => {
                this.results(res);
            },5000);
        });
    }

    });

**Comment by ManuelDeLeon** [comment]
Your collection needs to have an `_id` field.

This isn't a ViewModel issue. You'll get the same behavior in Blaze or React.

**Comment by dnish** [comment]
Ah thanks, I didn't know that.
