### ISSUE TITLE
Add 'disabled' attribute as a shorthand

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#201]
Add 'disabled' attribute as a shorthand, on par with src and readonly.

**Comment by ManuelDeLeon** [comment]
In general https://viewmodel.meteor.com/docs/bindings#enable already covers it.

I plan to remove the default attr shorthands and let you define which ones you want instead. Something like `ViewModel.addAttributeBinding(['src','href','readonly','placeholder', 'disabled'])`.

**Comment by avalanche1** [comment]
Ok, then we'll wait)

**Comment by ManuelDeLeon** [comment]
Pick up 4.0.0 and see https://viewmodel.meteor.com/docs/bindings#attr

**Comment by avalanche1** [comment]
Getting better every day))

**Comment by ManuelDeLeon** [comment]
Btw, Alan Brito is an old kids joke.
Q: What's the name of the shortest wire in Spain?
A: Alan Brito
(it sounds like "alambrito" which means short wire in Spanish)
