### ISSUE TITLE
rename some bindings

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#203]
Can we rename some bindings?
hide -> hidden
enable\disable -> enabled\disabled
That'll be more semantically correct

**Comment by ManuelDeLeon** [comment]
It isn't more correct as its perfectly fine to say "enable when something
is true". The biggest problem with -ed is that there are cases when you
can't use it (visible) and when it's just awkward (focused). That's why I
dropped the ed for the bindings.

**Comment by fvpDev** [comment]
+1 @ManuelDeLeon

**Comment by brajt** [comment]
I don't mind the naming as long as it is consistent across bindings.
