### ISSUE TITLE
Problem with ViewModel's class bindings

### ISSUE THREAD

**Issue by arggh** [ManuelDeLeon/viewmodel#204]
I'm not sure if this is a problem with ViewModel or Meteor, but:

If I try to use ViewModel's class binding to add or remove different  but partially overlapping combinations of classes, the declarations get overridden. Hard to describe in words, so here is a repro that explains the issue better:

[ViewModel class issue repro](https://github.com/arggh/viewmodel-class-issue)

This is annoying for example, if using Semantic-UI and trying to show different icons based on some value. The different icons' class declarations could be for example:

```
green check circle outline
```

```
orange circle outline
```

```
grey ban
```

And they would be shown based on this type of binding:

```
{{b "class: { 'green check circle outline': isYes, 'orange circle outline': isMaybe, 'grey ban': isNo }"}}
```

In this scenario, the green icon loses the `circle` and `outline` classes because it's also defined in the orange icon class list, which is not included based on the value of `isMaybe`

Also, would be nice if the class order would be respected. It's not necessary according to HTML spec, but for example Semantic-UI uses this type of approach where order of class names has importance, even duplicates are used to define different variations of elements. I think Meteor already changed Blaze in some future version to respect this, though it's a bit controversial.

**Comment by ManuelDeLeon** [comment]
I'll check it out tomorrow. Btw css classes don't care about order, even in
semantic ui (I use it all the time without a care for the order).

**Comment by arggh** [comment]
Semantic-UI _does_ care about class name order, it's in their documentation and also the way it works (according to my experience developing with it). This has caused some problems with Blaze for example, which removes duplicate class names. Try creating a responsive grid with Meteor 1.2:

```
<div class="ui grid">
   <div class="sixteen wide mobile eight wide tablet ten wide computer">
   ...
```
which, with Blaze currently, transforms to:

```
<div class="ui grid">
   <div class="sixteen eight ten wide mobile tablet computer">
   <!-- ...or something similar -->
```
There was an issue about this on Meteor repo, I think it got fixed recently.

Here's a quote from [Semantic-UI Grid documentation](http://semantic-ui.com/collections/grid.html) :

> **Significant Word Order**
> Grids include many variations for adjusting things like vertical or horizontal alignment, text alignment, or default gutter sizes.
> 
> Some multi-word variations, like left floated or right aligned are word-order dependent and require you to use adjacent class names.

Some people think (justifiably so) that Semantic-UI is begging for trouble going against the spec.

**Comment by fvpDev** [comment]
It took me a month to create my own ui with ViewModel. I'm almost "off" the semantic ui temptation lol you should try it.

**Comment by arggh** [comment]
Semantic-UI is really fast for prototyping when you are rapidly going over iterations. Once things start to click you can build your own pixel perfect UI in a month :)

**Comment by fvpDev** [comment]
Not sure what you mean by "pixel perfect UI" but I what I created for myself is just as useful as semantic ui for prototyping except for it's reorganized in a more efficient manner consistent with my version of meteor-boilerplate + viewmodel. Also, I have integrated SnapSVG and have svg elements as modules as well, so I really have no need for "pixel perfect" anything. Everything shall be responsive and reactive. :smile_cat:

**Comment by ManuelDeLeon** [comment]
Okay. Believe it or not it's working as expected. 

When you click a button it triggers a change in value and thus the class binding too. Let's say you click on Maybe. ViewModel will go to the first entry on the class binding 'green circle', isYes is false so it removes green AND circle. It goes to the second one, 'orange circle', isMaybe is true so it adds the orange and circle. It goes to the final one 'red circle', isNo is false so it removes red AND circle (key point here).

You should create a VM method that returns the right combination of classes for the element.

**Comment by arggh** [comment]
Ok, thanks. I was hoping it would work more like a switch, showing the combination of classes with 'true'  and dismissing the ones with 'false'. Then it would be addition-only approach, rather than a two-way evaluation where we have conflicting and last-overwrites-first class bindings.

Then I could keep templatey-stuff out of the viewmodel and in the template. Is there a downside to that approach?

I could also separate them, eg.

'''
   green: isYes, orange: isMaybe, circle: isYes || isMaybe, ....
'''
Though I think it would be a suboptimal solution.

**Comment by ManuelDeLeon** [comment]
Trust me on this one, your development life will be a lot easier if you
think of view components as the combination of the markup, the style, and
the code (the view model). They're all sides of the same triangle.

In your case the classes are part of the component, whether you put it in
the markup or the view model. Even if the class binding worked as you
expect, having a single method that returns the proper set of classes for
the element is a cleaner solution imo.

Sometimes it's good to separate code and markup, most of the time there's
no value in doing so.
