### ISSUE TITLE
Attribute bindings lose camelCase (necessary for inline svg elements)

### ISSUE THREAD

**Issue by fvpDev** [ManuelDeLeon/viewmodel#205]
Repro: https://github.com/fvpDev/_vmTestRepros/tree/Issue_205

1st svg sets attribute 'viewBox' whereas 2nd svg sets attribute 'viewbox' however because svg is xml, case is significant.

Lol I spent 4 hours racking my brain trying to understand what was going on.

**Comment by ManuelDeLeon** [comment]
The problem is that you're using an old version. Upgrade to v4.0.2 =)

**Comment by fvpDev** [comment]
Haha that's a good one. Thanks man!

**Comment by fvpDev** [comment]
It doesn't work if I were to use `ViewModel.addAttributeBinding('viewBox');`
```
	<div style='height: 1em; width: 2em; border: solid thin black'>
		<svg width='100%' height='100%' {{b "viewBox: viewBox"}}>
			<g>
				<rect fill='black' width='85' height='12' y='12'/>
				<rect fill='black' width='85' height='12' y='36.5'/>
				<rect fill='black' width='85' height='12' y='61'/>
			</g>
		</svg>
	</div>
```

**Comment by ManuelDeLeon** [comment]
I can't help you if you keep insisting in using old versions.

I honestly didn't test v4.0.3 (watching House of Cards) but it should be fine.

**Comment by fvpDev** [comment]
Works beautifully :D
