### ISSUE TITLE
Weird behaviour when using semantic-ui dropdown callback

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#207]
```coffee
Template.tpl.viewmodel
		autorun: ->
			console.log  'autorun function called ' + new Date
			$('#districtDD').dropdown('clear')
		propertyA: false
		onRendered: ->
			$('#districtDD').dropdown
				onChange: =>@propertyA()
```
try `ViewModel.findOne('tpl').propertyA(true)` in console.

I use [`.dropdown('clear')`](http://semantic-ui.com/modules/dropdown.html#/usage) (which essentially resets dropdown to initial value and triggers `onChange` callback) in autorun and have the `onChange` event on dropdown which calls a VM property. The autorun gets hit whenever that property is changed. But this shouldnt happen - the property is not directly called in autorun!
I guess, onChange callback somehow propagates itself into autorun declaration or smth....

repro [here](https://github.com/avalanche1/test)

**Comment by ManuelDeLeon** [comment]
`.dropdown('clear')` in the autorun triggers the `onChange` synchronously to it depends on `propertyA`.

**Comment by avalanche1** [comment]
How can this be? I don't understand.

**Comment by ManuelDeLeon** [comment]
I think it will be clear if you put a console log in the `onChange` (right before calling `@propertyA()`). You'll see that the autorun executes and prints to the console, then it calls the dropdown change, the `onChange` executes and it prints to the console and then calls `@propertyA()` which makes the autorun depend on `propertyA`.

If you want you can clear the dropdown inside a `Tracker.nonreactive` block. That way the autorun will not depend on `propertyA`.
