### ISSUE TITLE
"Don't have debug information for [$default]"

### ISSUE THREAD

**Issue by arggh** [ManuelDeLeon/viewmodel#209]
After updating viewmodel-debug today my Chrome dev console started filling with hundreds of messages like this:

`Don't have debug information for [$default]. Please report it at https://viewmodel.org/help. In the mean time you can turn off checks with `ViewModel.ignoreErrors = true`. See https://viewmodel.org/docs/misc#ignoreErrors for more information.`

**Comment by ManuelDeLeon** [comment]
Did you also update ViewModel?

**Comment by arggh** [comment]
Hmm. On a closer look, I get this when I run update:

```
$ meteor update
This project is already at Meteor 1.2.1, the latest release.
Your top-level dependencies are at their latest compatible versions.
                                              
The following top-level dependencies were not updated to the very latest version available:
 * kadira:flow-router 2.10.1 (2.11.0 is available)
 * manuel:viewmodel 3.4.10 (4.0.5 is available)

```

**Comment by arggh** [comment]
Removing and adding again resolved the issue.

**Comment by fvpDev** [comment]
Another way is to run `meteor update manuel:viewmodel --allow-incompatible-update`
