### ISSUE TITLE
Issue with Template.dynamic and hot code push?

### ISSUE THREAD

**Issue by hluz** [ManuelDeLeon/viewmodel#210]
I am trying to get hot code push to work but it appears to be some incompatibility with kadira:blaze-layout / Template.dynamic. Every time I trigger a hot code push, I keep getting:
```
Could not create unique identifier for an instance of template 'Page_home'. This can usually be resolved by wrapping a plain text in a div or adding a vmTag to the view model.
```

But it doesn't matter what I try (adding divs, ids, vmTags) it doesn't work. What am I missing?

Here is a repro of the problem: https://github.com/hluz/vmHot 

You can run meteor and trigger a hot code push (change some text in one of the html files for example) to see the message.

**Comment by ManuelDeLeon** [comment]
The problem is with the `appcache` package. It prevents the page to do its normal reload and ViewModel didn't account for that scenario.
Update to v4.0.6

**Comment by hluz** [comment]
Working great! 

PS. I just started using ViewModel in a new project and I'm loving it! Wish I had tried it before. Many thanks!

**Comment by ManuelDeLeon** [comment]
Don't tell me, blog about it! =)
