### ISSUE TITLE
Supported Events - Swipe?

### ISSUE THREAD

**Issue by fvpDev** [ManuelDeLeon/viewmodel#211]
Are jQuery mobile swipe events supported or should I do touch events? What do you suggest, and also what events _**are**_ supported?

Btw, I'm finally subscribed to VM :+1:

**Comment by ManuelDeLeon** [comment]
All events accessible via `$(element).on( 'eventName', callback)` and `element.addEventListener( 'eventName', callback)` are supported. I haven't played too much with mobile but others have built drag and drop, and swipe interfaces with ViewModel so I don't think you'll have problems in that area.

Thank you for subscribing. I hope you like the format of the videos =)
I was going to make one last night but got caught up working on ViewModel for React. I'm very pleased with the way it's turning out. It's even more succinct than the current API.

**Comment by fvpDev** [comment]
Gonna try to integrate http://labs.rampinteractive.co.uk/touchSwipe/demos/Swipe_status.html via https://atmospherejs.com/hedcet/touch-swipe
