### ISSUE TITLE
Can viewmodel and blaze in same file ?

### ISSUE THREAD

**Issue by crapthings** [ManuelDeLeon/viewmodel#213]
like react, or riot ?

**Comment by crapthings** [comment]
<template name="hello">
		
		<h3>hello</h3>

		<script>
			this.onRendered(function () {
				console.log(1)
			})
		</script>

	</template>

**Comment by ManuelDeLeon** [comment]
Viewmodel sits on top of Blaze so you can use anything you would with
Blaze. But the code you have there isn't valid Blaze.

**Comment by crapthings** [comment]
i know that is just some idea we can put blaze code and js code in same file

new extension or  spilt script from script tag

or let script acquire template context

**Comment by crapthings** [comment]
https://github.com/numtel/meteor-template-from-string/issues/4

can viewmodel check if template is exist ?

if not then using a template from viewmodel self from meteor-template-from-string

turn this

	Template.world = Template.fromString(`
		<button>{{label}}</button>
		{{> wiki}}
	`)

	Template.wiki = Template.fromString(`
		<h1>hello</h1>
	`)

	Template.world.viewmodel({
		
		label (label) {
			return label || 'wtf'
		},

		click () {
			alert(1)
		}
	})


like


	Template.world.viewmodel({
		template () { return `
			<h1>${this.label()}</h1>
		`}
		label (label) {
			return label || 'wtf'
		},

		click () {
			alert(1)
		}
	})

**Comment by ManuelDeLeon** [comment]
Search for dynamic templates.

**Comment by fvpDev** [comment]
http://docs.meteor.com/#/full/template_dynamic

**Comment by crapthings** [comment]
i mean use one file to write simple small component not split file into .html and .js

only js like what react and riot.

we use to

Template.templateName.events

Template.templateName.onCreated

Template.templateName.onRendered

blah blah blah

now we have 

    Template.templateName.viewmodel
        events
        onCreated
        onRendered

sometimes we only write a small chunk html but we have to split to two files

templateName.html
templateName.js

why not put into viewmodel

**Comment by daveeel** [comment]
Haven't tried but should be possible. Since templates are converted to .js anyway. Just need to know the Blaze API. Like React you could write in JSX or plain JS code.

**Comment by ManuelDeLeon** [comment]
See https://github.com/ccorcos/meteor-compile-view

**Comment by crapthings** [comment]
that looks cool
