### ISSUE TITLE
VM reserved words?

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#215]
Hi @ManuelDeLeon , lately, I'm making more components into controls. I'm wondering if you have a list of reserved words that I should avoid using them as internal props in a control. E.g. I have "value" that I should avoid in my head now. But is there any other ? It's best if they could be listed in the doc. Thanks.

**Comment by ManuelDeLeon** [comment]
See the beginning of this file
https://github.com/ManuelDeLeon/viewmodel/blob/master/lib/viewmodel.coffee
