### ISSUE TITLE
Enter event fires twice

### ISSUE THREAD

**Issue by dnish** [ManuelDeLeon/viewmodel#216]
Hey Manuel,
I've a chat application and have a problem with messages, that were added twice. At first I thought it is a problem with cluster, but now I can reproduce it on my local environment:

If my message contains "^^" at the end and I press enter, the enter event is fired twice. 

Here are example messages:

"Lol, yeah it was nice ^^" -> fired twice
"oh ^^ I didn't know that" -> fired once

Tested on Chrome v49 (Mac).

Do you need a repo for this?

**Comment by ManuelDeLeon** [comment]
I think that's enough. Very weird though.

**Comment by dnish** [comment]
I don't know if it is on Windows the same, but if I type in "^^" there is still a underline unter the last "^". It seems like Chrome is waiting for more input. If I press blank space, it doesn't move to the next space but seems to exit the "wait for another input" mode.

**Comment by ManuelDeLeon** [comment]
Gonna need a repro after all, "Lol, yeah it was nice ^^" works fine for me.

**Comment by ManuelDeLeon** [comment]
It could have been related to another issue. Try it with v4.0.10

**Comment by dnish** [comment]
Nope, update didn't fix it. Here is the repro:

https://github.com/dnish/viewmodel-enter


Just type in something with "^^" at the end and press enter, it is added twice. 

Here is a [picture](http://v82i.imgup.net/Bildschirm0900.png) about this issue. Just note the underline on the last "^", if it is there and I press enter, event is fired twice, if not, everything works fine.

**Comment by ManuelDeLeon** [comment]
I can't repro it.

![image](https://cloud.githubusercontent.com/assets/4257750/14219058/494f22fa-f815-11e5-8819-f3f1bfea495e.png)

I find it *really* strange that it doesn't work on Chrome. Now I don't know what to do about this one since I don't have a Mac. Submit a PR if you figure out what's wrong. Reopen if you can repro it on Windows or Linux.

**Comment by dnish** [comment]
@ManuelDeLeon Did you try to only press "^" once and then press enter? If I remember right, Windows is also wating for the second "^". Maybe it will cause the same behavior like on Mac.

**Comment by ManuelDeLeon** [comment]
Tried with one, two, and three.
