### ISSUE TITLE
Detect changes during runtime

### ISSUE THREAD

**Issue by dnish** [ManuelDeLeon/viewmodel#217]
For example, I want to fire an event if a user likes a message - but this should only happen, if it's happened during the runtime and not if the user reloads the page. So for example, I have this message VM which inherits from a collection:

```
Template.message.viewmodel({

 message:null,
 liked:false
});
```

I want to fire the event when the "liked" property changes from false to true, but it should not fire if it's true on the beginning. Normally I would do something like this:

```
autorun: [
    function() {
      if(this.liked()) { console.log("Event fired...");}
     }
]
```
...but this will also run on every page reload.

**Comment by ManuelDeLeon** [comment]
You then need show the events after the user starts the app, not the ones before. I wrote something similar here:

https://forums.meteor.com/t/reactivity-and-triggering-an-event-on-the-other-end-so-to-speak/20087/5?u=manuel

**Comment by dnish** [comment]
@ManuelDeLeon Just had an idea, what do you think about this?

Template.message.viewmodel({

 message:null,
 liked:false,
 wasLiked:false,
 
 onCreated() {
  this.wasLiked(this.liked());
  },

 autorun: [
  
  function() {
    if(this.wasLiked() != this.liked() { console.log("Fire event..."); } 
  }
]
});

**Comment by ManuelDeLeon** [comment]
I'm sorry but this question is regarding the overall design and structure of your system so I'm not in a good position to give an opinion. I will say that your code has a smell to it (too imperative). It may be symptom of a larger architectural problem.

**Comment by fvpDev** [comment]
I would something like 
```
Template.message.viewmodel({

 message:null,
 likes: 0,
 likes: function () { return this.likes() > 0 },

 autorun: [
  function() {
    if(this.liked() { console.log("Fire event..."); } 
  }
]
});
```

**Comment by dnish** [comment]
@fvpDev But in this case, it would fire automatically on every page reload, because it inherits the likes from the collection document. So for example, you have a posting which has 4 likes - if the user visits your page, <code>liked()</code> is automatically true and you fire an event (f.e. an animation) which you want to fire only if this like happened during your session.

**Comment by fvpDev** [comment]
Oh right, yeah I meant to l leave that onCreated fund in there in the same time. My bad
