### ISSUE TITLE
Duplicate events firing

### ISSUE THREAD

**Issue by hluz** [ManuelDeLeon/viewmodel#218]
Having a problem with vm appearing to create multiple identical event listeners on elements. Repro at [https://github.com/hluz/vmEvt.git](https://github.com/hluz/vmEvt.git).

To reproduce execute it and just add new Steps. The second time you add a step it fires two click events (causing two Steps to be created). The third time it fires three click events... Also, deleting existing Step(s) will also increase the number of events being fired the next time you add a new Step.

**Comment by arggh** [comment]
This can also be observed at [https://github.com/arggh/viewmodel-click-bind](https://github.com/arggh/viewmodel-click-bind), just pull the latest changes which updates ViewModel from 4.0.6 -> 4.0.9. The amount of events fired increases on every click.

**Comment by hluz** [comment]
@arggh, my repro is already at 4.0.9...

**Comment by arggh** [comment]
@hluz That is the repro which resulted in ViewModel updates `4.0.7`, `4.0.8` and `4.0.9`, so I thought I'd share the finding that the issue appeared somewhere between `4.0.7` and `4.0.9` and can be easily switched to appear or disappear in a repo that the creator of ViewModel already is familiar with :)

**Comment by hluz** [comment]
@arggh  Ok. I interpreted that you were saying that 4.0.9 fixes it, since the #214 (the issue your repro relates to) has been closed...

**Comment by ManuelDeLeon** [comment]
Fixed on v4.0.10

**Comment by hluz** [comment]
Many thanks!

**Comment by ManuelDeLeon** [comment]
Reopen if it doesn't work in v4.0.11

**Comment by hluz** [comment]
v4.0.11 did not regress it. All fine. Thanks.
