### ISSUE TITLE
Old bug about missing event bindings is back

### ISSUE THREAD

**Issue by arggh** [ManuelDeLeon/viewmodel#219]
The issue about missing event binds has resurfaced now with 4.0.10. All you need to do is update VM to 4.0.10 on the [old repo](https://github.com/arggh/viewmodel-click-bind) and selecting added list items does not work.

[Old issue](https://github.com/ManuelDeLeon/viewmodel/issues/214)

**Comment by ManuelDeLeon** [comment]
Reopen if it doesn't work in v4.0.11

**Comment by arggh** [comment]
I was about to file a completely new issue with v4.0.11, but in light of recent issues thought I'd triple check before posting - luckily it turned out to be a stupid mistake by _yours truly_ :)  Everything seems to work perfectly with v.4.0.11. Many thanks @ManuelDeLeon .
