### ISSUE TITLE
Bootstrap 3 hover doesn't work

### ISSUE THREAD

**Issue by illmat** [ManuelDeLeon/viewmodel#22]
Hey,
thanks for your good work so far.

I've tried using your "Login Box" Example with Bootstrap 3.
All I did was adding a "btn" class to the button:
```<a data-bind="enabled: canEnter, hover: showError" class="btn btn-primary">Enter Site</a>```
Now the errorText is never shown. 
The buttons enabled / disabled states are still working fine.

I am using the ian:bootstrap-3 package.

**Comment by ManuelDeLeon** [comment]
Make a repro for me...

**Comment by illmat** [comment]
https://github.com/illmat/mvvmTest
It looks like your events get overwritten by jquery or bootstrap.

**Comment by ManuelDeLeon** [comment]
Just ran your repro. I got a feeling this is going to give me a headache...

**Comment by ManuelDeLeon** [comment]
The good news is that it didn't give me a headache. The bad news is that the login example doesn't work with Bootstrap 3. In Bootstrap 2 <a class="btn"> looks like a button but behaves like a link in that you can interact with it (click it, hover, etc.). Bootstrap 3 makes it behave like a true button (you can't click it or hover over it).

So things are working as they should according to Bootstrap 3.

I'll add this to the list of reasons why I don't use Bootstrap 3...
