### ISSUE TITLE
Missing event bindings when using Blaze #if

### ISSUE THREAD

**Issue by arggh** [ManuelDeLeon/viewmodel#220]
If I have something like this using VM 4.0.10

```
{{#if showSomething}}
   <button {{b "click: doSomething"}}>Do Something</button>
{{/if}}
```

the events won't bind.

[Repro here.](https://github.com/arggh/viemwodel-blaze-if-issue)

This is a new problem in my experience, though similar to issues [#214](https://github.com/ManuelDeLeon/viewmodel/issues/214) and [#219](https://github.com/ManuelDeLeon/viewmodel/issues/219)

**Comment by ManuelDeLeon** [comment]
Reopen if it doesn't work in v4.0.11
