### ISSUE TITLE
Cannot read property 'name' of undefinedtemplateName

### ISSUE THREAD

**Issue by crapthings** [ManuelDeLeon/viewmodel#221]
viewmodel-checks.coffee:5 Uncaught TypeError: Cannot read property 'name' of undefinedtemplateName @ viewmodel-checks.coffee:5checks.T#viewmodel @ viewmodel-checks.coffee:58VmCheck @ viewmodel-checks.coffee:119ViewModel.check @ viewmodel.coffee:88Blaze.Template.viewmodel @ template.coffee:6meteorInstall.client.templates.login.login.coffee @ login.coffee:15fileEvaluate @ modules-runtime.js?hash=939c79d…:158require @ modules-runtime.js?hash=939c79d…:92(anonymous function) @ config.coffee:3

**Comment by daveeel** [comment]
Most likely you are still referencing to an instance which might have been removed when your code runs. Simply add existence check before referencing.

**Comment by ManuelDeLeon** [comment]
In your case the error is "Could not add the events for template '?'. The events property needs an object."

I am very curious on how you arrived at that error (a template with an undefined view). Please make a repro.

In the mean time update viewmodel-debug to v2.6.4
