### ISSUE TITLE
Any thoughts for Server side rendering

### ISSUE THREAD

**Issue by jamesgibson14** [ManuelDeLeon/viewmodel#225]
I user [meteorhack:ssr](https://github.com/meteorhacks/meteor-ssr) and was wondering if you have looked into applying viewmodel on the server?

**Comment by ManuelDeLeon** [comment]
Blaze in general doesn't play well on the server and so ViewModel for Blaze
wasn't designed for ssr.

I'm working on a ViewModel that uses React instead and it will be ssr
friendly.
