### ISSUE TITLE
vmTag & Dynamic Templating & Hot Code Pushes

### ISSUE THREAD

**Issue by fvpDev** [ManuelDeLeon/viewmodel#226]
How can I add `vmTag` to dynamic template? I'm having trouble with page contents loading dynamically into same component templates instead of rendering a new component template for each page's `items` as defined in each page object in a collection of pages (see below).

(I realize that rendering an app based on a collection is not the best thing but a while ago I ran with the idea of having a whole app be produced from one json file + a UX library so that I can have one file that distinguishes one of my clients from another, with the rest of meteor project being essentially the same, and so that once I create an admin back-end I can use it to add pages to the app/website).

See result here -> http://cch-website-61199.onmodulus.net.
Going to about page from home page breaks the layout, however refreshing about page after that renders it correctly of course. I don't want to have to create separate templates for each page because the layout for each page is defined in the page collection and components are produced by: 

```

<template name="page">
  {{#if page}}
    {{> Template.dynamic template="recursion" data=page }}
  {{/if}}
</template>

<template name="recursion">
  {{#if layout}}
    {{> Template.dynamic template=this.layout data=this }}
  {{ else }}
    {{#if items}}
      {{#each items}}
        {{> Template.dynamic template=this.type data=this }}
      {{/each}}
    {{ else }}
      {{> Template.dynamic template=this.type data=this }}
    {{/if}}
  {{/if}}
</template>
```

A page data object in the collection of pages looks like this: 
```
{
  'i': 2,
  'id': 'about',
  'name': 'About',
  'landing': {
    'type': 'container',
    'items': [
      {
        'type': 'header',
        'text': 'Welcome'
      },
      {
        'type': 'paragraph',
        'text': 'Welcome to this landing page'
      },
      {
        'type': 'anchor',
        'href': 'http://google.com/',
        'text': 'Go to Google'
      }
    ]
  }
}
```

As you can see in the `recursion` template, the `type` of each object in the page object `items` array defines a component to be rendered.

**Comment by fvpDev** [comment]
Maybe has to do with #210 ? I'm using v4.0.12

**Comment by fvpDev** [comment]
Found a solution that seems to work for now (for me at least...I have a vm for every single html element which is kinda why I need this for hot code push purposes so that I don't have to attach an _id to every single element that is rendered from a site json). Was wondering if you could let me know if there are any problems with the following, @ManuelDeLeon: 
```
ViewModel.mixin({
element: {
  id: '',
  vmTag() {
    return this.id() ? this.id() : this.parent().children(this.type()).findIndex((vm) => {
      return vm.templateInstance === this.templateInstance;
    });
  }
}
```

**Comment by ManuelDeLeon** [comment]
Aside from the performance hit, there is a chance for the json to change between HCP. You have to decide how likely is that to happen in your app. It may be that the answer is "extremely unlikely".

I have no clue how to make your life easier on this. I keep thinking "it should work without it" but I don't want you to waste time making a repro just to satisfy my curiosity.

**Comment by fvpDev** [comment]
It seems to be working well but I like the hot code push feature where the client gets refreshed automatically, and once I start creating admin back-ends to edit pages (site json) so that I can work through a portal and be mobile instead of at a computer, I'd like for the page to still refresh automatically for the client; not sure yet...there's such a small window of time for and such a small chance that someone can't just refresh the page for new data, but I like to always have the server running while I'm locally developing for now so that I don't have to hit F5 1000 times a day.

**Comment by fvpDev** [comment]
Still trying to figure out how I wanna do some things and developing my boilerplate
