### ISSUE TITLE
Display "block" on visible binding

### ISSUE THREAD

**Issue by dnish** [ManuelDeLeon/viewmodel#227]
Hey Manuel,
I'm using <code>{b "visible:showUser"}</code> on one of my divs. This div uses <code>display:flex;</code>. If showUser goes to true, the visible bindings seem to add a <code>display:block;</code> to the element. This destroys the flex layout. So the visible binding seems only to work on block elements?

**Comment by ManuelDeLeon** [comment]
Yes, if/visible use jQuery's show/hide functionality which is basically setting display to block/none. In your case use an `{{#if showUser}}` block instead.
