### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'n.vmId')

### ISSUE THREAD

**Issue by dnish** [ManuelDeLeon/viewmodel#229]
Hey Manuel,
my Kadira logs are full with the error above. It seems to happen only on mobile Safari, at the moment I can't reproduce it on my local environment.

Do you have any idea in which typical case this error is thrown?

**Comment by ManuelDeLeon** [comment]
No clue what Kadira is doing...

**Comment by dnish** [comment]
Ah I mean that it happens in my project and Kadira logs this errors. I only get this error and no information which part of my script causes it :(

**Comment by fvpDev** [comment]
you have any templates named "n" that only render on mobile?

**Comment by dnish** [comment]
@fvpDev Nope, there is to template that have this name. 

@ManuelDeLeon I'll close the issue because I can't reproduce, if I got more, I'll reopen it again.
