### ISSUE TITLE
[question] how to change the value of a property of a value reactively?

### ISSUE THREAD

**Issue by wuxianliang** [ManuelDeLeon/viewmodel#23]
Dear @ManuelDeLeon 
In my case, I have two classes of practices to do, I want to change one of them but keep the other unchanged. The following code works but reactively. How to modify the code? Or more clearly, how to pass a key of an object to a function to change the value of the very property reactively? Thank you very much!
```
new ViewModel {
  practices: { intAdd:10, intMinus:10}
  addTen: (key)->
    @practices![key] = @practices![key] + 10

}

```

**Comment by ManuelDeLeon** [comment]
In your case "practices" is converted to a function that returns the
object "{ intAdd:10, intMinus:10 }"

If you don't need the change to be reactive you can do:

new ViewModel({
practices: { intAdd: 10, intMinus: 10 },
addTen: function(key) {
this.practices()[key] += 10;
}
})

If you do need the change to be reactive then you need to create new object
(In the future I'll change it so you can just reset the object, without
cloning it. Sorry.)

new ViewModel({
practices: { intAdd: 10, intMinus: 10 },
addTen: function(key) {
this.practices()[key] += 10;
var clone = $.extend({},this.practices());
this.practices(clone);
}
})

**Comment by ManuelDeLeon** [comment]
In your case "practices" is converted to a function that returns the object "{ intAdd:10, intMinus:10 }"

If you don't need the change to be reactive you can do:

```
new ViewModel({
  practices: { intAdd: 10, intMinus: 10 },
  addTen: function(key) {
    this.practices()[key] += 10;
  }
})
```
If you do need the change to be reactive then you need to create new object (In the future I'll change it so you can just reset the object, without cloning it. Sorry.)
```
new ViewModel({
  practices: { intAdd: 10, intMinus: 10 },
  addTen: function(key) {
    this.practices()[key] += 10;
    var clone = $.extend({},this.practices());
    this.practices(clone);
  }
})
```

**Comment by wuxianliang** [comment]
I see! Thank you very much!

**Comment by ManuelDeLeon** [comment]
fyi, with v1.2.8 you can now do:

```
new ViewModel({
  practices: { intAdd: 10, intMinus: 10 },
  addTen: function(key) {
    this.practices()[key] += 10;
    this.practices(this.practices());
  }
})
```
Still not pretty but at least no cloning...

**Comment by wuxianliang** [comment]
It is good! Thank you.
