### ISSUE TITLE
.children with a function returns incorrect result

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#231]
```jade
template(name="signUp")
  +dropdown type='metro'
  +dropdown type='district'

template(name="dropdown")
  .ui.dropdown
```
`ViewModel.find('dropdown', (vm)-> vm.type() is 'metro')`
correctly returns the 1st dropdown vm.
`ViewModel.findOne('signUp').children('dropdown', (vm)-> vm.type() is 'metro')`
returns arr of two VMs...

**Comment by ManuelDeLeon** [comment]
Pick up v4.0.13
