### ISSUE TITLE
Uncaught ReferenceError: title is not defined

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#232]
Hi @ManuelDeLeon , I'm trying to use the onUrl feature on a multi-step form (just in page hide/show switching). The browser back/next button sometimes works, but when I notice the titled error in console, the back/next button would stop working (page state no longer updates).

The error points to your source code:
```  
history.replaceState = (state) ->
    if typeof history.onstatechange is 'function'
      history.onstatechange state, title, url
```

I tried to add 'title' property in my layout template but still has the same error. What is that title? Where should I define it?

**Comment by ManuelDeLeon** [comment]
I don't know how I've never run into this. Try running ViewModel from local/packages and change `viewmodel-onUrl.coffee`:

From:
```coffee
history.replaceState = (state) ->
```
To:
```coffee
history.replaceState = (state, title, url) ->
```

**Comment by daveeel** [comment]
Tried the suggestion and the error is gone.

However the back/next browser button issue seems not related to the 'title' error. I noticed that the URL encoding string does change with the back/next browser history, only the VM properties don't get changed. Sometimes I reload the browser, it works again, then after a few back and forth test, the VM props won't change again.

**Comment by daveeel** [comment]
Originally I was using onUrl on several levels of components (controls). Now I am restricting the use of onUrl only at the top level template, then it works as expected. So probably the question is whether onUrl is designed to work only at one level? 

Should the following structure be expected to work ?

```
template(name="Top")
  +myInputComponent ref='countryInput' options=countryList
  +myInputComponent ref='districtInput' options=districtList
```
e.g. the `myInputComponent` has mixin props say `input`. The original intention is to also have
```
onUrl: ['input']
```
Only removing component level onUrl, the onUrl in Top could work predictively.

**Comment by ManuelDeLeon** [comment]
It may be a reactivity problem. I don't remember exactly but I had a timing issue using onUrl. I think it was because the data fetched at the template level wasn't ready immediately after using the back/forward button.

**Comment by daveeel** [comment]
I'm only trying to save the input from the forms in the steps, as well as a
prop called "step" at top level.

**Comment by ManuelDeLeon** [comment]
In theory onUrl should work at any level. Please make a repro.

**Comment by daveeel** [comment]
That might take some time for me to remove the complexities to make the
repro since I tried onUrl at quite late stage of my project. Please keep
this open. I'll come back with the repro ASAP.

**Comment by ManuelDeLeon** [comment]
Okay. onUrl works by matching the template's location on the page with the location stored in the url blob. It can be that the path to an inner template isn't "right" by the time it pulls the data from the url (eventually consistent).

**Comment by ManuelDeLeon** [comment]
I'll leave it open for you.

**Comment by ManuelDeLeon** [comment]
Humor me and change `viewmodel.coffee`

from
```coffee
  vmHash: ->
    viewmodel = this
```

to
```coffee
  vmHash: ->
    viewmodel = this
    return viewmodel.vmHashFixed() if viewmodel.vmHashFixed
```

and then give the view models with onUrl a unique `vmHashFixed`.

**Comment by daveeel** [comment]
Does that mean I have to add vmHashFixed to all VMs? Somehow like vmTag? Speaking of vmTag, is it feasible, it's better VM takes care of it internally, like generate a random but unique tag, as it adds no value to a developers core logic.

**Comment by ManuelDeLeon** [comment]
Not every vm, just the one you use onUrl.

It can't be se automatically because you can't know the id when the
template is created. The best you can do is create an ID based on the
template path.

**Comment by ManuelDeLeon** [comment]
Did you try adding vmHashFixed?

**Comment by daveeel** [comment]
I've changed a bit how to handle entered info (something like auto guest login and save to DB). So I'm a bit away from this issue.

Anyway, I'll give vmHashFixed a try and report back today.

**Comment by daveeel** [comment]
Just tried adding vmHashFixed. Seems like the situation is much better, but there are exceptions.

I have a generic component(control) called `dropdownSelect` it has `onUrl = ['input']`. I use the component like:

```
    .form-group
      +dropdownSelect ref='occupationInput' options=occupations vmHashFixed='occ' vmTag='driverOccupation' inputReminder='Occupation is required' defaultText='Occupation' dataReady=dataReady searchMode=true
    .form-group
      +dropdownSelect ref='districtInput' options=districts vmHashFixed='dist' vmTag='driverDistrict' inputReminder='Residential district is required' defaultText='Residential District' dataReady=dataReady
    // ... other form-groups ...
```

Somehow one of the selection value of a field never got saved onUrl. The value is just a string like others. Probably the use of component complicates the issue. When I can isolate the issue with a repro, shall try to open a new issue.

I think it's fine to close this issue after fixing what the original question is about: i.e. 
```
history.replaceState = (state, title, url) ->
```

**Comment by daveeel** [comment]
Not sure if it's better to make PR for these kind of misc fix? Let me know :)

**Comment by ManuelDeLeon** [comment]
Alright, 4.1.1 has `history.replaceState = (state, title, url) ->`
