### ISSUE TITLE
Aurelia has four modes of binding - features request

### ISSUE THREAD

**Issue by comerc** [ManuelDeLeon/viewmodel#233]
- twoWay
- oneWay
- bind - it is depend by context: twoWay in input elements and oneWay in other cases
- oneTime - for the best performance

**Comment by ManuelDeLeon** [comment]
That's a whole bunch of complexity for little to no added value to the
programmer. If you need one of those bindings (unlikely) you can add a
custom one.

It's like having a bunch of types for numbers. In theory it makes sense, in
practice it's just more stuff for a developer to know, for little to no
value (in practice).

**Comment by comerc** [comment]
OK, [React declared two-way data binding mixin as deprecated](https://facebook.github.io/react/docs/two-way-binding-helpers.html) :)

**Comment by ManuelDeLeon** [comment]
The React community in general prefers ceremonies over shortcuts (which is what bindings are). I don't see any value of boilerplate code when you can declare what you want instead.

**Comment by comerc** [comment]
Same here, I'm your man! I love CoffeeScript, Jade, Stylus and Sass. Also I very loved AutoForm, but the love has gone. :)
