### ISSUE TITLE
How to get templateInstance inside onRendered - undocumented feature

### ISSUE THREAD

**Issue by comerc** [ManuelDeLeon/viewmodel#237]
https://viewmodel.org/docs/viewmodels#templateinstance
```
Template.editContact.viewmodel({
  onRendered: function(t) {
    console.log('t', t);
  }
});
```

**Comment by ManuelDeLeon** [comment]
Added it to the docs but it will appear the next time I update the site. I use mupx to deploy and sometimes it works smoothly but other times it fails left and right and it's a hassle to get the site up and running again (like last night).
