### ISSUE TITLE
[question]How to use chart.js with viewmodel?

### ISSUE THREAD

**Issue by wuxianliang** [ManuelDeLeon/viewmodel#24]
Dear @ManuelDeLeon 
I want to use chart.js with viewmodel, so I have to find a place to write 
```
var ctx = document.getElementById("myChart").getContext("2d");
var myNewChart = new Chart(ctx).PolarArea(data);
```
we ever wrote in 
```
template.canvas.rendered = ->
```
so how to find an equivalent pattern within viewmodel? Thank you very much!

**Comment by ManuelDeLeon** [comment]
If I understand the problem correctly, you want to access "myNewChart" from other functions in your ViewModel. If that's the case you have to set the chart after creating the view model:

```
Template.canvas.rendered = ->
  vm = new ViewModel(
    chart: {}
    # other properties and functions that use chart
  ).bind @
  ctx = document.getElementById("myChart").getContext("2d")
  vm.chart( new Chart(ctx).PolarArea(data) )
```

**Comment by wuxianliang** [comment]
I am sorry I did not make it clear.
In meteor, we have the pattern 
UI<-----------ViewModel<------------Data

but when I am using chart.js with meteor
UI<-----------Template.chart.rendered<-------------Data

I want to find a way to manipulate data in ViewModel then pass them to charts on the template.

Something like

```
Template.canvas.rendered = ->
  vm = new ViewModel(
    data: {
    # for using chart
    }
    
  ).bind @
  ctx = document.getElementById("myChart").getContext("2d")
  chart =  new Chart(ctx).PolarArea(vm.data) 
```

**Comment by ManuelDeLeon** [comment]
Is the data in Mongo? If so you have to put it in a function to make it reactive:
```
new ViewModel
  data: -> DataCollection.find()
```
and then
```
chart =  new Chart(ctx).PolarArea(vm.data())
```

btw, I'm still guessing here...

**Comment by wuxianliang** [comment]
Yes, that is what I mean.I missed the () after vm.data Thank you!
