### ISSUE TITLE
value binding isnt updated if input is modified externally

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#241]
E.g. when I send `$('input').val(132)` through console, input value is updated, but value binding holds old value.

**Comment by ManuelDeLeon** [comment]
That's because you're not triggering the change event (which ViewModel is
listening to)

**Comment by avalanche1** [comment]
I see. I will do `$('input').val(132).change()` then.

**Comment by compgumby** [comment]
Hello... I keep trying to unsubscribe from this thread, but it's never taking.  In fact, it says "You're ignoring this thread."  And yet - emails keep coming.  What else do I need to do?

**Comment by ManuelDeLeon** [comment]
No clue. That's a GitHub issue. Either way this thread is pretty much dead...
