### ISSUE TITLE
Enforcing binding type?

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#244]
Hi @ManuelDeLeon, say I have a prop `duration: 0`. By binding to an input field it will be converted to String `"0"`. Apart from autorun, is there any hook that I could make some conversion ?

**Comment by ManuelDeLeon** [comment]
You could try using the change binding but it will be the same as using an autorun.

I'm working double time on validations. Soon you'll be able to do:

```js
Template.Example.viewmodel({
  duration: ViewModel.property.integer.convert
})
```

And also:

```js
Template.Example.viewmodel({
  duration: ViewModel.property.integer
    .convertIn( value => transformValueBeforeUpdatingTheProperty(value) )
    .convertOut( value => transformValueBeforeReturningIt(value) )
})
```

**Comment by hluz** [comment]
> I'm working double time on validations

I have been on the edge of my seat waiting for it :-) Even halted my attempts to reach an acceptable pattern to use SimpleSchema in the view layer...

**Comment by ManuelDeLeon** [comment]
Added on v4.1.0 

https://viewmodel.org/docs/viewmodels#validation
