### ISSUE TITLE
won't install in Meteor.1.2.1 anymore

### ISSUE THREAD

**Issue by HatemJerbi** [ManuelDeLeon/viewmodel#245]
While selecting package versions:
error: Conflict: Constraint ecmascript@0.4.2 is not satisfied by ecmascript 0.1.6.
Constraints on package "ecmascript":
* ecmascript@=0.1.6 <- top level
* ecmascript@0.1.6 <- random 1.0.5 <- accounts-base 1.2.2 <- accounts-password 1.1.4
* ecmascript@0.1.6 <- random 1.0.5 <- accounts-password 1.1.4
* ecmascript@0.1.6 <- ddp-server 1.2.2 <- ddp 1.2.2 <- accounts-base 1.2.2 <- accounts-password 1.1.4
* ecmascript@0.1.6 <- ddp-server 1.2.2 <- ddp 1.2.2 <- accounts-password 1.1.4
* ecmascript@0.1.6 <- templating 1.1.5 <- blaze-html-templates 1.0.1
* ecmascript@0.1.5 <- caching-html-compiler 1.0.2 <- templating 1.1.5 <- blaze-html-templates 1.0.1
* ecmascript@0.1.3 <- caching-compiler 1.0.0 <- caching-html-compiler 1.0.2 <- templating 1.1.5 <- blaze-html-templates 1.0.1
* ecmascript@0.1.3 <- caching-compiler 1.0.0 <- coffeescript 1.0.11 <- manuel:viewmodel 4.1.2
* ecmascript@0.1.3 <- templating-tools 1.0.0 <- caching-html-compiler 1.0.2 <- templating 1.1.5 <- blaze-html-templates 1.0.1
* ecmascript@0.1.3 <- templating-tools 1.0.0 <- templating 1.1.5 <- blaze-html-templates 1.0.1
* ecmascript@0.1.6 <- reactive-dict 1.1.3 <- iron:controller 1.0.12 <- iron:router 1.0.12
* ecmascript@0.1.6 <- reactive-dict 1.1.3 <- manuel:viewmodel 4.1.2
* ecmascript@0.1.6 <- neo:meteor-ubold-themeforest 0.0.1
* ecmascript@0.1.6 <- neo:awspackage 0.0.1
* ecmascript@0.1.6 <- coffeescript 1.0.11 <- manuel:reactivearray 1.0.5 <- manuel:viewmodel 4.1.2
* ecmascript@0.1.6 <- coffeescript 1.0.11 <- manuel:viewmodel 4.1.2
* ecmascript@0.1.6 <- neo:aws-iot-device-sdk 0.0.1
* ecmascript@0.1.6 <- accounts-password 1.1.4
* ecmascript@0.1.6 <- accounts-base 1.2.2 <- accounts-password 1.1.4
* ecmascript@0.4.2 <- manuel:viewmodel 4.1.2

**Comment by HatemJerbi** [comment]
why do you specify ecmascript version in package.js (ecmascript@0.4.2)?

**Comment by ManuelDeLeon** [comment]
I honestly don't remember, I think Meteor requires the numbers. I'll lower
it to 1.6

**Comment by HatemJerbi** [comment]
I have a lot of private meteor packages that work great without setting specific version to any of imported Meteor package.

**Comment by ManuelDeLeon** [comment]
Fixed on 4.1.3
