### ISSUE TITLE
viewmodel 4.1.3 added with success in Meteor 1.2.1 but!!!! 

### ISSUE THREAD

**Issue by HatemJerbi** [ManuelDeLeon/viewmodel#247]
/Users/MacBook/NeoConcept/CityOne.Caap.Pita/.meteor/local/build/programs/server/packages/manuel_viewmodel.js:71
W20160507-05:00:13.271(1)? (STDERR) class Property {                                                              
W20160507-05:00:13.271(1)? (STDERR) ^^^^^
W20160507-05:00:13.273(1)? (STDERR) SyntaxError: Unexpected reserved word
W20160507-05:00:13.273(1)? (STDERR)     at /Users/MacBook/NeoConcept/CityOne.Caap.Pita/.meteor/local/build/programs/server/boot.js:241:30
W20160507-05:00:13.273(1)? (STDERR)     at Array.forEach (native)
W20160507-05:00:13.273(1)? (STDERR)     at Function._.each._.forEach (/Users/MacBook/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160507-05:00:13.273(1)? (STDERR)     at /Users/MacBook/NeoConcept/CityOne.Caap.Pita/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8

Manuel: I can confirm when you omit the specific version for the ecmascript all go ok.  I have tested it, coping your package as local package and omitting the version in ecmascript fix the problem.

**Comment by HatemJerbi** [comment]
Manuel: when i use VM 4.1.3 as local package all seems ok even with ecmascript specific version but when install it from atmosphere i get the error mentioned in previous comment. i don't understand !!!!

**Comment by dnish** [comment]
@ManuelDeLeon Having the same issue after upgrading to the latest version. My app was created with Meteor 1.1, then upgraded to 1.2 and doesn't use ES6 syntax

**Comment by ManuelDeLeon** [comment]
How do I create a 1.2.1 project? (now that I have 1.3)

**Comment by dnish** [comment]
Didn't try it yet, but maybe it works if you change the <code>release</code> file to <code>METEOR@1.2.1</code> and then do a <code>meteor update --packages-only</code>

**Comment by ManuelDeLeon** [comment]
Someone make a repro...
