### ISSUE TITLE
Throttle issue - quickly deleted text is restored

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#249]
In https://viewmodel.org/docs/bindings#throttle example input: type smth and quickly press ctrl+backspace - you will have you deleted text restored.
This is much more obvious when you set throttle to 1000 and longer.

**Comment by ManuelDeLeon** [comment]
Make a repro, I can't reproduce it.

**Comment by fvpDev** [comment]
The example above works for me; If you type and ctrl+backspace all within the example 400 milliseconds the text gets deleted within the input, and then once the 400 is up, what was typed appears in the input box and label again. Easier to reproduce if typing something quick like `asdf`

**Comment by ManuelDeLeon** [comment]
```
// TODO: Insert lame excuse for why it took so long to fix.
```

Pick up v4.1.7
