### ISSUE TITLE
[Question] Nested objects

### ISSUE THREAD

**Issue by Shalimov** [ManuelDeLeon/viewmodel#25]
Whenever I try define smth like this: 
         return new ViewModel({ email: { value: '', isValid: false } });
I get tracker an error:
       "Exception from Tracker afterFlush function: undefined is not a function. TypeError: undefined is not a function"

Can I use nested objects for model definition?

**Comment by ManuelDeLeon** [comment]
You can but then you're storing an object inside email. Its properties won't be reactive. In your case you'll be able to call:
```
viewmodel.email() // { value: '', isValid: false }

viewmodel.email().isValid 
// returns false. 
// Notice that it's not a function, just a property of the email object.
```

**Comment by wuxianliang** [comment]
Dear @ManuelDeLeon 
Is there a way to use https://atmospherejs.com/mrt/reactive-object or something like that with viewmodel for the very reactivity? I have a bold try and failed.

**Comment by ManuelDeLeon** [comment]
You can use it but not for 2 way data binding since reactive object uses ECMAScript 5 getters and setters, while ViewModel uses a more conservative (old browser compatible) approach (functions).

See: http://meteorpad.com/pad/YBCnHouejznyDJRGs/Leaderboard

**Comment by wuxianliang** [comment]
Thank you! @ManuelDeLeon

**Comment by Shalimov** [comment]
Are you planning to provide nested objects for next versions of ViewModel?

**Comment by ManuelDeLeon** [comment]
yeah, that's coming. The way it will work is that everything that's not a function will be reactified.

**Comment by Shalimov** [comment]
It's cool, thx for your responses.

**Comment by zimt28** [comment]
Any updates on nested objects?

**Comment by ManuelDeLeon** [comment]
Not yet. Been busy with other stuff =(

**Comment by ManuelDeLeon** [comment]
(scheduled for v2)
