### ISSUE TITLE
Cannot use 4.1.0 with Meteor 1.1

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#250]
4.1.0 and higher require ecmascript which for some reason doesnt want to add to my config: 
![image](https://cloud.githubusercontent.com/assets/10534563/15093028/75e856b2-1483-11e6-9d36-c64ec20c1be0.png)
Is it absolutely necessary for viewmodel package?

**Comment by ManuelDeLeon** [comment]
I'd rather have you try to solve the problem on your end and share your
finding. I mean, it should work. It allows me to share code with the  react
version.
