### ISSUE TITLE
Add note to .depend and changed in docs.

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#251]
Manuel, could add an explicit note to docs that .depend and .changed methods are only available on vm properties. It took me some time to figure it out... Now I understand that object methods cannot have methods of their own , but why learn that the hard way? (today I have only 1 year of experience with programming)

**Comment by fvpDev** [comment]
If you want to have object methods you could have the method of a parent viewmodel to reference another vm instance and access its properties' methods; this way, methods and properties stay as part of the encapsulations that are the viewmodels.

**Comment by ManuelDeLeon** [comment]
The docs do say depend and changed are part of vm properties. I find it really odd to use them on a function. depend/changed... what exactly, the return value? What if it doesn't return anything? One of the dependencies used inside the function? which? It just doesn't make sense.

**Comment by avalanche1** [comment]
bah, stumbled in this again! Maybe throw an error when trying to call a property method on a function?
