### ISSUE TITLE
arrays declared with ViewModel.property are not converted to reactive arrays 

### ISSUE THREAD

**Issue by HatemJerbi** [ManuelDeLeon/viewmodel#252]
Example:
selectedRoles: ViewModel.property.array
		.default(['CaapUser'])
		.invalidMessage("a least one Role must be selected")
		.validate((value)=>{
			if (value.length===0)
				return false;
			else
				return true;
		}),

selectedRoles is not converted to reactive array

**Comment by ManuelDeLeon** [comment]
Fixed on 4.1.4
