### ISSUE TITLE
Prevent event bubbling ?

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#254]
Hi @ManuelDeLeon , is there a simple way to prevent the click on span to bubble up to div?

```jade
    div($b="click:clickMe('DIV')") DIV
      span($b="click:clickMe('SPAN')") SPAN
```
```
    clickMe: (p)->
      console.log "clickMe: #{p}"
```

**Comment by ManuelDeLeon** [comment]
See http://api.jquery.com/event.stopPropagation/

**Comment by daveeel** [comment]
not as clean as I expect. thanks anyway :)

**Comment by ManuelDeLeon** [comment]
If you're doing that a lot then create a "noBubbleClick" custom binding.
