### ISSUE TITLE
Errors when accessing properties _of properties_ via bindings

### ISSUE THREAD

**Issue by arggh** [ManuelDeLeon/viewmodel#258]
Let's say I have an object `Dog`, which has a property `stray`, which can be true or false.

I'd like to do this:

```
<label {{b "class: { strayColor: dog.stray }"}}>Stray dog label</label>
```
which in some scenarios produces this error:

`viewmodel.coffee:588 Can't access 'stray' of 'undefined'. This is for template 'dog_tmpl'.`

If I replace the VM-bind with this, the error disappears.

```
<label class="{{#if dog.stray}}strayColor{{/if}}">Stray dog label</label>
```

This is of course due to Blaze's nature of forgiving checking up on anything that's actually missing, but it would be nice to have the same behaviour in ViewModel (at least I think so).

Now, if I want to use the dog's property `stray` in the condition of a VM binding, I have to create a helper, something like this:

```
  isStray() {
    return this.dog() && this.dog().stray;
  }
```

which is annoying. Any ideas?

**Comment by ManuelDeLeon** [comment]
I don't feel strongly about either way but right now I lean towards throwing the undefined error because it's easier for debugging.

Maybe you need CoffeeScript =p
