### ISSUE TITLE
Subscriptions inside onCreated don't unsubscribe automatically after viewmodel is destroyed

### ISSUE THREAD

**Issue by tomyo** [ManuelDeLeon/viewmodel#270]
When clicking to somewhere else in the site (flowrouter), subscription inside onCreated method don't unsubscribe. If I use autorun(), works as expected (unsubscribes automatically after viewmodel is destroyed). Looks like this shouldn't happen.

```
onCreated: ->
    Meteor.subscribe 'somethings'
```
```
autorun: ->
    Meteor.subscribe 'somethings'
```

**Comment by ManuelDeLeon** [comment]
I don't think I can do much since I don't have a mechanism to know when/if you subscribe to a publication.

**Comment by tomyo** [comment]
I'm using `babrahams:constellation`, gives you a left panel where you can view the local collections and subscriptions.

**Comment by ManuelDeLeon** [comment]
I'll implement it if you help me out. The task for you to is "given a
function, how do you know the subscriptions it makes (if any) when you run
the function?"

You give me that and I'll use it when the template is created and
unsubscribe from the publications onDestroyed.

**Comment by tomyo** [comment]
Ok, I couldn't find that (nice question though), but I found [this](http://stackoverflow.com/questions/25995399/iron-router-meteor-auto-unsubscribe):
> If you call Meteor.subscribe within a reactive computation, for example using Deps.autorun, the subscription will automatically be cancelled when the computation is invalidated or stopped.

I don't know if that helps. In the mean while, how would you recommend to handle subscriptions with viewmodels (when using the pattern of subscribing in the template layer)?
Thanks.

**Comment by ManuelDeLeon** [comment]
Just unsubscribe from the publication onDestroyed.

**Comment by tomyo** [comment]
The solution was to use `this.templateInstance.subscribe`, wich unsubscribes automatically when the template is destroyed. This also gives you the `subscriptionsReady` helper, available in the template as `Template.subscriptionsReady` to check if all subscriptions are ready. Cool.

**Comment by ManuelDeLeon** [comment]
I forgot about that one. Thanks.

**Comment by tomyo** [comment]
Thank you for ViewModel, the reason why I keep using blaze. ^_^

**Comment by ManuelDeLeon** [comment]
You should try the [React version](https://viewmodel.org/) for your next project, it works with or without Meteor =)
