### ISSUE TITLE
Templates dynamically created with Blaze API are not behave like viewmodels

### ISSUE THREAD

**Issue by RevelsGit** [ManuelDeLeon/viewmodel#272]
That said, templates created with Blaze.render, Blaze.renderWithData are not initialized as viewmodels. Is this intended behavior? Is there some way to initialize them as viewmodels by hand?
Simple reproduction: https://github.com/RevelsGit/viewmodel-blaze-issue-1

**Comment by ManuelDeLeon** [comment]
You're replacing your contents with the render. In the following example the child template is rendered via renderWithData and it uses the child view model:

```html
<template name="parent">
  <div class="container">
  </div>
</template>

<template name="child">
  {{text}}
  <br><button type="button" {{b "click: sayHello"}} >Say Hello</button>
</template>
```

```js
Template.parent.viewmodel({
  onRendered() {
    Blaze.renderWithData(Template.child, {
      text: 'Hello World!'
    }, this.templateInstance.$('.container')[0]);
  }
});

Template.child.viewmodel({
  sayHello() {
    console.log("Hello");
  }
});
```

**Comment by RevelsGit** [comment]
The problem was that I haven't passed parentView to render. Because of that viewmodels were created but not associated with parent template.
