### ISSUE TITLE
Passing data as helper issue

### ISSUE THREAD

**Issue by RevelsGit** [ManuelDeLeon/viewmodel#273]
The props passed with undefined value are created by viewmodel. This is really annoying sometimes if we need to check if prop exists, for example.
Take a look at the following:
```js
<template name="tpl">
  {{> child (childArgs)}}
</template>

Template.tpl.viewmodel({
  childArgs() {
    return {
      someCallbackFunction: undefined
    };
  }
});
```
Then in the child template we need to check if it has `someCallbackFunction` property for some reason:
```js
Template.child.viewmodel({
  onClick() {
    if (this.someCallbackFunction) this.someCallbackFunction();
  };
});
```
This is pretty annoying sometimes. Say that `someCallbackFunction` is passed as prop to `tpl` as well.
To get away with this we need to do some wacky stuff:
```js
Template.tpl.viewmodel({
  childArgs() {
    return {
      text: 'hello world',
      ...(() => this.someCallbackFunction ? { someCallbackFunction: this.someCallbackFunction() } : null)()
    }
  }
});
```

**Comment by ManuelDeLeon** [comment]
I don't understand the problem, you are passing a property with the value of undefined so of course the child will have a property with undefined as its content.

It's the same as if you write `var a = { b: undefined }` and get true with `a.hasOwnProperty("b")`. `a` has the property `b` which just happens to be undefined.

And if you don't know if an object (or view model) has a property/function then of course you have to check if it exists before using it.

**Comment by RevelsGit** [comment]
What's the point of creating a property with undefined value anyway? But okay, I guess it's more like Blaze design problem not viewmodel.

**Comment by ManuelDeLeon** [comment]
> What's the point of creating a property with undefined value anyway?

I'm confused, you're the one creating an object that has a property with undefined. So Blaze is doing exactly what you're telling it to do: "give the child an object with property X that has a value of undefined"
