### ISSUE TITLE
Binding input value to shared property throws Error

### ISSUE THREAD

**Issue by arggh** [ManuelDeLeon/viewmodel#278]
Having a simple input binding made to a shared property throws this error:

`viewmodel-parseBind.coffee:17 Uncaught TypeError: Cannot set property 'nextVal' of undefinedvalueEvent @ viewmodel-parseBind.coffee:17(anonymous function) @ manuel_viewmodel.js?hash=49c6756…:608dispatch @ jquery.js:5201elemData.handle @ jquery.js:5009`

Reproduction here:

https://github.com/arggh/vm-throttle-input2

**Comment by arggh** [comment]
@ManuelDeLeon Do you have any plans about finishing this throttle-of-a-mess issue in the near-future?

I was trying to interpret ViewModel source code and help out, but with zero Coffeescript experience it is quite daunting to comprehend what's happening under the hood, and thought I'd ask before I waste more time fiddling.

**Comment by ManuelDeLeon** [comment]
Sorry for the delay. Pick up v6.1.5
