### ISSUE TITLE
After pushing a new option to the bounded select, all other selects of this view model instance gets selected value if they doesn't have

### ISSUE THREAD

**Issue by mflafl** [ManuelDeLeon/viewmodel#28]
Easy to reproduce:
1) Create view model without data (no fromJS call) : So all the selects rendered just empty, with no selection.
Meteor.Cattle.getViewModel = function(animal) {
    var vm = new ViewModel({
        pen_name: function() {
            return Session.get('activePen');
        },
        pens: Meteor.getPensSelectValues(),
        herd_id: '',
        rfid: '',
        animal_type: 'cow',
        culled: false,
        tag_name: '',
        birthdate: '',
        calving_ability: '',
        twin_status: '',
        birth_data: '',
        sex: 'female',
        timestamp: '',
        animalTypes: Meteor.configuration.animalTypes,
        calvingAbilityTypes: Meteor.configuration.calvingAbilityTypes,
        twinStatusTypes: Meteor.configuration.twinStatusTypes,
        sexTypes: Meteor.configuration.sexTypes,
        birthDataTypes: Meteor.configuration.birthDataTypes
    });
    if (animal) {
        vm.fromJS(animal);
    }
    return vm;
}

<select class="form-control" data-bind='options: animalTypes, value: animal_type'></select>

2) Add a new value to the options array in some event handler:
template.trackSession.animalTypes().push(newType);

3) All the other bounded selects of this view model gets a selected value, first item of the appropriate options array.

**Comment by ManuelDeLeon** [comment]
Make a repro
