### ISSUE TITLE
Bug wit raw() ?

### ISSUE THREAD

**Issue by frankapimenta** [ManuelDeLeon/viewmodel#281]
when i call raw on viewmodel....

rawAll.js:18 Uncaught TypeError: Class.getFieldsNames is not a function(…)rawAll @ rawAll.js:18raw @ raw.js:13(anonymous function) @ VM743:1

**Comment by ManuelDeLeon** [comment]
I have no clue what `raw()` is.

**Comment by frankapimenta** [comment]
this is not related to view model. something else was being added to it...

**Comment by ManuelDeLeon** [comment]
cool
