### ISSUE TITLE
How to build a modal component with ViewModel

### ISSUE THREAD

**Issue by arggh** [ManuelDeLeon/viewmodel#284]
I've been using Semantic-UI in a project, but now would like to get rid of it entirely. This brings me to wonder, what would be the ideal ViewModel-way of building a dynamic and reusable modal- or a popup-component?

It's cumbersome enough using Blaze, and I'm having a hard time thinking of an elegant way to build such component with ViewModel and I'm not sure, if VM bring anything valuable to the table in this case?

Any guidance would be greatly appreciated!

**Comment by ManuelDeLeon** [comment]
Check out this thread https://viewmodel.org/help/MiqtTm4J5yKDMZGcK it might
give you an idea.

**Comment by arggh** [comment]
Thanks for the link.

I wonder, what if, instead of writing this same helper over and over again in all my ViewModels...

```
byRef(prop) {
    return () => this[prop];
}
```

...it could be part of every ViewModel out of the box?

Writing referencing functions to props being passed down the component chain, which is quite often if one tries to embrace the component oriented approach, sounds a lot like something ViewModel could alleviate in Blaze.

**Comment by arggh** [comment]
Though, I mostly have found myself passing down more complex stuff wrapped in objects anyway, not just VM props, like so:

```handlebars
{{> component componentArgs }}
```
```js
// VM
componentArgs() {
   return {
     someAttr: true,
     someRef: this.enabled,
     options: importedStuff,
     onChange() {
        ...
     }
}
```

How these scenarios should ideally be dealed with... now that was originally hard to find in both ViewModel & Blaze's docs.

**Comment by ManuelDeLeon** [comment]
I added https://viewmodel.org/docs/misc#usingcontrols

In the end I used `vmRef` instead of `byRef` because I didn't want people scratching their heads wondering where that `byRef` comes from. At least with `vmRef` there's a clue.

Thanks for the help.

**Comment by arggh** [comment]
That was fast 👍  I agree, vmRef is better.
