### ISSUE TITLE
event.stopPropagation() with ViewModel.signal

### ISSUE THREAD

**Issue by davidsavoie1** [ManuelDeLeon/viewmodel#287]
Hi Manuel!

I looked into the _signal_ ViewModel attribute to control keyboard keydown events and followed the _Pacman_ example you provided. Here's a code sample :
```
ViewModel.signal({
    keyboard: {
        keydown: {
            target: document,
            event: 'keydown',
        }
    }
});

Template.itemTpl.viewmodel({
    signal: 'keyboard',
    autorun() {
            const e = this.keydown();
            console.log(e);
            e.stopPropagation();
    }
}
```
It looks to me that `this.keydown()` returns the `event` object, as I can see in the console, but I don't seem to be able to use `e.stopPropagation()`. I get the error _Exception in setTimeout callback: TypeError: e.stopPropagation is not a function_.

However, I need this functionality, because my application concerns nested items, so an `itemTpl` can be used inside other `itemTpl`, so triggering a low level template event would bubble up to as many ancestors the template has. Do you know why `stopPropagation()` doesn't seem to work?

Thanks a lot for your excellente work!

**Comment by ManuelDeLeon** [comment]
You're calling `this.keydown()` from an autorun which means the code inside will run as soon as the template is loaded. At that time no key has been pressed so `e` is an empty object. Best way to deal with it inside an autorun is by ignoring the first time it runs:

```js
  autorun(c) {
    const e = this.keydown();
    if (c.firstRun) return;
    console.log(e);
    e.stopPropagation();
  },
```

**Comment by davidsavoie1** [comment]
Wow, thanks! I wouldn't have guessed that! It does work as intended.

**Comment by ManuelDeLeon** [comment]
Yeah, Tracker needs to run a block of code at least once to figure out the dependencies. After that it will re-run the block whenever a dependency changes and thus recompute new dependencies.
