### ISSUE TITLE
Problem with helpers using references being called from template (Blaze)

### ISSUE THREAD

**Issue by arggh** [ManuelDeLeon/viewmodel#288]
When a helper uses references as described in the [Controls section of docs](https://viewmodel.org/docs/misc#controls), this gets thrown:

```
Exception in template helper: TypeError: Cannot read property 'enabled' of undefined`
```

If I change the code so that the helper only gets called if I click a button (for example), it works fine.

Minimal reproduction:

```handlebars
<template name="parentTemplate">
  {{#if isEnabled}}
    ENABLED
  {{/if}}

  {{> childTemplate ref='childtemp' }}
</template>


<template name="childTemplate">
  <button {{b "toggle: enabled"}} type="button">toggle</button>
</template>
```

```js
Template.parentTemplate.viewmodel({
  isEnabled() {
    return this.childtemp.enabled();
  }
});
 
Template.childTemplate.viewmodel({
  enabled: false
});
```

Now, if I exchange that `{{#if isEnabled}}` into a div `<div {{b "if: isEnabled">...` it works.

Tested with Meteor 1.4.2.3.

**Comment by ManuelDeLeon** [comment]
There's no fix for it since the parent #if is invoked before the child is
created. You'd have to check for the existence of the reference or use the
if binding (which happens after the child is created).

**Comment by arggh** [comment]
Thanks for the clarification 👍
