### ISSUE TITLE
https://viewmodel.org not working

### ISSUE THREAD

**Issue by tomyo** [ManuelDeLeon/viewmodel#289]

**Comment by ManuelDeLeon** [comment]
I updated the deploy script and just ended up messing up the entire website.

**Comment by tomyo** [comment]
Haha, I thought something like that happened, but added the issue just in case. ^_^

**Comment by ManuelDeLeon** [comment]
Site is back up. I added the following section to Blaze: https://viewmodel.org/docs/misc#usingcontrols

Thanks for the heads up and sorry for the outage.
