### ISSUE TITLE
Error: Template.<templateName>.viewmodel is not a function

### ISSUE THREAD

**Issue by tomyo** [ManuelDeLeon/viewmodel#299]
Hi!, I'm trying to use ViewModel in a new project, but when calling the viewmodel, I get that error.  I'm starting with a fresh meteor@1.6, what am I missing? Thanks!

P.S I installed viewmodel with meteor add manuel:viewmodel

**Comment by ManuelDeLeon** [comment]
Please make a repro.

**Comment by tomyo** [comment]
I just did a meteor update, and found this:
```
The following top-level dependencies were not updated to the very latest version available:
 * manuel:viewmodel 0.2.4 (6.3.4 is available)
```

whaaaaat

**Comment by tomyo** [comment]
There you go: git@github.com:tomyo/puntoscava.git, thanks for looking it up

**Comment by ManuelDeLeon** [comment]
Just set the version of ViewModel to the latest in the packages file.

**Comment by tomyo** [comment]
OK, I did, then this appeared in server:

```
Errors prevented startup:                  
   
   While selecting package versions:
   error: Potentially incompatible change required to top-level dependency: coffeescript 1.12.7_3, was 2.0.2_1.
   Constraints on package "coffeescript":
   * coffeescript@1.0.6 <- manuel:viewmodel 6.3.4
   * coffeescript@1.0.4 <- manuel:reactivearray 1.0.6 <- manuel:viewmodel 6.3.4
   * coffeescript@1.0.6 <- manuel:viewmodel-debug 2.7.1 <- manuel:viewmodel 6.3.4
```

Then I removed coffeescript package, did a meteor update that returned this:
```
coffeescript           upgraded from 1.12.6_1 to 1.12.7_3
coffeescript-compiler  added, version 1.12.7_3
```

Then installed back coffeescript package, and now it works!

Seems the problem was installing coffeescript package before viewmodel, somehow..

Thanks!
