### ISSUE TITLE
Strange, possibly ViewModel related errors

### ISSUE THREAD

**Issue by arggh** [ManuelDeLeon/viewmodel#306]
Ever since I updated to Meteor 1.6.1.1, I've had these strange UI breakages. I posted about this in the [Meteor repository](https://github.com/meteor/meteor/issues/9926) as well, but I thought opening an issue here is a good idea, since the error might be related to ViewModel.

### Description

Currently only observed on Mac OS Safari (11.1), but I haven't yet properly tested other browsers or OS's.

The user interface would break in random places and at random times. There seems to be no logic to it.

For example, 1 out 20 times I would get this error in the console when reloading the page:

```
Exception in template helper::
TypeError: null is not an object (evaluating '(h=a.instance()).viewmodel')
```

which then proceeds to many errors like these:

```
Exception from Tracker afterFlush function:
Error: Can't select in removed DomRange
Exception from Tracker afterFlush function:
Error: Can't use $ on template instance with no DOM 
```

The component from where the error originates seems to change at random.

Sometimes the app works fine for 5 to 10 minutes, sometimes it breaks twice in a row in less than 30 seconds.

Breaking could mean any of the following symptoms:

- an element could just "vanish" from the DOM
- a button might get rendered without any labels or styles
- click handlers might not work

![screencapture](https://user-images.githubusercontent.com/17210302/40888809-751bf702-6765-11e8-88e4-c3bd193a3015.png)

Most errors I've investigated seem to be related to ViewModel trying to get a hold of the current template instance from Blaze when a component is created, but for some reason null is returned instead, thus breaking everything.

Do you @ManuelDeLeon have any idea what could be the cause? Some kind of race condition going on between ViewModel and Blaze?

The part of my app where this frequently happens is quite complex, having lots of nested components, dynamic templates and block templates.

Other, simpler parts don't seem to be impacted.

**Comment by ManuelDeLeon** [comment]
Did you try cloning Blaze and checking inside the instance() call?

**Comment by arggh** [comment]
This was caused by an async autorun function, which was loading new Blaze templates dynamically. Removing the autoruns fixed the issues.

Apparently, and not suprisisingly, Blaze cannot handle async autorun.

**Comment by arggh** [comment]
False conclusions in the previous post. I'll reopen this issue here as well.

It seems `dynamic-import` causes some timing issues with either Blaze or ViewModel. Loading new templates dynamically while Blaze is constructing large components trees is very prone to break.

**Comment by arggh** [comment]
There's also another Meteor user in the referenced Github issue who's reporting nearly the exact same issue with `dynamic-import` and Blaze, the difference being that he doesn't use ViewModel at all. So it's quite likely this issue doesn't have anything to do with ViewModel, but Blaze and `dynamic-import` being incompatible in some way.
