### ISSUE TITLE
onRendered doesn't get current template instance as argument

### ISSUE THREAD

**Issue by arggh** [ManuelDeLeon/viewmodel#308]
`onCreated` and `onDestroyed` receive the current template instance as argument, so stuff like this is convenient:

```
onCreated(instance) {
   instance.subscribe('docs');
}
```

Is there a reason, why `onRendered` doesn't receive the template instance as argument? In Blaze it's bound as `this` in all three life cycle functions, so it would make sense to have a similar behavior across all of them in ViewModel as well?

**Comment by ManuelDeLeon** [comment]
Gonna need a repro. The following works:

```js
Template.body.viewmodel({
  onRendered(instance) {
    console.log(instance);
  }
});
```

**Comment by arggh** [comment]
I have no idea what happened then. Probably some silly human error. I just tried this in a random component and indeed it works like you said. Sorry for the trouble, closing.
