### ISSUE TITLE
Scope for "Each in..." not being passed to function

### ISSUE THREAD

**Issue by jamesgibson14** [ManuelDeLeon/viewmodel#309]
`{{#each item in items}}
  li {{ b 'click: doSomething(item)'}}>text here li
{{/each}}
`
`doSomething`, does run but item is "undefined". If you go back to just `{{#each items}} ... doSomething(this)`  it works as expected.

**Comment by arggh** [comment]
This is a known and documented limitation of ViewModel.

**Comment by ManuelDeLeon** [comment]
You could combine `#each` with `#with` but you'd still need `this`. 

```handlebars
  {{#each item in items}}
    {{#with item}}
      <button {{b "click: doSomething(this)"}} ></button>
    {{/with}}
  {{/each}}
```

It's still an option tho.

**Comment by jamesgibson14** [comment]
Thanks I didn't realize it was already documented. I didn't see it anywhere, which is why I added this.
