### ISSUE TITLE
using soop with viewmodel

### ISSUE THREAD

**Issue by miguelalarcos** [ManuelDeLeon/viewmodel#31]
Hi, first of all let me give you the thanks for this amazing package.

I've been thinking about the integration of my package [```soop```](https://github.com/miguelalarcos/soop) with yours.

For example, given:

```coffee
Template.loginBox.rendered = ->
  new ViewModel(
    first: ''
    last: ''
    greeting: -> "Hello #{@first()} #{@last()}"
    canEnter: -> !!@first() and !!@last()
    showError: false
    errorText: ->
      return '' if @canEnter() or not @showError()
      "Please enter your first and last name"
  ).bind @
```

It would be something like:

```coffee
class Client extends soop.Base
  @collection: clientCollection
  @schema:
    first:
      type: String
    second:
      type: String

  greeting: -> "Hello #{@first} #{@last}"

Template.loginBox.rendered = ->
  new ViewModel(
    model: new Client
      first: ''
      second: ''

    canEnter: -> !!@model.first and !!@model.last
    showError: false
    errorText: ->
      return '' if @canEnter() or not @showError()
      "Please enter your first and last name"
  ).bind @
```

So we separate at all the view and the model. What do you think about this? I will appreciate your answer. Thanks for your attention.

**Comment by ManuelDeLeon** [comment]
That sounds good in theory but in practice you end up with a bunch of properties bound to the UI which are not part of "the model". In those cases you'll have to face the question "is this part of my model or not?".

I think it's better to skip the question altogether and think of it in terms of "the model of the view". What model represents my view? (aka the "viewmodel"). I know, horrible name games... but what do you expect of a pattern coming from Microsoft?

To me, the Model part of MVVM refers to the data model (what's on the DB).

btw, in the next few days I'll release a new version of ViewModel where you can define the viewmodels this way:

```
Template.loginBox.viewmodel
  first: ''
  last: ''
  greeting: -> "Hello #{@first()} #{@last()}"
  canEnter: -> !!@first() and !!@last()
  showError: false
  errorText: ->
    return '' if @canEnter() or not @showError()
    "Please enter your first and last name"
```

It will take care of adding the right code to the right template events.

**Comment by miguelalarcos** [comment]
ok :)
thanks for the answer.
