### ISSUE TITLE
Meteor noob - added this package - viewmodel -> Uncaught type error

### ISSUE THREAD

**Issue by compgumby** [ManuelDeLeon/viewmodel#32]
Full disclosure - using the Windows version of Meteor.

In my .js file, I do this:

Template.masterLists.viewmodel(
    'masterLists',
    {
        lists: function () {
            return TestLists.find({}, {sort: {list: 1}});
        }
    },
    'lists'
);

In the console, I get this:
 Uncaught TypeError: undefined is not a function  - with Template.masterLists.viewmodel highlighted.

I have added a couple of other packages to the project with no similar issues.  Did I add it wrong?  Is it the Windows distro?  Does the .js file have to be in a root directory?  This particular file is a few folders deep off the "client/templates" directory.  

Thanks for writing the package, and for any support you can offer. 

Best,
Mike

**Comment by ManuelDeLeon** [comment]
Get the latest Windows version: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

**Comment by compgumby** [comment]
That seems to have helped.  ;)  Thanks!
