### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by zimt28** [ManuelDeLeon/viewmodel#33]
I've just read the documentation and love it! I wish I had always used `viewmodel` .. 

Ok, look at this code:

```
Template.person.viewmodel
  events:
    'click #fancyButton': ->
      Template.instance().viewmodel.doSomething()
```
Having to use `Template.instance().viewmodel` here is ugly (just too long), so I'm wondering if the following is possible:

```
Template.person.viewmodel
  events:
    'click #fancyButton': (e, tmpl, vm) ->
      vm.doSomething()
```

**Comment by ManuelDeLeon** [comment]
The thing to remember is that adding events that way is a last resort kind of thing. It's what you would do when you have no way to put a bind in the markup. 

Implementing your suggestion would require monkey patching Meteor code. I'm not a fan of it for something so minor and, as mentioned before, something that should seldom happen.

The normal way of doing things is:
```
<template name="person">
  <button data-bind="click: doSomething">Do Something</button>
</template>

Template.person.viewmodel
  doSomething: ->
```

btw, you can also write the following right now:
```
Template.person.viewmodel
  blaze_events:
    'click #fancyButton': (e, t) ->
      t.viewmodel.doSomething()
```
(a minor improvement)

**Comment by zimt28** [comment]
I've just started converting my code to `viewmodel`, can say it has reduced my code by some hundred lines of code in about two hours. I actually opened this issue just at the beginning, but I didn't have to use events so far. So `t.viewmodel.doSomething()` should be nice enough :)

**Comment by ManuelDeLeon** [comment]
`it has reduced my code by some hundred lines of code in about two hours`
Oh man, you just made my day =)

People don't believe me when I tell them that you need a lot less code when you do things this way (with a view-model). They think "yeah, right, everyone says that..."
