### ISSUE TITLE
Select Inputs

### ISSUE THREAD

**Issue by zimt28** [ManuelDeLeon/viewmodel#36]
At the moment `options` for select input fields only accepts an array of values. It would be nice if we could also provide an array of objects, so that the visible option is different from its value.

```
[
  {
    option: 'Germany'
    value: 'de'
  }
  {
    option: 'France'
    value: 'fr'
  }
]
```

**Comment by ManuelDeLeon** [comment]
Yeah, this is in the roadmap. The way it will works is that you give it a collection of objects and you specify which property is going to be the value and which will be the display.

Something like:
```
    <select data-bind="options: availableCountries,
                       text: 'countryName',
                       value: selectedCountry"></select>
```

**Comment by ManuelDeLeon** [comment]
Check out the options documentation -> Object Array: http://viewmodel.meteor.com/#optionsBk

**Comment by ManuelDeLeon** [comment]
btw, that's with ViewModel version 1.6.1
