### ISSUE TITLE
[Question] Syntax

### ISSUE THREAD

**Issue by zimt28** [ManuelDeLeon/viewmodel#37]
Why does `viewmodel` use commas in `data-bind` to separate bindings instead of semicolons?
As an idea, what about allowing multiple arguments for bindings?
Like 
```
data-bind="if:selectedA, selectedB; click: doSomething, doSomethingElse; class: { selected: selectedA, selectedB }"
```
would only show the element if both values === true, and trigger both functions.

**Comment by zimt28** [comment]
And a second question, which has to do with https://github.com/ManuelDeLeon/viewmodel/issues/38. 
Is there a way to do something like the following things?
```
data-bind="class: { selected:  selection=1 }"
```
or 
```
data-bind="class: { selected: _selection(1) }"

template.viewmodel 
  selection: 0
  _selection: (val) ->
    val is @selection()
```

I don't think this exists, but it would be really helpful. The syntax is not so important here, it's more about the idea :)

**Comment by ManuelDeLeon** [comment]
About the commas, to be honest (for once), it's not going to change because it would require major rewrite of the parser. Then there's the ambiguity of it (is it going to be AND or OR?) In that particular case the solution is to allow functions to run: `data-bind="if: function() { return optionA() && optionB(); }"` I couldn't find it any uglier so don't wait for it. In the meantime just bind to one property and put your logic in the view model.

Regarding the second question, you can do that already. I'll reuse the example on #38 

html
```
<body>
  <div data-bind="click: selection(1), class: { selected: selected(1) }">One</div>
  <div data-bind="click: selection(2), class: { selected: selected(2) }">Two</div>
  Selected: <span data-bind="text: selection"></span>
</body>
```
coffee
```
Template.body.viewmodel
  selection: 0
  selected: (n) -> n is @selection()
```
css
```
.selected {
    color: red;
}
```

**Comment by zimt28** [comment]
I see, I didn't think about it. Allowing to pass functions looks bad, I agree. What do you think about this syntax?

```
<div data-bind="visible: and(true, false)">Not visible</div>
<div data-bind="visible: or(true, false)">Visible</div>
```

I've tried to write these helpers:
```
  and: ->
    result = _.find arguments, (property) ->
      not (property?() ? property)

    result isnt false

  or: ->
    !!_.find arguments, (property) ->
      !!(property?() ? property)
```

Code works, but only for `text` bindings, and only when I pass `true` and `false` values directly. Passing viewmodel properties doesn't work (`[Log] Error: ReferenceError: Can't find variable: x`).

**Comment by zimt28** [comment]
The more I think about it, the better I like this syntax. 

Back to a previous comment,
```
data-bind="class: { selected:  selection=1 }"
```
is ugly, while
```
data-bind="class: { selected:  is(selection, 1) }"
is clean.

```
  is: ->
    a = arguments[0]
    b = arguments[1]
    
    (a?() ? a) is (b?() ? b)
```
