### ISSUE TITLE
What's wrong with this binding?

### ISSUE THREAD

**Issue by zimt28** [ManuelDeLeon/viewmodel#38]
Hey there,

sorry for opening so many issues but I'm just trying to use `viewmodel` for everything :D

Code first:

```
<div data-bind="selected: selection" data-value="1"></div>
<div data-bind="selected: selection" data-value="2"></div>
<div data-bind="selected: selection" data-value="3"></div>
```
```

ViewModel.addBind 'selected', (p) ->
  p.element.bind 'click', ->
    property = p.vm[p.property]
    value = p.element.data 'value'

    if property() is value
      property ''
    else
      property value
```
```
[Log] Error: undefined is not a function (evaluating 'property()') (reporters.js, line 67)
```
What I want: I have three divs. One of them can be selected, it's also possible to select none. When I click an element, I want the `selection` property to be updated. I've looked at [this code from viewmodel.coffee](https://github.com/ManuelDeLeon/viewmodel/blob/master/viewmodel.coffee#L115) and think my code should work as well. What's wrong here?

**Comment by zimt28** [comment]
I just tried so many things that I forgot to add the property to my viewmodel. The issue was that I tried to use `value` here, which doesn't work. `data-value`  instead works great :)

**Comment by ManuelDeLeon** [comment]
You're making things harder than they need to be. Don't add another binding. Just do the following:
```
<body>
  <div data-bind="click: selection(1)">One</div>
  <div data-bind="click: selection(2)">Two</div>
  Selected: <span data-bind="text: selection"></span>
</body>

Template.body.viewmodel
  selection: 0
```

**Comment by zimt28** [comment]
Great to know this works, but in my situation I need to reset the selection when the user clicks it again.

**Comment by ManuelDeLeon** [comment]
Same deal:
```
Template.body.viewmodel
  selected: ''
  selection: (n) -> @selected( if n is @selected() then '' else n )
```

**Comment by zimt28** [comment]
Nice! So the hard thing for me will be figuring out what goes into viewmodel functions and when to use custom bindings. Maybe you could add some advice to the docs?
