### ISSUE TITLE
Save state of child templates on hot code pushes

### ISSUE THREAD

**Issue by zimt28** [ManuelDeLeon/viewmodel#39]
Only the state of the parent template gets saved at the moment. 
When using the child template without a parent template, it works.

**Comment by ManuelDeLeon** [comment]
It should work if you give each child's view model a unique name.

**Comment by zimt28** [comment]
Strange. I have one component that I use on multiple pages, but just include it once per page. I've set names as I do `ViewModel.byId` to access the component.

**Comment by ManuelDeLeon** [comment]
Please make a small repro...

**Comment by zimt28** [comment]
Tried to reproduce it but couldn't. Looks like it's a problem with one of the component's properties. So it's because of my code. I will update here when I find the reason.

Maybe you cold have a look at https://github.com/ManuelDeLeon/viewmodel/issues/37 and let me know what you think. And sorry for opening so many issues, I'm currently porting my whole app to `viewmodel` and love it so far, but I have so many questions and ideas. So please let me know if I can give something back :)

**Comment by ManuelDeLeon** [comment]
Don't worry about it. This is great feedback for both the library and the documentation. I'll be making some changes based on your feedback. To give you a heads up, I'll make it so you can use vm functions in the bindings:
```
<div data-bind="text: getName('department1', isPublic())"></div>
```
Where `getName` and `isPublic` are functions of the view model.

**Comment by zimt28** [comment]
Amazing :) One small detail, maybe it's possible to leave out the parentheses there, so that it looks consistent? Or doesn't the interpreter allow this? 
```
<div data-bind="if: isPublic, text: getName('department1', isPublic())"></div>
<!-- or -->
<div data-bind="if: isPublic, text: getName('department1', isPublic)"></div>
```

Great news anyway, looking forward to using this :+1:

**Comment by ManuelDeLeon** [comment]
Yep, you'll be able to leave out the parenthesis. I'll answer #37 with an example when I have the time. The summary is that right now the parameters are passed as strings so `doSomething(true)` is interpreted as `doSomething("true")`. I'll fix that too.
