### ISSUE TITLE
TypeError after hot code push when using delay binding

### ISSUE THREAD

**Issue by cgudrian** [ManuelDeLeon/viewmodel#40]
After a hot code push the client throws this exception whenever the delay timeout expires:

> Exception in setTimeout callback: TypeError: p.vm._vm_delayed[p.property] is not a function
>    at http://localhost:3000/packages/manuel_viewmodel.js:755:43
>    at _.extend.withValue (http://localhost:3000/packages/meteor.js:955:17)
>    at withoutInvocation (http://localhost:3000/packages/meteor.js:435:45)
>    at Meteor.bindEnvironment (http://localhost:3000/packages/meteor.js:983:22)

After a page reload the exception is gone.

**Comment by ManuelDeLeon** [comment]
I'll check it out.

**Comment by ManuelDeLeon** [comment]
I can't reproduce it. Please make a repro.

**Comment by cgudrian** [comment]
This project exposes said behavior:
https://www.dropbox.com/s/qrhbybu7wauh9xp/viewmodel40.tbz?dl=0

What might be important is that I added and removed the viewmodel explorer package. Perhaps there's some state in the browser (Chrome) that's triggering this exception?

**Comment by ManuelDeLeon** [comment]
Ah yes, right now viewmodel-explorer has that issue on hot code pushes =(
I've been kicking that can down the road for too long, I'll get on it. In the meantime your choices aren't that good: A) Refresh the page after your updates or B) Remove viewmodel-explorer

Sorry.

**Comment by cgudrian** [comment]
The thing is: I've already removed viewmodel-explorer… :)

After a hot code push a new instance of the ViewModel is created. Its `_vm_delayed` field is set to an empty object. After that `@_vm_addDelayedProperty` gets called. That call has no effect, though, because `valuesDelayed` has not been reset during the code push.

**Comment by ManuelDeLeon** [comment]
Pick up v1.5.4

viewmodel-explorer still breaks after a hot code push though =(

**Comment by ManuelDeLeon** [comment]
Ooops, I made the changes but forgot to publish 1.5.4. It's ready now.

**Comment by cgudrian** [comment]
Great! Thanks!

**Comment by ManuelDeLeon** [comment]
Get viewmodel-explorer 1.0.3, it works across hot code pushes.
