### ISSUE TITLE
How to use template data

### ISSUE THREAD

**Issue by satyavh** [ManuelDeLeon/viewmodel#43]
I'm having issues to pull template data into Viewmodel. So I'm using Iron Router and I'm doing something like this:

```
@route 'example',
   data: ->
      Collection.findOne @params.id
```

So in a template controller you can reach this data, for example via `Template.currentData()` or `@` in helpers. However, trying to call Template.currentData() from within Viewmodel results in errors, and `@` obviously refers to Viewmodel.

So I've tried to get this data via a Session variable, like this:

```
data: ->
  Session.set 'templateData',  Collection.findOne @params.id
```

which I pull in either in a Viewmodel function or set it on a variable:

```
name: Session.get('templateData').name
```

which sometimes works, but sometimes results in undefined (probably some timing issues here).

So what's the right way to get template data with Viewmodel?

**Comment by ManuelDeLeon** [comment]
See: http://viewmodel.meteor.com/#definingBk

You basically define the view model with a function that takes the data context. You can use as many view model definitions as you like (functions or objects). They get appended to the the view model.
```
Template.home.viewmodel(
  // Add all properties in the data context
  function (data) { return data; }, 
  // Add more properties (some using the data context)
  function (data) {
    return {
      isEven: data.number % 2 === 0,
      address: '123 Main St.',
      zip: 12345
    }
  },
  // Now use a plain object
  {
    name: ''
  }
);
```

**Comment by tomeglenn** [comment]
@ManuelDeLeon This still doesn't always work. Doing the same thing as @satyavh I am defining a route with iron:router that returns a `Collection.findOne({})` as the data context. Then I define my viewmodel as follows.

```
Template.edit.viewmodel('edit', function(data) {
  return {
    id: data._id
  }
});
```

This results in `Uncaught TypeError: Cannot read property '_id' of null` when I browse to the url manually. Works fine if I hit the url from a link, so again I suspect strange timing issues.

**Comment by ManuelDeLeon** [comment]
@tomeglenn Please make a repro. It looks like IR is rendering the template before there's something in the collection.

**Comment by tomeglenn** [comment]
@ManuelDeLeon Thanks for the quick response. When I get the chance I'll try and put together a sample.
