### ISSUE TITLE
Template.templatename.viewmodel is undefined

### ISSUE THREAD

**Issue by nicolamr** [ManuelDeLeon/viewmodel#44]
Hey there, this looks like a great module. I just installed it and added your loginBox example, but the following error pops up in the console:

TypeError: Template.loginBox.viewmodel is not a function

apparently it's undefined.

**Comment by ManuelDeLeon** [comment]
Looks like you don't have a loginBox template defined (in your markup) .

**Comment by nicolamr** [comment]
Thanks for the answer. Actually I do, and defining helpers for the template works just fine. What's undefined is the function "viewmodel", not the template.

**Comment by nicolamr** [comment]
Hey, updating from meteor 1.0 to 1.1 (and a bunch of other packages) fixed the issue.
