### ISSUE TITLE
Parent is set too late

### ISSUE THREAD

**Issue by nicolamr** [ManuelDeLeon/viewmodel#45]
@parent() is available in a viewmodel function if it's used with data-bind, but not if used as a template helper.
See the following example:

```
Template.test.viewmodel 'test',

Template.child.viewmodel 'child',
    helper: ->
        if @parent?
            "yes"
        else
            "no"
, "helper"
```

```
template(name="test")
    +child

template(name="child")
    p #{helper}
    p(data-bind="text: helper")
```

The result is

```
no
yes
```

**Comment by ManuelDeLeon** [comment]
This was answered in #46 but here's the explanation for a future developer crawling the issues:

`p #{helper}` is a blaze helper method, it doesn't have a parent method/property.
`p(data-bind="text: helper")` is bound to the view model which does have a parent.
