### ISSUE TITLE
Viewmodel is nonreactive to changes in template data

### ISSUE THREAD

**Issue by nicolamr** [ManuelDeLeon/viewmodel#46]
Here's an example

```
Template.test.viewmodel 'test',
	name: "John"
	newName: ''
	changeName: ->
		@name @newName()
, "name"

Template.child.viewmodel 'child', (data) ->
	name: data
, "name"
```

```
template(name="test")
	input(data-bind="value: newName, returnKey: changeName")
	p #{name}
	with name
		+child

template(name="child")
	p #{name}
	p(data-bind="text: name")
```

The first output will be

```
John
John
John
```

Entering 'Mike' and pressing enter yields

```
Mike
John
John
```

**Comment by ManuelDeLeon** [comment]
Please make a repro (something I can clone and run). That way I don't have to guess what it should do.

**Comment by nicolamr** [comment]
Ok, here it is: https://github.com/nicolamr/test
I also added the test for the other issue I posted.
I never had to do this, so if there's a more efficient way to make a repro please let me know.

**Comment by ManuelDeLeon** [comment]
That's good. The first problem is a little bit confusing so I'll get back to you on that one. The second one is simple: when you use 'helper' as a helper method then @ (this) refers to the helper context, not the view model. When you use 'helper' in a data bind then @ (this) refers to the view model and it does have a parent.

**Comment by ManuelDeLeon** [comment]
Here's the deal, Blaze is kind of cheating in that the name property is reactive only for helper purposes. It knows that the helper comes from the parent template and thus hooks/binds it the parent. To give you an idea, you can't get the same behavior if you try to put name in a Tracker.autorun.

On the other hand the view model is only getting a non-reactive object when it's initialized ({name:"John"}). You have 2 options: 1) pass an object to the child with a function that returns the parent's name or 2) reference @parent().name() from the child. #2 is the simplest/cleanest one.

**Comment by nicolamr** [comment]
Thank you for your time. I appreciate your efforts. I spent a couple of days exploring your module, which is very nice. But I got into these complex situations because I have forms with parts that change depending on the user input. As soon as you have to communicate between different levels of viewmodels/helpers, it starts to feel hacky and not intuitive (a lot of time is spent trying things out without knowing whether they will work). I wonder why the meteor development team didn't go all the way to implement full two-way data binding. I'd have preferred your module, which adheres much more to the meteor philosophy, but I think I'm going to take a look at angular-meteor for my current project. Thank you again, and keep up the good work.

**Comment by ManuelDeLeon** [comment]
The problem is that you're expecting your view models to have dynamic contexts like Blaze does. In Blaze the context changes every two steps. If you look at Blaze 2 proposals they're trying to move away from it and standardize the context. In ViewModel the context is always the same (the view model, however you create it).

If you're going with Angular I suggest you take a look at the Aurelia project (http://aurelia.io/). It's to Angular as Coffeescript is to Javascript.
