### ISSUE TITLE
Why am I getting the parent's data context here?

### ISSUE THREAD

**Issue by coopermaruyama** [ManuelDeLeon/viewmodel#47]
I have a ViewModel (`CallToAction`) to which I'm passing the following data context via this helper:

```coffeescript
Template.MyTemplate.helpers
   rightCTAData: ->
      id: 'toc_progress_cta'
      title: 'Track your progress'
      message: 'Login to track your progress and get access to videos and tests!'
      buttons: [
        {
          buttonText: 'New user'
          buttonAction: ->
            Router.go 'atSignIn'
        }
        {
          buttonText: 'Existing user'
          buttonAction: ->
            Router.go 'atSignIn'
        }
      ]
```

MyTemplate's Template:

```jade
template(name="MyTemplate")
  +CallToAction rightCTAData
```

Here's the viewnodel receiving this data:

```js
var CallToAction = function(data) {
  return {
    title: data.title,
    message: data.message,
    buttons: data.buttons,
    addButton: function(button) {
      this.buttons().push(button);
    },
    shouldGroupButtons: function() {
      return this.buttons().length > 1;
    }
  }
}

if (Meteor.isClient) {
    Template.CallToAction.viewmodel(
      CallToAction, // ViewModel
      'buttons' // helper
    );
}
```

And here's the template for it:

```jade
template(name="CallToAction")
  h2(data-bind="text: title")
  p(data-bind="text:message")
  if shouldGroupButtons   
    .uk-button-group
      each buttons
        +Button 
  else
    +Button
```

`Button` is also a viewmodel, defined like this:

```js
var Button = function(data) {
  return {
    buttonText: data.buttonText,
    doButtonAction: function() {
      var actionType = typeof data.buttonAction;
      if (actionType == 'string') {
        var target = data.navigationTarget;
        Router.go(target);
      }
      if (actionType == 'function') {
        return data.buttonAction();
      }
    }
  }
}

if(Meteor.isClient){
  Template.Button.viewmodel( Button );
}
```

And here's the template:

```jade
template(name="Button")
  button.uk-button.uk-button-primary(am-Button data-bind="text: buttonText, click: doButtonAction")
```

I've done testing on the `Button` VM and it works just fine when passed one of the objects in the `buttons` array that `rightCTAData` uses... as long as it's used on its own. The `CallToAction` viewmodel also seems to be working, since the `title` and `message` are displaying correctly. 

As you can see in the screenshot below, the `buttons` property of the `CallToAction` viewmodel also looks to correcly contain an array of the necessary buttons: ![screenshot](https://s3.amazonaws.com/f.cl.ly/items/323v3x3x2c2F382D2d0C/Image%202015-05-13%20at%204.49.04%20AM.png)

The problem is that for some reason, in the `each` block defined the `CallToAction` template that renders each button, the data context for each button is being set to the entire context for `CallToAction` (i.e. the `rightCTAData` object) rather than just the context for each button in the `buttons` array, which should be the standard behavior of Spacebars. If change `buttonText: data.buttonText` to `buttontext: data.buttons[0].buttonText`, it correctly renders the text. 

So, what gives? Thanks in advance for the help!

**Comment by ManuelDeLeon** [comment]
Make a repro...

**Comment by coopermaruyama** [comment]
Sorry, meant to close this. I was doing just that and then figured it out - it was due to the `shouldBeGrouped` method not being defined as a helper.
