### ISSUE TITLE
new to meteor:viewmodel

### ISSUE THREAD

**Issue by rvolari** [ManuelDeLeon/viewmodel#48]
Manuel,
Very exciting what you have done. and a big thank you : )
I am new to meteor:viewmodel - and a big fan of KO.
I added your package to meteor and setup an extremely basic test application. 
I am getting an error: Uncaught TypeError: Cannot read property 'viewmodel' of undefined
Seems like the 'meteor add manuel:viewmodel' did not take though meteor runs ok, the error is in the console.
Hope the question is not too basic for you.
Thank you in advance

**Comment by ManuelDeLeon** [comment]
Are you using the latest meteor? How are you defining the viewmodel?

**Comment by rvolari** [comment]
Thank you for your very quick response.
Copies & pasted the code here: http://viewmodel.meteor.com/#loginBoxBk (and nothing else)

here is the meteor list:
autopublish       1.0.3  
insecure          1.0.3  
manuel:viewmodel  1.6.5  
meteor-platform   1.2.2  

Thanks again

**Comment by ManuelDeLeon** [comment]
That's not enough, I have no clue what you're running. Make a repro.

**Comment by rvolari** [comment]
I understand - because the code is short, i will paste here: HTML
<body>
  {{> loginBox}}
</body>
<template name="loginBox">
    First Name: <input type="text" data-bind="value: first"/>
    <br/>
    Last Name: <input type="text" data-bind="value: last"/>
    <div data-bind="text: greeting"></div>
    <a data-bind="enabled: canEnter, hover: showError" class="btn-primary">Enter Site</a>
    <span data-bind="text: errorText" class="text-error"></span>
</template>

--------------JS
if (Meteor.isClient) {
  Template.loginBox.viewmodel({
    first: '',
    last: '',
    greeting: function() {
      return "Hello " + this.first() + " " + this.last();
    },
    canEnter: function() {
      return !!this.first() && !!this.last();
    },
    showError: false,
    errorText: function() {
      if (this.canEnter() || !this.showError()) {
        return '';
      }
      return "Please enter your first and last name";
    }
  });
}

**Comment by ManuelDeLeon** [comment]
In your case Template.loginBox is undefined as if the template isn't
defined in html.

Try putting the code inside the client folder instead of using
Meteor.isClient

**Comment by ManuelDeLeon** [comment]
If that doesn't work make a repro.

**Comment by rvolari** [comment]
Hi Manuel,
Thanks for your very prompt responses.
So I tried your suggestion and i am sure i am making some very silly mistake and that did not work.
I have repo'd that and added you as a collaborator. 
Thanks again

**Comment by ManuelDeLeon** [comment]
You don't have a loginBox template, only 'hello':
```
<template name="hello">
  <button>Click Me</button>
  <p>You've pressed the button {{counter}} times.</p>
</template>
```

**Comment by rvolari** [comment]
I am so embarrassed ... 
I thought i had updated the file in my folder.
Thanks so much for this ... 
And thanks for recreating the MVVM in meteor : )
Just a quick question - have you done any performance testing? Do you have any matrix for limitations? users/complexity?

Thanks Manuel . I made the changes and it did work :+1:

**Comment by ManuelDeLeon** [comment]
Not done performance tests but "it's fast enough" =)
Want to take up the task of doing the performance tests?

**Comment by rvolari** [comment]
I would like to very much ... I am planning on spending the next few weeks and learning (and tinkering) with this. 
Let me know how you suggest i move forward with performance testing. If you see I would be able to help, I would welcome the opportunity to do what I can to make this possible. (full disclosure, I am not an expert, and I am a very quick learner).
Thx

**Comment by ManuelDeLeon** [comment]
the reason I ask is because I have no clue of how to do it so you're on your own there =/

**Comment by rvolari** [comment]
:) got it ... I will do some research and i will share what i find.  I am interested to help.  Let's see how much i would be able to contribute.
Also question, are you part of meteor core development? I ask is because of the subdomain viewmodel.meteor.com?
Thx

**Comment by ManuelDeLeon** [comment]
LOL, no. Anyone can get a *.meteor.com website. You just create your app and then run `meteor deploy` and voila, your website is up and running. See http://docs.meteor.com/#/full/meteordeploy

**Comment by rvolari** [comment]
: )  ... i guess you got the perfect one then ... I will keep you updated on my learning curve and any performance tests that i think could be appropriate. BTW, have you used your plugin for any larger scale production apps that you could share?
Thx

**Comment by ManuelDeLeon** [comment]
Not large scale but got this running: responses.me

Other people are using it in prod too.

**Comment by rvolari** [comment]
Awesome : )  Thx for the info. I will keep you updated on my progress and hopefully some near future performance test once i have things under control. Thx again for your help
