### ISSUE TITLE
How do we integrate this to Orion?

### ISSUE THREAD

**Issue by timfam** [ManuelDeLeon/viewmodel#49]
This will be great if we can make it an integral part of Orion https://github.com/orionjs/orion. I'm inviting you to Orion gitter room

**Comment by ManuelDeLeon** [comment]
I have no clue how Orion works but I'm open to help out. Have you talked to anyone about it? I searched the Orion Gitter room and I couldn't find anything relating to this project.

**Comment by timfam** [comment]
Nothing yet because I just saw this package and gosh it's damn hot! So I opened up a channel to talk collaboration. I will ping you on gitter

**Comment by ManuelDeLeon** [comment]
k, closing this one then.
