### ISSUE TITLE
Examples for using with Autoform

### ISSUE THREAD

**Issue by rwatts3** [ManuelDeLeon/viewmodel#50]
Hi Manuel first of all great work on this project.  I will be using view model on a few packages with Orion. In the meantime do younger examples on integrated use with Autoform ? I see in the examples you are using native input boxes , but I and we use autoform pretty heavily so if you have advice or docs on integrated use with Orion that would be awesome.  

Thanks 
Ryan

**Comment by ManuelDeLeon** [comment]
I haven't used autoforms but if it has an "after-render" hook (similar to Blaze onRendered) and it allows you to add data-* attributes to the elements it generates (specifically data-bind), then it's technically possible to use the two together.

Assuming those 2 prerequisites are met, the way you would use the two is by creating a view model in the onCreated event, configure autoforms to add the proper data-bind attributes for the elements it generates (e.g. add data-bind="value: name" to the name field input box), and finally call the .bind method of the view model.

I hope this helps.

**Comment by rwatts3** [comment]
Ah I believe that solution will work . Auto form allows you to pass any
amount or type of attributes including data attributed and classes. So I'd
imagine I ca still use the CRUD functionality of autoform along with the
MVVM. I'll try some examples and I'll post something once I test things out

**Comment by ManuelDeLeon** [comment]
cool, see "Getting your hands dirty" under http://viewmodel.meteor.com/#definingBk

Let me know how it goes.

**Comment by rwatts3** [comment]
Will do.  Did you use any MVVM on the nav for the demo site ? Or is it
basic bootstrap and hard coded ?

On Tuesday, May 19, 2015, ManuelDeLeon <notifications@github.com> wrote:

> cool, see "Getting your hands dirty" under
> http://viewmodel.meteor.com/#definingBk
>
> Let me know how it goes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ManuelDeLeon/viewmodel/issues/50#issuecomment-103669216>
> .
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts

**Comment by ManuelDeLeon** [comment]
It depends on what demo site =)
The documentation nav is plain bootstrap.

The phonebook example (https://github.com/ManuelDeLeon/phonebook) has a header bar that does uses a view model. The header has a search box and lists are filtered based on that value. That project is done with Semantic UI though.

**Comment by rwatts3** [comment]
I see thank you for that additional insight.

On Tuesday, May 19, 2015, ManuelDeLeon <notifications@github.com> wrote:

> It depends on what demo site =)
> The documentation nav is plain bootstrap.
>
> The phonebook example (https://github.com/ManuelDeLeon/phonebook) has a
> header bar that does uses a view model. The header has a search box and
> lists are filtered based on that value. That project is done with Semantic
> UI though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ManuelDeLeon/viewmodel/issues/50#issuecomment-103671712>
> .
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts

**Comment by TomFreudenberg** [comment]
Hi Ryan @rwatts3 

had you some results about using viewmodel and autoform?

Thanks for a reply
Tom

@ManuelDeLeon Thanks for sharing this package!

**Comment by rwatts3** [comment]
Hello I haven't tried it just yet.  But I'll add it to my to-do.  And let
you know what results I have.

**Comment by TomFreudenberg** [comment]
I made some tests today and I really impressed that a lot is running out of the box. Pretty cool @ManuelDeLeon !


Here is just a very simple one

````
<template name="updateBook">
  <div id="updateBook" class="row">
    <div class="col s4 l8">
      {{#autoForm collection="Books" id="updateBook" type="update" doc=my_doc }}
      <fieldset>
        {{> afQuickField name="title" }}
        {{> afQuickField name="author" data-bind="hover: mouseIsOver" }}
      </fieldset>
      {{/autoForm}}
    </div>
    <span data-bind="text: errorText, if: mouseIsOver" class="text-error"></span>
  </div>
</template>
````

and that is the viewmodel code part

````
Template.updateBook.viewmodel(
  function(data) {
    return { data: data.doc };
  },
  {
    my_doc: function() {
        var doc = this.data().doc();
        return doc;
    },
    mouseIsOver: false,
    errorText: function() {
      return "Value = " + this.title();
    },
    title: function() { 
      var doc = this.data().doc();
      return doc && doc.title 
    }
  }, 'my_doc'
);
````

So if hover over the author, the viewmodels binding will take part and shows the Text.


---

So, if you want to extend your AutoFormFields with some bindings activities, you just can step in.

What is missing? It would be great, if `autoForm` and `quickForm` could be used when using a viewmodel instead the collection or schema as well.

I will check this if possible to add.

TBC

**Comment by TomFreudenberg** [comment]
After reading more documentation, I guess there is "nothing todo" to the packages like autoform, simple-schema, collection2 and viewmodel. It is more like you create your app and where you put your logic.

First (quick) impression is:

1) If you work on a collection

- use collection2/simple-schema to describe your data and define your validation rules of the dataset
- if you need to extend virtually the dataset just use transform best with package meteor-collection-helpers
- if you want to have simple input forms, just use autoform and quickform without any magic
- if you want to improve the ui just create a viewmodel and  use autoform and quickfields with additional data-binds

2) if you do not rely on a collection (or want to have full power over your ui)

- use a schema
- create your viewmodel
- use autoform with schema and custom validation and methods
- add data-binds on your quickfields and check via schema validations
- handle data and post or whatever by viewmodel actions (or server methods)

I will try and prepare some example app for that setup

**Comment by dnish** [comment]
Have to reopen it again, what about ViewModel 2? If I define an input like:

    {{> afFieldInput name="title" type="text"}}

Is there any way to also include a {{b "value:title"}}?
