### ISSUE TITLE
Parent is undefined.

### ISSUE THREAD

**Issue by komogitski** [ManuelDeLeon/viewmodel#51]
After update to latest version of the ViewModel I get the errors like:

"Exception from Tracker recompute function:"
"TypeError: self.parent(...) is undefined"
"ViewModel/this.dispose@http://localhost:3000/packages/manuel_viewmodel.js?:275:9

Please give me any suggestions what I do wrong?

**Comment by ManuelDeLeon** [comment]
The root cause of the problem is between my chair and keyboard =/

I can't fix right now but I'll do so tonight. In the meantime use a previous version and you'll be fine.

Sorry about that.

**Comment by komogitski** [comment]
Thank you for quick response and for very useful and powerful package.
Should I make any changes in my code after your fix?

**Comment by ManuelDeLeon** [comment]
You shouldn't but I would love to know what you're doing since that error wasn't caught by my test suite.

**Comment by ManuelDeLeon** [comment]
btw, I think I just have to check if the view model has a parent before calling it and everything will be fine.

**Comment by dcrescim** [comment]
I get the same sort of issue when dispose is called on the viewmodel. The exception looks like

TypeError: Cannot read property '_vm_children' of undefined. 

Looks like line 275 of viewmodel.coffee.js

      if (self.parent) {
        self.parent()._vm_children.remove(self);
      }

Hope this helps! Minor glitch, but still love the package.

**Comment by ManuelDeLeon** [comment]
`$ sorry --really`

I'll fix it tonight.

**Comment by ManuelDeLeon** [comment]
Upgrade to 1.6.8
