### ISSUE TITLE
Access to viewmodel via console

### ISSUE THREAD

**Issue by rvolari** [ManuelDeLeon/viewmodel#52]
Hi Manuel,

Thanks for all your help.
I am wondering if you could direct me on how i can achieve visibility to the viewmodel prototypes and methods in the client console (say on chrome).
In KO, we can access the observable or its values directly from the console?
Is there a way that this could also be possible in your implementation?
(i.e. getting the value of a view model property 'first', or triggering a viewmodel method etc.)

Thanks so much

**Comment by ManuelDeLeon** [comment]
Sure. You have a couple of options.
1) If you gave a name to the view model: `ViewModel.byId(strName)`
2) If the view model is used in a template: `ViewModel.byTemplate(strName)`
3) To get a list of all view models: `ViewModel.all`
4) Use the package `manuel:viewmodel-explorer`

See:
http://viewmodel.meteor.com/#compCommunicationBk
http://viewmodel.meteor.com/#viewmodelExplorerBk

**Comment by rvolari** [comment]
Hi Manuel,
Thanks so much for the reference.
These help greatly : ) 
And I really appreciate this.

So I have been playing around and still getting comfortable with your code.
And I have ran across a situation that I am hoping you may be able to help.
In KO, we can have looping to populate things. Specifically a SELECT list and create <optgroup> etc
Such as below:

                    <select name="list-things" id="myList"
                            data-bind="value: itemSelected">
                        <option value="na"> -- Select Below -- </option>
                        
                        <optgroup data-bind="attr: {label: listGroupName}">
                            
                            
                                <option data-bind="text: itemName"></option>
                            
                            
                        </optgroup>
                        
                    </select> 
Is this also possible in 'viewmodel' ?

Thank you so much as always. I working to make progress and understand more. Hopefully in a few weeks I should be up to par to do some testing as I had promised.
Thx

**Comment by ManuelDeLeon** [comment]
Nope, for that kind of fine grained control of the DOM you have to use good
old Blaze.

**Comment by rvolari** [comment]
Thanks so much Manuel.
I am still forging ahead.  Made some progress.
I am hoping that within the next 3 week I would have an ok handle on viewmodel.

On another note, what is your suggest for best practices, to change the property of a viewmodel for Template X, from another Template Y.
(example: in Template X has a button that is normally disabled (using a viewmodel reactive class variable), until all the fields in form located in Template Y has been entered. Should I access, and set the value of of the enable/disable via ViewModel.byTemplate('X')? or some other way).

Thanks so much.

**Comment by ManuelDeLeon** [comment]
You're still thinking in imperative and event driven. Here's how you do it with view models:
```
Template.AAA.viewmodel({
  buttonEnabled: function() {
    var vmB = ViewModel.byId("BBB");
    return vmB && vmB.complete();
  }
})
```
```
Template.BBB.viewmodel( "BBB" , {
  name: '',
  address: '',
  complete: function() {
    return !!this.name() && !!this.address();
  }
})
```
Notice how we don't "set" the value of buttonEnabled, it changes based on B. So B doesn't set the enabled value of A, it doesn't even know that A exists. If template A depends on B then it's A's job to pull the values from B.

**Comment by rvolari** [comment]
You are correct.
It seemed as though I had not kicked that habit of imperative approach.
Your explanation and example was perfect to drive that point home for me. Thx
One more item to request: (and I am sure I am not going to say it the right way - so apologies in advance) how can I associate a viewmodel (an observable) to a template helper?
example:

  Template.homeStuff.helpers({
    houseItems: [
      { item: "desks" },
      { item: "chairs" },
      { item: "books" } ]
  });
To make 'houseItems' a viewmodel so that if it changes then the view updates as well. 'houseItems' will be specifically used inside <option> tag of select box. Thx
Best, R

**Comment by ManuelDeLeon** [comment]
See the helpers parameter when defining view models (the easiest way) :
http://viewmodel.meteor.com/#definingBk

And blaze_helpers hook:
http://viewmodel.meteor.com/#blazeHooksBk

**Comment by rvolari** [comment]
Got it. Perfect : )
It is working. Thanks so much.
Also in KO, there is concept of 'subscribe', to watch for changes to an observable and then 'do' something. Does 'viewmodel' have something similar? (or is there another way in Meteor).
Thanks so much Manuel.

**Comment by rvolari** [comment]
-- note regarding above: I believe you have implemented 'change:' data-binding which acts similar to the 'subscribe' on KO? (am I on the right path?)
If my understanding is correct, I also searched for a 'beforeChange' (similar to KO 'subscribe - "beforeChange") and I could not find one. Am I missing something?  Is there a way to implement that?
Thank you

**Comment by ManuelDeLeon** [comment]
I don't think I'll implement before change soon just because it requires
major tinkering with ViewModel.

**Comment by ManuelDeLeon** [comment]
Btw, change does works like subscribe but declaratively.

**Comment by rvolari** [comment]
Hi Manuel,
Thanks so much for the input.  I have been tinkering with 'change' and I am getting a hang of this (I think : ) 
I have a question outside the scope of viewmodel, because you seem to be very versed in Meteor.
In your suggestion above, you had mentioned a declarative approach:

Template.AAA.viewmodel({
  buttonEnabled: function() {
    var vmB = ViewModel.byId("BBB");
    return vmB && vmB.complete();
  }
})

With viewmodel, you seem to have created a way to get 'visibility' into properties and/or methods of another template. (using ViewModel.byId or ViewModel.byTemplate).  Is there such a thing in Meteor as well?  Can one template get access to another template's info?  if so, how? 
Thanks so much.
R

**Comment by ManuelDeLeon** [comment]
You can only do that with some kind of global object (session vars,
reactive dict, or reactivevars in a global object of your own). Template
instances don't expose their properties.

**Comment by rvolari** [comment]
I see.
Thanks so much for the explanation.
Btw, since you are 'the' expert on 'viewmodel' : ) 
And because they just seem to have uses for every object/var (can technically replace Session var), in what cases do you suggest it would not be a good idea to use viewmodels?
Thx

**Comment by ManuelDeLeon** [comment]
With view models I rarely if ever use Sessions, reactive-vars, and reactive-dicts, so I don't feel the need to replace them (since I don't use them). If you're using them, then I don't think you should replace them with view models since they're lighter weight.

That said, a view model is a great way to have an object with (reactive) functions that depend on other properties of the same object.

**Comment by ManuelDeLeon** [comment]
btw, just to be clear, it's not that I use view models instead of Sessions, reactive-vars, and reactive-dicts. It's that when you code with view models you rarely need them.

**Comment by rvolari** [comment]
Thanks for the clarification. I believe I get you (I think I do).
You are referring to the same type of logic you talked about before (not thinking imperatively). So if the code is written to function with view models then it will not need (or should not need Sessions/Recactive Vars/Dicts).
Thanks for sharing.  Continuing on my learning / practicing / experimenting with your viewmodels : )
