### ISSUE TITLE
Code legibility

### ISSUE THREAD

**Issue by ffxsam** [ManuelDeLeon/viewmodel#53]
Hey there,

Are you open to people contributing pull requests to this package?

**Comment by ManuelDeLeon** [comment]
Sure, what do you have in mind?

**Comment by timfam** [comment]
Manuel beat me to it. :)

**Comment by ffxsam** [comment]
Not 100% sure yet, but if I get the time, I'll submit a PR! Thanks

**Comment by ManuelDeLeon** [comment]
If you're bored there are a couple of tests missing (right now I'm only checking that the bindings are there):
* visible/if
* hidden/unless
* file
* files
* focused

The tests are in the documentation project: https://github.com/ManuelDeLeon/viewmodel-docs
