### ISSUE TITLE
Viewmodel + FlowRouter

### ISSUE THREAD

**Issue by zimt28** [ManuelDeLeon/viewmodel#54]
When I define a viewmodel on a template and then change the route using FlowRouter, I get the following error:
```
[Log] Exception from Tracker recompute function: (meteor.js, line 888)
[Log] TypeError: null is not an object (evaluating 't.viewmodel') (meteor.js, line 888)
```

Using `template.viewmodel 'Login', {}` is enough to cause this error. I'm using the newest version of viewmodel, also tried the older 1.5.1 version, same error.

**Comment by zimt28** [comment]
The chrome output might be better:
```
Exception from Tracker recompute function:
debug.js:41 TypeError: Cannot read property 'viewmodel' of null
    at ViewModel.vm.parent (viewmodel.coffee:101)
    at ViewModel.dispose (viewmodel.coffee:26)
    at null.<anonymous> (hooks.coffee:72)
    at template.js:116
    at Function.Template._withTemplateInstanceFunc (template.js:437)
    at fireCallbacks (template.js:112)
    at null.<anonymous> (template.js:218)
    at fireCallbacks (view.js:267)
    at Object.Tracker.nonreactive (tracker.js:560)
    at view.js:264
```

**Comment by zimt28** [comment]
I'm not sure if this affects something else in the viewmodel package but just changing [this line](https://github.com/ManuelDeLeon/viewmodel/blob/master/viewmodel.coffee#L101) to `vm.parent = -> t?.viewmodel` fixes the problem for me.

**Comment by ManuelDeLeon** [comment]
I included your update. Thanks
