### ISSUE TITLE
blaze_event property shall be a plain object

### ISSUE THREAD

**Issue by sveinburne** [ManuelDeLeon/viewmodel#57]
**Version 1.7.1**
Hi and thank you for this great job. 
I have a problem using blaze_event. I do it the same as provided on the documentation : 

    Template.person.viewmodel({
     doSomething: function() {
      // Do something
      },
      blaze_events: {
        'click #fancyButton': function() {
        Template.instance().viewmodel.doSomething();
       }
     }
    }); 

Indeed, `hooks.coffee`  61 & 62th line are : 
    
     if this.viewmodel.blaze_events
        template.events this.viewmodel.blaze_events()

So to make it work, I have to replace the `blaze_event` property as follow : 
    
      blaze_events: function() {
        return {
            'click #fancyButton': function() {
            Template.instance().viewmodel.doSomething();
       }
    }

**Comment by ManuelDeLeon** [comment]
Ouch, that was embarrassing. Upgrade to 1.7.2
Thanks for the heads up.
