### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by santiagopuentep** [ManuelDeLeon/viewmodel#59]
Hi. I'm installing the viewmodel package but I can't use it. There isn't any Template.myTemplate.viewmodel function. Also, the installed version is 1.3.2 (old).

I would love to try out your solution to the many problems I was having with Blaze!

**Comment by ManuelDeLeon** [comment]
Make sure you have the latest version of Meteor and ViewModel.

**Comment by santiagopuentep** [comment]
I have the latest version of meteor and I called meteor update. Everything up to date. Using meteor for Windows, maybe that's the problem?

**Comment by sveinburne** [comment]
`meteor update` might not work while running the application. What does `meteor list` prints?

**Comment by ManuelDeLeon** [comment]
Nope, I use Windows without a problem. Force meteor to use the Viewmodel
v1.7.4 (the latest)

**Comment by santiagopuentep** [comment]
Meteor lists outputs the following:

manuel:viewmodel  1.3.2* Native MVVM framework for Meteor. Similar to
Knockout and Angular.
meteor-platform   1.2.2-rc.0* Include a standard set of Meteor packages in
your app


* New versions of these packages are available! Run 'meteor update' to try
to update those packages
  to their latest versions. If your packages cannot be updated further, try
typing
  `meteor add <package>@<newVersion>` to see more information.

I'll try that.


---
Santiago Puente.

2015-06-03 3:04 GMT-03:00 ManuelDeLeon <notifications@github.com>:

**Comment by ManuelDeLeon** [comment]
Going to sleep now. I hope you resolve it. If not, I'll help you tomorrow.

**Comment by santiagopuentep** [comment]
Me too. I'll let you know tomorrow if I was able to solve it. Thanks!


---
Santiago Puente.

2015-06-03 3:06 GMT-03:00 ManuelDeLeon <notifications@github.com>:

> Going to sleep now. I hope you resolve it. If not, I'll help you tomorrow.
>

**Comment by ManuelDeLeon** [comment]
I know what's going on. Remove Meteor and install the latest from scratch.

**Comment by santiagopuentep** [comment]
Manuel, I was able to solve it. I reinstalled but it wasn't doing any good.
The problem was that my project was stuck with windows preview 0.3.0 and
was not updating. I recreated the project with the latest version and now
your package works correctly. Thanks for the help!


---
Santiago Puente.

2015-06-03 3:07 GMT-03:00 ManuelDeLeon <notifications@github.com>:
