### ISSUE TITLE
viewmodel subscriptions issue

### ISSUE THREAD

**Issue by sveinburne** [ManuelDeLeon/viewmodel#60]
Hi again! I was quite amazed by your ultra-fast answer last night, hope you're doing well, thanks a lot :) 
I seem to have trouble handling subscriptions with viewmodel. 
I tried two ways to achieve my goal, which is to have a working template whenever the user refreshes the page by hand. 

* Via the `Router.route` configuration : 

router:

        Router.route('/administration/rules',{
        name:'adminRules',
        data:function(){
            return GlobalConfig.findOne();
        },
        waitOn:function(){
            this.subscribe('globalconfig');
         }});

viewmodel :

     Template.adminRules.viewmodel(function(globalConfig){
        console.log(globalConfig);
        var id=globalConfig?globalConfig._id:null;
        return {
            allowUsers:globalConfig?globalConfig.usersCanCreateProject:false,
            updateConfig:function(){
                GlobalConfig.update({_id:id},{$set:{usersCanCreateProject:this.allowUsers()}});
            }
        }
    });
    
`globalConfig` remains `null` if I refresh by hand.

* Via template' subscription `onCreated`

onCreated:

    Template.adminRules.onCreated(function(){
        this.subscribe('globalconfig');
    });

viewmodel:

    Template.adminRules.viewmodel(function(){
        var globalConfig=GlobalConfig.findOne();
        console.log(globalConfig);
        var id=globalConfig?globalConfig._id:null;
        return {
            allowUsers:globalConfig?globalConfig.usersCanCreateProject:false,
            updateConfig:function(){
                GlobalConfig.update({_id:id},{$set:{usersCanCreateProject:this.allowUsers()}});
            }
        }
    });

Same problem here... did I do something wrong?
Thanks in advance for your insights!

**Comment by ManuelDeLeon** [comment]
I don't use Iron Router so I don't know why it's letting the template render without a globalConfig.
Either way, I wouldn't do the whole waitOn + data thing. I'd do something like the following:
```
Template.adminRules.viewmodel({
	globalConfig: function() {
		return GlobalConfig.findOne();
	},
	allowUsers: function() {
		return this.globalConfig() && this.globalConfig().usersCanCreateProject;
	},
	updateConfig: function() {
		if (this.globalConfig()) {
			GlobalConfig.update( this.globalConfig()._id ,{ $set: { usersCanCreateProject: this.allowUsers() } } );
		}
	}	
});
```

**Comment by sveinburne** [comment]
Great thanks, that's working!
Just curious : is it that you can pass reactive sources to the viewmodel, and it will update the view accordingly ? How is this managed?

**Comment by ManuelDeLeon** [comment]
When defining a view model, properties are converted to functions that use Tracker's dependency management, functions are left "as is" so if they're reactive then you can use it anywhere you could use a reactive source.

**Comment by sveinburne** [comment]
Actually, with this "workaround", the `change` binding is not triggering anymore, any clue?

**Comment by ManuelDeLeon** [comment]
That's because updateConfig doesn't return anything (well, technically it always returns undefined).

**Comment by sveinburne** [comment]
Ok, managed to get it work with a click binding on the label element, as follows : 

     <div class="switch round" >
           <input id="allowAnyUserToCreateProject" data-bind="checked: allowUsers" type="checkbox"/>
           <label for="allowAnyUserToCreateProject" data-bind="click: updateConfig"></label> 
     </div>

As you stated, the function is kept as it is, so I had to change the updateConfig this way to do the job : 

       updateConfig:function(){
            GlobalConfig.update({_id:globalConfig()._id},{$set:{usersCanCreateProject:!this.allowUsers()}});
        }
