### ISSUE TITLE
Reactivity problems

### ISSUE THREAD

**Issue by santiagopuentep** [ManuelDeLeon/viewmodel#64]
Hi Manuel.

I'm not getting reactivity with the following setup and I don't undestand why.

I have an items collection with the following schema:

	// item
	{
		_id: "iuosg982345lksa",
		text: "item text",
		// array of _ids from other items
		children: ["198540189asdf12", "asq0189asdf12", "wtq540189asas2"]
	}

My viewmodel has a getChildren() method that fetches the actual items from the ids like this:

	getChildren: function() {
		var result = [];
	
		// dataContext() does a Items.find() with the current item _id.
		var childrenIds = this.dataContext().children;
		
		var total = childrenIds .length;
		for (var i = 0; i < total; i++) {
			var child = ItemsList.findOne(childrenIds [i]);
			if (child) {
				result .push(child);
			}
		}
		return result ;
	}

If I change the children array from any item the viewmodel doesn't update.

What am I doing wrong?

The template uses an #each statement over getChildren().

Thanks!

**Comment by ManuelDeLeon** [comment]
Looks like children isn't reactive. It's a plain array. Use a ReactiveArray
and it should work.

**Comment by santiagopuentep** [comment]
children comes from the server, it's saved in a mongo collection. What I don't understand is how to have my template react to changes to that children array, making it fetch the actual data.

**Comment by ManuelDeLeon** [comment]
Then it's easier, instead of `var childrenIds = this.dataContext().children` do something like `var childrenIds = ChildrenCollection.find()`

The point is that if you want getChildren to be reactive then you need to use a reactive source, not a plain array.

**Comment by santiagopuentep** [comment]
Manuel, I did this change in the implementation and this worked correctly, but I wanted to get back to you when this was tested and I found a problem with this approach. Using:

    return Items.find({_id: {$in: ["itemId0", "itemId1", "itemId2"]}})

works great with the reactivity, but MongoDB doesn't return the results in order and there's no way to ensure that unless I do it manually, which gets me back at the inicial problem.

What I don't understand is why in blaze the reactivity works even if I don't return a reactive data structure. The autorun usually seems to know that there is a reactive object inside the function call. Is this correct?

**Comment by ManuelDeLeon** [comment]
> but MongoDB doesn't return the results in order

If I understand correctly just use the option `{ sort: { sortField: 1 } }`

> What I don't understand is why in blaze the reactivity works even if I don't return a reactive data structure.

A function is reactive as long as it uses a reactive source, it doesn't matter what it returns. For example `function() { var a = getReactiveVal(); return true; }` is reactive even though it returns a constant. When placed in a reactive context (e.g. a blaze helper), that function will rerun when `getReactiveVal()` changes.

**Comment by santiagopuentep** [comment]
Sorting like that doesn't work because the order I want is the one that goes in the array of Id's I'm passing to find() and not the order in the database. It seems to be a bug/missing feature in Mongo from what I found in the forums.

I was able to solve it with the help of the explanation you gave me for reactivity so I replaced my for loop with Items.findOne() with a for loop using find().fetch()[0]. It's a function that returns a reactive object so now it works!

Thanks a lot for the help! By far the fastest answers I got for an issue, anywhere.

The final function is:

    getChildren: function () {
        var result = [];
    
        var childrenIds = this.getChildrenIds();
    
        var total = childrenIds.length;
        for (var i = 0; i < total; i++) {
            var child = ItemsList.find(childrenIds[i]).fetch()[0];
            if (child) {
                result.push(child);
            }
        }

        return result;
    }

**Comment by santiagopuentep** [comment]
Manu, I was able to fix the reactivity part but I'm having problems with focus on the items. That getChildren function that returns an array of items from mongo creates item viewmodel/templates for each one.

Starting viewmodel/template setup:

    List
        Item0
        Item1
        Item2 (in focus)

Press up arrow:

    List
        Item0
        Item2 (should be in focus but loses it)
        Item1

What I'm trying to do is to have one of those items with keyboard focus and by pressing the up arrow move that item up one position in the childrenIds array of it's parent (in mongo). This triggers reactivity and moves the item template up in the list but since there's no callback or anything that lets me know when it's re-rendered I can't put it back in focus.

onRendered doesn't work because the item view is not destroyed, so it won't get called in the new version of the item.
Tracker.afterFlush with a focus() call to the item doesn't work either because the item loses focus after the flush.

The getChildren helper is called twice when I move the item up and only once when I move the item down. Moving it down keeps the focus in the item, moving it up doesn't.

Is there anything in viewmodel to help me fix this? I can't find a solution!

Thanks!

**Comment by ManuelDeLeon** [comment]
What kind of list are we talking about, a select element?

**Comment by santiagopuentep** [comment]
They are contenteditable divs:

    <div class="itemContainer">
        {{#each getChildren}}
            {{> item}}
        {{/each}}
    </div>

    <template name="item">
        <div class="item">
            <div class="textArea" contenteditable="true"></div>
        </div>
    </template>

**Comment by ManuelDeLeon** [comment]
Keep the active/selected item id in a property of the view model for itemContainer (the parent of the "item" view model). Use an autorun on the item template or view model that references getChildren. When getChildren changes you focus the textArea if the item's id matches the active/selected item id of the parent.

**Comment by santiagopuentep** [comment]
Thanks manu. I was thinking about your solution but the problem and I think it would also not work.

getChildren() gets called after mongo changes due to an autorun. Blaze/viewmodel renders the items and after that I'm getting a blur event on the item that moved up. If I do a tracker afterflush inside getChildre() the blur event still get's called after the flush. I don't undestand why, I thought that the afterFlush would work because it should be called after the render, but it seems it's not.

What I think I would need is a way of listening when the item's render ends to focus it after that, but I don't see a way to do it. And it would also be great to solve this because it's something that would be needed in many projects and different situations.

**Comment by santiagopuentep** [comment]
I was able to solve this problem using _uihooks.

http://www.webtempest.com/meteorjs-animation
https://github.com/tmeasday/transition-helper/blob/master/transition-helper.js

With that I have control over the movement, addition and removal of any element. Great and very needed addition to Blaze!

**Comment by ManuelDeLeon** [comment]
Actually, I'm very close to releasing a new version that takes care of it
by putting Meteor's onRendered functions on the animation frame instead of
the normal javascript cycle.

**Comment by ManuelDeLeon** [comment]
Update to 1.7.9

**Comment by santiagopuentep** [comment]
Great, that solved a flicker problem I was having when rapidly changing the state of an element that updates through reactivity.

I still need to use _uihooks to access to the removal/addition/movement of elements that update after a change in a model in Blaze. But it's a pretty good solution to use until the next upgrade.

Please let me know if you need any help with this project.
