### ISSUE TITLE
Compliment - Not Issue

### ISSUE THREAD

**Issue by franzsilva** [ManuelDeLeon/viewmodel#65]
I just wanted to say your library is awesooooome, i strongly suggent that this library be part as the core of the blaze engine. and integrate it as part of meteor, this is the only thing it needs, 

Great Work Manuel
P.S. Sorry for creating this as an issue, but you need the compliment. 

Regards,
Franz

**Comment by ManuelDeLeon** [comment]
Oh man, thank you. I needed that today =)

**Comment by sveinburne** [comment]
+1!

**Comment by santiagopuentep** [comment]
+1 here too!

**Comment by ManuelDeLeon** [comment]
As a "thank you for your thank you" I just updated the documentation with testing:

http://viewmodel.meteor.com/#testCodeBk
http://viewmodel.meteor.com/#testBindingsBk

I also added a link to this non-trivial sample app I've been working on:

https://github.com/ManuelDeLeon/phonebook
