### ISSUE TITLE
Issue with nested viewmodels

### ISSUE THREAD

**Issue by sveinburne** [ManuelDeLeon/viewmodel#66]
I have an issue with nested viewmodels. The issue seems to occur at random times (from my point of view). `binds.coffee`, line 47 complains that `role`  is not found on viwmodel. But the printed viewmodel is the parent... the data binding I'm using is `checked:role` for a radio button. If I add the `role` property to blaze (by passing `'role'` as a second argument to the `viewmodel` function), it does print it within a `{{role}}`. 
One more element that might help is that the nested template is included multiple times within a `{{#each}}` loop, and **only the second to the last elements in the loop trigger this console output**. So perhaps it has to do with multiple occurrences of the same viewmodel in the same page? 
Last clue : the issue appears only when I refresh the page. If I navigate with the router inside my application, and go back to the problematic page, the issue does not appear again.
Lastly, if I print the `role`  value assigned during viewmodel construction, it does prints as expected. Any idea?

**Comment by ManuelDeLeon** [comment]
Post the templates, I think you might be using bindings in a loop.

**Comment by sveinburne** [comment]
Ok! I'll write only the relevant pieces. 

    <template name="newProjectForm">
        <form data-abide="ajax" id="newProjectForm">
               {{> projectMembers autosave=false}}
        </form>
    <template>

    <template name="projectMembers">
        <fieldset>
            <legend>Membres</legend>
            <div class="row collapse prefix-radius">

                <table style="width:100%;">
                    <thead>
                    <tr>
                        <th>CIP</th>
                        <th>responsable</th>
                        <th>associé</th>
                        <th>non intégré</th>
                    </tr>
                    </thead>
                    <tbody>
                    {{#each users }}
                        {{> projectMember member=this autosv=../autosave}}
                    {{/each}}
                    </tbody>
                </table>
            </div>
        </fieldset>
    </template>

    <template name="projectMember">
        <tr {{autosave}}>
            <td>{{member.username}}</td>
            <td >
                <div class="switch tiny round">
                    <input id="is{{member.username}}Responsible" data-bind="checked:role"         value="responsible" type="radio" name="{{member.username}}responsability">
                    <label for="is{{member.username}}Responsible"></label>
                </div>
            </td>
            <td>
                <div class="switch tiny round">
                    <input id="is{{member.username}}Associated" data-bind="checked:role"     value="associated" type="radio" name="{{member.username}}responsability">
                    <label for="is{{member.username}}Associated"></label>
                </div>
            </td>
            <td>
                <div class="switch tiny round">
                    <input id="is{{member.username}}Out" data-bind="checked:role" value="none" type="radio" name="{{member.username}}responsability">
                    <label for="is{{member.username}}Out"></label>
                </div>
            </td>
        </tr>
    </template>


And the javascript counterpart :

    var ProjectMemberDefault=function(params){
       var member=params.member;
       var autosave=params.autosv;
       var project=Utils.currentProject.get;
       var role='none';
       var userid=member._id;
       var firstRun=true;
       if(project()){
           fetchedRole = project().members[userid];
           if(fetchedRole) {
               role=fetchedRole;
           }
       }
       return {
           role:role,
           userid:userid,
           autorunRole:function(role){
               var role=role();
               if(firstRun){
                   firstRun=false;
               } else{
                   Meteor.call("updateUserRoleInProject",project()._id,userid,role);
                   if(role=='none'){
                       Alerts.new({
                           severity:"info",
                           message:member.username+" a bien été retiré du projet "+project().acronym,
                           vanishes:3200
                       });
                   } else {
                       Alerts.new({
                           severity:"info",
                           message:member.username+" s'est vu confié le rôle "+role+" dans le projet "+project().acronym,
                           vanishes:3200
                       });
                   }
               }        
           },
           blaze_helpers:{
               autosave:function(){
                   if(autosave) return {"data-bind":"autorun:role"};
                   else return "";
               }
           }
       }
    };

    Template.projectMember.onCreated(function(){
        this.subscribe('projects');
        this.subscribe('users');
    });

    Template.projectMember.viewmodel(ProjectMemberDefault,'role');



    ViewModel.addBind('autorun',function(params){
        var autorunFunction=params.vm["autorun"+params.property.capitalize()];
        if(autorunFunction){
            params.autorun(function(){
                autorunFunction(params.vm[params.property]);
            });
        }
    });

    Template.newProjectForm.viewmodel(function(project){
        Utils.currentProject.set(project);
        var localPrj=project;
        return {
            acronym:project?project.acronym:"",
            fullName:project?project.fullName:"",
            validator:project?"":"projectExists",
            blaze_events:{
                "valid #newProjectForm":function(){
                    var prj=Utils.currentProject.get();
                    var members=ViewModel.byTemplate('projectMember');
                    var doc={
                        acronym:Template.instance().viewmodel.acronym(),
                        fullName:Template.instance().viewmodel.fullName(),
                        members:TemplateCommons.filterMembers(members)
                    };
                    if(!prj){
                        Projects.insert( doc);
                        $('#newProject').foundation('reveal', 'close');
                        $('#newProjectForm').trigger('reset');
                        Alerts.new({
                            severity:"success",
                            message:"Projet créé avec succès!",
                            vanishes:1800
                        });
                    } else {
                        Projects.update({_id:prj._id},{$set:doc});
                        Router.go("/administration/projects");
                        Alerts.new({
                            severity:"success",
                            message:"Projet mis à jour avec succès!",
                            vanishes:1800
                        });
                    }
                }
            }
        }
    });

**Comment by ManuelDeLeon** [comment]
I'm sorry but I can't help you there. It's way too much code to review. Here are my thoughts from glancing at it:
* You're mixing too much Blaze and ViewModel together. You can probably get it done without blaze helpers or events.
* You're closing over your variables. For example you define userId then create a vm with a userId property and then use "userId" inside a function.
* That autorun is very clunky to say the least. You can probably do without it. At the very least replace it with the built in 'change' bind or 'autorun' on the viewmodel. For example:
```
Template.name.viewmodel({
  name: '',
  autorun: function() {
    if (this.name()) console.log(this.name());
  }
})
```
I hope this helps.

**Comment by sveinburne** [comment]
Well, there are reasons for all the points you underlined. The change binding won't work with a 3 states, 3 buttons toggle bound to the same variable, or at least I didn't manage to. The only event I'm listening on is triggered by the zurb foundation abide lib, which helps me validate the form. The autorun function is quite easy to understand : if you bind with `autorun: role`, it'll check for a parameter called `autorunRole` and autorun the function. I didn't understand the issue with `userid` however...
Anyway, I'll try to find a smaller version of this bug ; thanks though.
