### ISSUE TITLE
Is there a way to repeat HTML elements, like <li> ?

### ISSUE THREAD

**Issue by deanius** [ManuelDeLeon/viewmodel#67]
I feel like I had to write a `players` helper to do the following, is there any way I could leverage a viewmodel property to repeat each `li`, much like Knockout or Angular ?

```
  <ol>
  {{#each players}}
    <li class="{{#if answered}}playerHasAnswered{{/if}}">{{name}} </li>
  {{/each}}
  </ol>
```

**Comment by ManuelDeLeon** [comment]
Blaze doesn't give a way of detecting changes in #if and #each blocks =(
My personal preference is to just use sub-templates for those situations. So in your case I would have:
```
<template name="players">
  <ol>
  {{#each players}}
    {{> player}}
  {{/each}}
  </ol>
</template>
```
```
<template name="player">
  <li data-bind="text: name, class: { answered: playerHasAnswered }"></li>
</template>
```
I think it's cleaner.

**Comment by deanius** [comment]
Thanks again.
