### ISSUE TITLE
Does this work anymore?

### ISSUE THREAD

**Issue by cyllu2** [ManuelDeLeon/viewmodel#68]
Is this package deprecated? It doesn't seem to work at all and I'm only using the example code.

**Comment by ManuelDeLeon** [comment]
Yes it works and it's maintained. Please make a repro.

**Comment by cyllu2** [comment]
I think the problem is that I tried using it inside a {{#with}} block, which I suppose doesn't work?

**Comment by ManuelDeLeon** [comment]
It depends on what you're trying to do.
