### ISSUE TITLE
Viewmodel seems slow, how to make it faster?

### ISSUE THREAD

**Issue by satyavh** [ManuelDeLeon/viewmodel#69]
I've noticed that Viewmodel initialisation is slow. For example, I have this template (abbreviated):

```
template(name="login")
      form#login-form
        .alert.alert-danger(data-bind="text: message, if: hasError")   
```

And this viewmodel (abbreviated)

```
Template.login.viewmodel
  email: ''
  password: ''
  hasError: false
  message: ''
  emailValid: ->
    return false if @email().length is 0
    true
  passwordValid: ->
    return false if @password().length is 0
    true  
  allValid: ->
    @emailValid() and @passwordValid()
  emailVerified: ->
    return true if Session.get('email-verified')?
    false  

etc etc etc 
```

Now what happens when I load the route, the UI briefly shows `.alert.alert-danger(data-bind="text: message, if: hasError")` before Viewmodel gets initialised and evaluated completely, and kicks in. Resulting in annoying flickering of DOM elements.

I'm showing an abbreviated version of my template / viewmodel, but what I found out is that the more functionality you put in your viewmodel, the slower it initialises, the longer UI elements show that should not be visible in the first place.

And this makes Viewmodel not a very good option for dynamically showing/hiding DOM elements. Or, you really have to reverse your coding logic or something like that.

So how to make it faster?

**Comment by ManuelDeLeon** [comment]
That's not because of ViewModel but the way Meteor works. See http://viewmodelboard.meteor.com/comments/QSXnRJXqRtLsdsAzb
