### ISSUE TITLE
Button Inside Template Handler Block not Firing

### ISSUE THREAD

**Issue by dmarkrollins** [ManuelDeLeon/viewmodel#70]
First - view model is really great... thanks.

I have a button inside a view model handler function on my template.

2 things do not seem to work for me.

1) the button click event in the view model never fires - but when I move the button outside the hasMorePlayers block in the template it does fire.

2) When i do move the button outside the hasMorePlayers block so that the click event fires, the Template.instance() is null inside the viewmodel btnMorePlayers function.

```
    {{#if hasMorePlayers}}
      <button data-bind="click: btnMorePlayers" class="waves-effect waves-light btn" >Load More</button>
    {{/if}}
```

My handler looks like this
```
Template.bindtest.helpers({
  hasMorePlayers: function(){
    //return false;
    return Players.find().count() >= Template.instance.limit.get();
  }
});
```

My view model looks like this:

```
Template.bindtest.viewmodel(
'bindtestdata',
{
  first: '',
  last: '',
  score: '',
  greeting: function() {
    return "Hello " + this.first() + " " + this.last();
  },
  canEnter: function() {
    return !!this.first() && !!this.last();
  },
  showError: false,
  errorText: function() {
    if (this.canEnter() || !this.showError()) {
      return '';
    }
    return "Please enter your first and last name";
  },
  showList: function(){
    // show a list of stuff
    if(this.canEnter()){
      $('#listDiv').toggleClass("hide");
    }
  },
  playeritem: function() {
    return Players.find({}, {limit: Template.instance().loaded.get()});
  },
  btnMorePlayers: function(){
    alert('hi there');
    var limit = Template.instance().limit.get();
    if(!limit || isNaN(limit)){
      limit = 2;
    }
    limit += 2;
    Template.instance().limit.set(limit);
  }
},'playeritem');
```

**Comment by ManuelDeLeon** [comment]
That's normal. The 'if' block is empty by the time the view model is bound to the elements on screen so there's nothing to bind. Then Blaze inserts the button and it stays unbound (Meteor doesn't provide a way to know if an 'if' block has changed). Either use the if/visible bind instead of the Blaze 'if' block, or put the button inside a template and put `{{> templateWithButton }}` inside the 'if' block.

I'll put this in the faq

**Comment by ManuelDeLeon** [comment]
Updated the (newly created) FAQ: http://viewmodelboard.meteor.com/posts/rrpagb6DnciFQde8J
