### ISSUE TITLE
ViewModel and Iron Router problems

### ISSUE THREAD

**Issue by santiagopuentep** [ManuelDeLeon/viewmodel#71]
Are there known incompatibility issues with iron:router? I'm having errors everywhere using it with viewmodel.

**Comment by ManuelDeLeon** [comment]
I use it all the time with IR...

**Comment by santiagopuentep** [comment]
Here's an example of one of the problems.

If I comment the #if statement in the template the back button is visible. If I uncomment it it's not. Very strange. The onBackClick handler doesn't work, but in certain cases (with the more complex app) it does, sometimes it doesn't. All these problems started with iron router installed.

This is the code:

I have this template:

    <template name="desk">
        // comment this #if and the data-bind stops/starts working
    	{{#if currentUser}}
		    <a href="" data-bind="visible: isNotInRoot, click: onBackClick">back</a>
	    {{/if}}
    </template>

With this viewmodel:

    Template['desk'].viewmodel(
	    function (data) {
		    return {
		    	isNotInRoot: false,
	    		onBackClick: function (e) {
	    			e.preventDefault();
	    			console.log('back clicked!');
    			}
    		}
    	},
    	['root']
    );

And this router:

    Router.configure({
	    layoutTemplate: 'layout',
	    waitOn: function () {
	        	Meteor.subscribe('items');
	    }
    });

    Router.route('item', function () {
    		this.render('desk');
    	},
    	{
    		path: '/:_id',
    	}
    );

**Comment by ManuelDeLeon** [comment]
Check out the faq on the board site...

**Comment by santiagopuentep** [comment]
Sorry, board site?

**Comment by santiagopuentep** [comment]
Found it: http://viewmodelboard.meteor.com/posts/rrpagb6DnciFQde8J

Thanks! Problem one fixed.

**Comment by santiagopuentep** [comment]
I'm still having problems with this. I was using IronRouter and I changed to FlowRouter but the problem is the same, one part of my template is in a #with statement that renders an item template and doesn't get re-rendered when the data context changes (root helper). This is the code:

```
<template name="desk">
	<a href="" data-bind="click: onBackClick">back</a>
	<div class="desk">
		{{#with root}}
			{{> item}}
		{{/with}}
	</div>
</template>
```

```
Template['desk'].viewmodel(
	function (data) {
		return {
			root: function() {
				var item;
				
				var itemId = FlowRouter.getParam("_id");
				if (itemId) {
					item = ItemsList.findOne(itemId);
				}
				
				return item;
			},
			onBackClick: function (e) {
				e.preventDefault();
				
				var itemId = FlowRouter.getParam("_id");;
				
				if (itemId) {
					// finds an id to other item (the parent of the current one)
					var parent = ItemsList.findOne({children: itemId});
				}
				
				if (parent) {
					FlowRouter.go('/' + parent._id);
				} else {
					FlowRouter.go('/');
				}
			}
		}
	},
	['root']
);
```

```
FlowRouter.route('/', {
	subscriptions: function (params, queryparams) {
		this.register('items', Meteor.subscribe('items'));
	},
	action: function (params, queryparams) {
		FlowLayout.render('layout');
	}
});

FlowRouter.route('/:_id', {
	subscriptions: function (params, queryParams) {
		this.register('items', Meteor.subscribe('items'));
	},
	action: function (params, queryParams) {
		FlowLayout.render('layout');
	}
});
```

When I press the back button FlowRouter.go() is called, the root helper is called but the template inside the #with statement doesn't change.
