### ISSUE TITLE
Viewmodel 

### ISSUE THREAD

**Issue by satyavh** [ManuelDeLeon/viewmodel#73]
Also posted / discussed this on viewmodel board (http://viewmodelboard.meteor.com/posts/crdZH5SsrMKbJ8ScC/meteor-user-is-undefined-empty-or-not-reactively-updated), but I feel this is an issue for a very common use-case. Plus the solutions offered in the discussion A) do not work, or B) are not very viewmodel-like.

The use-case is:

1. There is a form with input fields
2 Use Viewmodel to populate the input fields with data from database (value binding)
3. Enable the user to change the values
4. Instantly validate the values using 2-way binding
5. Call a method (preferably) to write the final values to the database.

I've made a repository here showing the different use-cases and issues.

https://github.com/satyavh/viewmodel-populate-db

Non acceptable solutions are:
1) using delay binding, because you can never know how much to delay.
2) do database updates in client, because it's just way more secure to use methods (if you disagree, please check out the Allow/Deny challenge).

Best solution would be if Viewmodel values update reactively, like Viewmodel functions. Example:

```
user: Meteor.user().profile.name
```
doesn't reactively update, hence returns `undefined` because viewmodel initialises before db-call is ready.

```
user: ->
  Meteor.user().profile.name
```
reactively updates. Binds but can't be updated because it's a function

Lets aim for a Viewmodel-worthy solution!

**Comment by ManuelDeLeon** [comment]
You're being helped over at the board, opening two threads only makes it harder for me to keep track of things.
