### ISSUE TITLE
Data context

### ISSUE THREAD

**Issue by TomFreudenberg** [ManuelDeLeon/viewmodel#74]
Hi @ManuelDeLeon 

I am working on an example with Flow-Route, Flow-Layout, Auto-Form and Route based subscription and would like to integrate Viewmodel to that setup.

I miss to hand over correctly the data context when call the template and to access the context functions.

Sample template

````
<template name="updateBook">
  {{> updateBook_VM doc=my_doc }}
</template>

<template name="updateBook_VM">
  Title: <input type="text" data-bind="value: title"/>
  <br/>
  Author: <input type="text" data-bind="value: author"/>
  <br/>
  This works: {{doc.title}}
</template>
````

Sample js

````
Template.updateBook.onCreated(function() {
  this.data.my_doc = function() { return Books.findOne(); }
});

Template.updateBook_VM.viewmodel(function(data) {
  return {
    title: data.doc.title, 
    author: data.doc.author
  }
});
````

This does not work. When inspecting at viewmodel, the context var `data` has one element `doc`but it is `undefined`

Any idea, what my mistake is?

Thanks
Tom

**Comment by TomFreudenberg** [comment]
UPDATE: My first posting you may have got via mail is outdated. The problems with overall data context I had there, depends on Autoform in parallel. 

So situation/question is as described above.

**Comment by ManuelDeLeon** [comment]
I'm not on a computer right now so I can't give you the fixed code until
later tonight.

You just have to create a helper method that is used as parameter (with the
data) for the template when you call it.

**Comment by TomFreudenberg** [comment]
Hopefully I did understand you correct - but this won't either not work

````
Template.updateBook.helpers({
  get_my_doc: function() {
    return Template.instance().data.my_doc;
  }
});
````

So using that  

<template name="updateBook">
  {{> updateBook_VM doc=get_the_doc }}
</template>

will also just give an `Undefined` as value from `data.doc` in the viewmodel.

Any ideas left?

Otherwise I will wait until you find the time tonight.

Thanks Manuel

Tom

**Comment by ManuelDeLeon** [comment]
The data probably isn't ready. Either wait for the data to be ready (the
viewmodel constructor is getting a non reactive object), or pass a function
that returns the result of the query call (instead of the non reactive
object), or move the dB call to the sub template.

**Comment by TomFreudenberg** [comment]
Hi Manuel, the data must be already `ready`.

If I just use

````
{{#with my_doc}}
  {{> updateBook_VM }}
{{/with}}
````

I get the field values to data and be able to access with

`data.title`

In my point of view it seems to be a problem when I set a context for the (sub) template.

**Comment by ManuelDeLeon** [comment]
Not necessarily, read this comment: https://github.com/ManuelDeLeon/viewmodel/issues/46#issuecomment-101414012

**Comment by ManuelDeLeon** [comment]
Option #1 
```
Template.updateBook.viewmodel({
  doc: function() {
    return Books.findOne();
  }
});
Template.updateBook_VM.viewmodel({
  title: function(){
    var doc = this.parent().doc();
    return doc && doc.title;
  },
  author: function(){
    var doc = this.parent().doc();
    return doc && doc.author;
  }
});
```
```
<template name="updateBook">
  {{> updateBook_VM  }}
</template>

<template name="updateBook_VM">
  Title: <input type="text" data-bind="value: title"/>
  <br/>
  Author: <input type="text" data-bind="value: author"/>
</template>
```

**Comment by ManuelDeLeon** [comment]
Option 2
```
Template.updateBook_VM.viewmodel({
  doc: function() {
    return Books.findOne();
  },
  title: function(){
    var doc = this.doc();
    return doc && doc.title;
  },
  author: function(){
    var doc = this.doc();
    return doc && doc.author;
  }
});
```
```
<template name="updateBook">
  {{> updateBook_VM  }}
</template>

<template name="updateBook_VM">
  Title: <input type="text" data-bind="value: title"/>
  <br/>
  Author: <input type="text" data-bind="value: author"/>
</template>
```

**Comment by ManuelDeLeon** [comment]
Option 3
```
Template.updateBook.viewmodel({
  data: {
    doc: function () {
      return Books.findOne();
    }
  }
}, 'data');

Template.updateBook_VM.viewmodel(
  function(data) {
    return data;
  },
  {
    title: function(){
      var doc = this.doc();
      return doc && doc.title;
    },
    author: function(){
      var doc = this.doc();
      return doc && doc.author;
    }
  }
);
```
```
<template name="updateBook">
  {{> updateBook_VM  data}}
</template>

<template name="updateBook_VM">
  Title: <input type="text" data-bind="value: title"/>
  <br/>
  Author: <input type="text" data-bind="value: author"/>
</template>
```

**Comment by ManuelDeLeon** [comment]
You get the idea...

**Comment by TomFreudenberg** [comment]
Hi Manuel, thanks for your time and effort. That kind of options (1+2) I had already got out from documentation but option 3 is new kind.

Let me try to explain what I am struggling with: If I have to write all the dependencies, fields and cursors inside that one and only `Template.foo.viewmodel` it feels a bit hacky. So this time I have to throw away all existing structures (we defined for us) and move everything inside the viewmodel.

In case of no experiences with your package we can currently not decide if this ok or bring us into trouble. Hopefully you can understand the emotional feeling when changing technologies.

I do not like to grab into the parent context nor multiply the selection of data through sub templates. 

Mostly option 3 comes near to what we would prefer as abstraction between sub-templates and data but with that I have no access inside some elements without data binding. If I do it like written in option 3, how can I e.g. loop through the data like:

````
{{#each doc}}
  ...

````

when the doc function is placed inside `Template.updateBook.viewmodel` 

---

My question is still: why can't I send my wished data context via the template call

`{{> sub foo=bar doc=whatever }}`

Is this a technical restriction on viewmodel or something not wished by design? 


Maybe I am totally wrong in my head and did not get how to use viewmodel, so in any case I am sorry for that.

Tom

**Comment by TomFreudenberg** [comment]
Hi Manuel, I got my answer from reading your documentation `.addHelper` for the `{{#each doc}}` question. ;-)

So, I guess it still is an emotional decision (like going to unknown countries) to switch over to viewmodel

**Comment by TomFreudenberg** [comment]
Hi Manuel,

after testing again things might get clearer

Is it correct, that when using with viewmodel:

`{{> updateBook_VM my_doc=my_data}}`

the function my_data has to be defined inside `Template.updateBook.viewmodel` 

and at least has to be exported as Template helper.

Correct?

**Comment by TomFreudenberg** [comment]
Hopefully one of my last question to understand

This works (again it is just to understand how it works):

````
{{> updateBook_VM my_doc=my_data}}

Template.updateBook.viewmodel({
  my_data: { 
    doc: function() {
      return Books.findOne();
    }
  }
}, 'my_data');

Template.updateBook_VM.viewmodel(
  function(data) {
    return { data: data.my_doc };
  },
  {
    title: function() { 
      var doc = this.data().doc();
      return doc && doc.title 
  }
);
````

But this does not work

````
{{> updateBook_VM my_doc=my_data}}

Template.updateBook.viewmodel({
  my_data: { function() {
    return Books.findOne();
  }
}, 'my_data');

Template.updateBook_VM.viewmodel(
  function(data) {
    return { data: data.my_doc };
  },
  {
    title: function() { 
      var doc = this.data();
      return doc && doc.title 
  }
);
````

So, isn't it possible to directly return the function, without returning an doc envelope object from `Template.updateBook.viewModel`?

**Comment by ManuelDeLeon** [comment]
All of this has more to do with how Meteor and JavaScript work than ViewModel (ViewModel is almost a casualty in this mess)

Okay, let's start:

> Why can't I send my wished data context via the template call `{{> sub foo=bar doc=whatever }}`

You can access those parameters when you create the view model:

```
Template.A.viewmodel(function(data) {
  // data.foo === bar (at the moment the template is created)
  // data.doc === whatever (at the moment the template is created)
})
```

The problem is that foo and doc are passed as non reactive values. If the data for bar isn't available/ready by the time sub is created then they will be undefined and stay that way. It works with a blaze (`{{ foo }}`) because blaze is kinda cheating: when bar changes, blaze knows sub uses it for `{{ foo }}` and updates it accordingly (that happens on the template side). On the code side (so to speak) the onCreated hook receives a non-reactive/static object `{ foo: bar, doc: whatever }`, so unless it's a function, the values are fixed.

> Why does the first example works but the second one doesn't?

On the second example `my_data` returns a non-reactive object (the mongo document), so when `title` calls `this.data()`, that function doesn't hit `Books.findOne()`, it has the object and thus isn't reactive. In other words, you're not passing a function that returns the result of `Books.findOne()`, you're passing the actual object (non-reactive) so `title` doesn't have any reason to change.

On the first example you are not calling `Books.findOne()` until `title` is invoked, that makes `title` reactive because `Books.findOne()` is reactive.

> What do you do?

You have plenty of choices but all revolve around coping with the fact that the sub template isn't going to have the data it needs at the time it's created.

In your case I would do one of the following:

### Option 1 

```
Template.sub.viewmodel({
  autorun: function() {
	this.extend(Books.findOne());
  }
})
```

This will automatically add all the properties of the book when they're available. The only downside is that the properties are not there until the subscription is ready. That means that it is possible for `vm/this.title()` to return function undefined.

### Option 2

```
Template.sub.viewmodel({
  author: '',
  title: '',
  autorun: function() {
	this.extend(Books.findOne());
  }
})
```

Same as 1 but it fixes the problem of properties not being available until the data is ready. The downside is that you have to create all properties (instead of letting .extend do it for you).

### Option 3

(assuming you'll pass an object that has the book id)

```
Template.sub.viewmodel(
  function(data) {
	return {
	 _id: data._id
	};
  },
  {
    autorun: function() {
	  this.extend(Books.findOne({ _id: this._id() }));
    }
  }
)
```

You can combine this with option 2

### Option 4

(assuming the parent view model is the one that knows how to call `Books.findOne()`)

```
{{> updateBook_VM my_doc=my_data}}

Template.updateBook.viewmodel({
  my_data: { 
    doc: function() {
      return Books.findOne();
    }
  }
}, 'my_data');

Template.updateBook_VM.viewmodel(
  function(data) {
    return { data: data.my_doc };
  },
  {
    autorun: function() { 
      this.extend(this.data().doc());
  }
);
```

And of course you can mix and match

**Comment by TomFreudenberg** [comment]
:-) thanks for your explains !!!

Just for my understanding: You have made the `autorun` dep just to not have to declare all fields from dataset/collection document?

Is it otherwise also still valid to use `title: function() { var doc = ... }` outside the autorun dep?

**Comment by ManuelDeLeon** [comment]
Yeah, the following two are pretty much equivalent:

```
Template.sub.viewmodel({
  title: '',
  autorun: function() {
    this.extend(Books.findOne());
  }
})
```

```
Template.sub.viewmodel({
  doc: function() {
    return Books.findOne();
  },
  title: function(){
    var doc = this.doc();
    return doc && doc.title;
  }
});
```

The only difference is that the first view model will let you change the title (in the view model, not the DB) and the second one won't (it always returns the title from the DB).

**Comment by TomFreudenberg** [comment]
I see, so you would suggest the `autorun` "version"

Thanks Manuel, I hope you will not become exasperated with me ;-)

**Comment by ManuelDeLeon** [comment]
Don't worry, I get a lot from these conversations =)
