### ISSUE TITLE
viewmodelboard down?

### ISSUE THREAD

**Issue by wesyah234** [ManuelDeLeon/viewmodel#75]
viewmodelboard.meteor.com is not loading.. 

http://www.webpagetest.org/result/150707_GJ_VZD/

**Comment by ManuelDeLeon** [comment]
Not exactly, it's just hosted on *.meteor.com which is very buggy =(

(can't complain too much since it's free)

I'll move it somewhere else when I have time.

**Comment by ManuelDeLeon** [comment]
btw, it's up now.

**Comment by wesyah234** [comment]
thx!
