### ISSUE TITLE
Getting data out of embedded arrays

### ISSUE THREAD

**Issue by cheesington** [ManuelDeLeon/viewmodel#76]
I've been trying to figure out how to create a form that will gather data for a document that contains an embedded array. The fact that a viewmodel can't bind to things inside an ```{{#each }}``` block means that sub-viewmodels need to be used, and I can populate their fields with data from the document; what I can't figure out how to do is to get the data back out so as to update the document with any changes that have been made.  Is there a recommended way to do this?

For what it's worth, I've coded up a small example of what I'm trying to do here:
https://github.com/cheesington/viewmodel-embedded-array/tree/master

**Comment by ManuelDeLeon** [comment]
That example is superb.

It's a requirement so simple there has to be an easy way to do it. If not I have to update ViewModel to deal with this scenario somehow.

Unfortunately I can't work on it right now. I may be able to work on it tonight, but I have to record a screen cast so I may not have the time today.

/sorry

**Comment by cheesington** [comment]
Oh good, I'm glad it was clear enough to illustrate the problem.  Thanks for having a look at it!

**Comment by ManuelDeLeon** [comment]
The biggest problem I have is updating the Mongo document. Let's say you
have the correct list of authors for a book. How are you going to update
the authors array? Are you going to replace the whole array? Try to update
the entries that changed? How?

If I give you a viewmodel.children() method then getting the array of
authors is trivially easy. You just loop on the children and push the
author objects (vmAuthor.toJS()) to an array.

I'll work on the.children() method and you work on how you'll update the
document's array.

**Comment by cheesington** [comment]
Oh hey, I was just thinking about the children() method, and wondering what would happen if my Book document eventually needed a list of Editors, too.  I'd need some sort of way to tell which array each child was from, and -- wait a minute, there's already a mechanism for that:

>```ViewModel.byTemplate( templateName )```
Returns an array with all the view models associated with a particular template. Returns undefined if the template doesn't exist or there isn't a view model loaded for that template.

So even without the children() method, if I name my child viewmodels uniquely I can get that array when it comes time to update the document.  Am I thinking about this correctly?

**Comment by ManuelDeLeon** [comment]
You're right, you can use .byTemplate or .byId but you'll need some way to distinguish authors from one book and another. This is why .children() is so much cleaner =)

Here's how you do it with .byId giving each author a unique global id:

First add an id to the authors:
```
Books.insert({
    name: "Rocking Out Vol 1",
    authors: [{
        id: 1, // No other author can have this id (on this or any other book)
        firstName: "Alice",
        lastName: "Cooper",
    },
    {
        id: 2,
        firstName: "Elton",
        lastName: "John",
    }]
});
```

The templates stay the same.

Books view model stays the same:
```
Template.Books.helpers({
    books: function() {
        return Books.find();
    },
});
```

On the Book view model, get rid of the autorun, it's not doing anything (unless you expect the data to change from underneath). Then get the authors on the save function.
```
Template.Book.viewmodel(
  function(data) { 
    return data; // Add all book properties
  },
  {
    save: function() {
      var authors = [];
      for(var i = 1, total = this.authors().length; i <= total; i++) {
        var author = ViewModel.byId("Author_" + i).toJS();
        authors.push(author);
      }
      // Save the updated authors array to the DB
    }
  },
  'authors'
);
```

Give each author's view model a name:
```
Template.Author.viewmodel(
  function(data) {
    return "Author_" + data.id; // Returns a string so it's used as vm name
  },
  function(data) {
    return data;
  }
);
```

You can also achieve the global uniqueness if you use the Book Id for the author's view model's name. That way the author's id can repeat on different books.

Again, you wouldn't have to do any of these gymnastics if there was a .children() function. You would leave your code as it is and get the array of authors like this:

```
var authors = this.children().map(function(author) { return author.toJS(); });
```

**Comment by ManuelDeLeon** [comment]
Okay, on a scale of 1 to embarrassing, this is humiliating...

View models already have a .children() method!

This is what happens when you don't update your own documentation =(

So in your case leave your code exactly as it is and just change the Book view model to:

```
Template.Book.viewmodel(
	function(data) {
		return data;
	},
	{
		save: function() {
			var authors = this.children().map(function(author) { return author.toJS(); });
			console.log(authors);
		}
	},
	'authors'
);
```

**Comment by cheesington** [comment]
Ha ha.  Well it's not a small package, and you seem like a busy person.  And having code already written seems like the nicest of problems to have.  :)

One issue with the ```children()``` solution that I've been trying to puzzle out is how to distinguish the elements of different arrays on the document.  For example, if Book were to eventually require a list of editors in addition to the authors, you'd need to do something like the following to make sure you were not accidentally getting editors in your list of authors:

```javascript
var authors = _.chain(this.children())
.filter(function(child) { return child.template === 'author'; })
.map(function(child) {return child.toJS();})
.value();
```
Except that, if I'm reading the source code right, the ```template``` property is external to the ```ViewModel ``` instance, and therefore inaccessible.  

There may be another way, though.  I'm working on getting the data in the toplevel view model to reactively update with changes in the child fields, using a bottom-up approach.  Pass the name of the array and the current index into the child viewmodel in its constructor, and it can call ```parent()['authors'][index].set(this.toJS())```.  Or something like that.  I'll have some time to work on it tonight, I think, and I can only guess at the syntax till then.

**Comment by ManuelDeLeon** [comment]
Yeah, if you add 'editors' to the mix then we're back to needing a way to distinguish one type of child from another. You can also add the type when you create the child view model. In the case of authors you can do:

```
Template.Author.viewmodel(
  function(data) {
    return data;
  },
  {
    type: function() {
      return 'author';
	}
  }
);
```

I used a function for the type so it doesn't show up when you call author.toJS().

**Comment by cheesington** [comment]
My experiment with having the parent viewmodel data update reactively as the fields in the children are manipulated was successful, but added complexity disproportionate to the convenience.  And really, the only reason to keep the parent viewmodel up to date reactively is if you're trying to update the db document on the fly too, and I think that can be done more easily and efficiently by just allowing the children to update the fields they're responsible for directly.  

For updating the document at submit time, I think that just iterating through the children as you outlined remains the best solution.
