### ISSUE TITLE
the 'value' binding seems to be causing double key strokes in input text boxes on ios devices

### ISSUE THREAD

**Issue by devinesoftware** [ManuelDeLeon/viewmodel#78]
When I deploy my meteor application to the ios simulator or my ios device, on input text fields where I have the text bound to the viewmodel via the 'value' binding, keystrokes from my keyboard(simulator) and from the ios keyboard render two characters. However, hitting the delete or backspace key only removes one of them.

Help Please!

Here is some sample code showing the issue:

https://github.com/devinesoftware/testBed

**Comment by ManuelDeLeon** [comment]
How do I run an ios simulator on Linux or Windows?

**Comment by devinesoftware** [comment]
You'll need to install X-Code. If you don't have a mac, you'll have to create a VM with OS X on it and install X-Code that way.

Once you have x-code installed, you'll need to run the following commands:

meteor add-platform ios
meteor run ios-device

The last command will package your meteor application up into a deployable bundle. it will then launch X-Code and from there you can run in the ios-simulator or run it on an ios device.

**Comment by ManuelDeLeon** [comment]
I'll take a look at it when I get in front of a computer. In the meantime,
is there any chance you can save me the time and make me a virtual box?

**Comment by devinesoftware** [comment]
Sure, but can you point me to an online resource where I can build you a mac OS-X VM image?

**Comment by ManuelDeLeon** [comment]
I don't know, you're the osx user =D

**Comment by devinesoftware** [comment]
Ha.

Thanks

**Comment by devinesoftware** [comment]
From my research (stackoverflow), you're not legally allowed to run OS X on anything other than apple hardware. I'm going to use knockout-client instead for my project. I hope you get this issue fixed because you've got a really great package here which fills a gigantic hole in the meteor framework. However, if it doesn't work on iOS, well that's going to make it a 'no-go' for many projects.

Good luck!

**Comment by ManuelDeLeon** [comment]
I'll look into it. Thanks for the heads up.

**Comment by PEM--** [comment]
I've narrowed it down in the release. It happened during the devs from the 1.8.2 to the 1.8.3.

For the moment, I've blocked the updates on the 1.8.2 (got some customers on iOS).

**Comment by devinesoftware** [comment]
Good deal man. Thanks for looking into it. I look forward to using it when you've got the issue resolved.

**Comment by ManuelDeLeon** [comment]
Ahh the joys of fixing something in ie and breaking it on Firefox, fixing
it for Firefox and breaking it for iPhone. All the while your tests running
just fine in Chrome.

Please test it on the input of vmtest.meteor.com (the textarea doesn't do
anything)

Thanks for your patience.

**Comment by ManuelDeLeon** [comment]
Please test version 1.8.9
I refactored the value binding and it should work on iPhone too

**Comment by PEM--** [comment]
I share your joy on an everyday basis :confused: 

The 1.8.9 fixes the issue :+1: Thanks for your reactivity (well on a package for reactivity, I was quite sure of it :smile: ).
