### ISSUE TITLE
Unwanted symbols appearing in value-bound text fields when using control keys

### ISSUE THREAD

**Issue by cheesington** [ManuelDeLeon/viewmodel#79]
I'm having some trouble with value bound fields.  Typing normally is fine, and backspacing through entered text is fine too.  However, when using the arrow keys, the Home/End keys, ctrl-shift-arrow keys, or delete key, their normal function doesn't work and a symbol is appended to the text field instead.  Left-arrow, for example, is ```%``` and right arrow is ```'```.  Also, backspacing in an empty field adds a character unrepresented by my font.  

This happens for me in Firefox with Windows 8; it seems to be fine in Chrome.  I can reproduce using the Books code from issue #76, updated to use Viewmodel 1.8.6:
https://github.com/cheesington/viewmodel-embedded-array

I've deployed that code to meteor.com here for easy checking:
http://colinf-books.meteor.com/

**Comment by ManuelDeLeon** [comment]
The problem is that you're using an OLD version. Update to 1.8.7 =p

**Comment by cheesington** [comment]
Lol!

Okay, 1.8.7 fixes all the strange symbol problems except for the one that's triggered when backspacing in an empty field.

**Comment by ManuelDeLeon** [comment]
Crap, I forgot that one. I already left the house. I'll fix it when I get
back.

**Comment by ManuelDeLeon** [comment]
I really can't help you if you insist on using old versions... use 1.8.8

**Comment by cheesington** [comment]
Great, thanks!  1.8.8 works like a champ.
