### ISSUE TITLE
Global viewmodel helper

### ISSUE THREAD

**Issue by dalgard** [ManuelDeLeon/viewmodel#81]
*(Thanks for this addition to Meteor! The first day after discovering this, I was flying :) I actually searched for "meteor viewmodel", because I thought there had to be some MVVM library for Meteor – and yours is even simpler and more powerful than what I thought I was looking for.)*

Can you tell me whether I'm working an anti-pattern here?

Inside sub-templates, I am able to write `data-bind` attributes and have them picked up by the closest overlying viewmodel – however, I can't use the viewmodel properties as Spacebars helpers without passing them through to the sub-template as named params.

Instead of doing that, I'm thinking of registering a global helper `vm` which returns the closest overlying viewmodel of the current template instance.

Is there a reason you haven't included such a helper in the library?

It would solve the need for even registering specific vm props as helpers – they could just be gotten through `{{vm.myProp}}`. The code is straight-forward (in this example using the `parent()` method from `aldeed:template-extension`, but that part could easily be copied):

```javascript
Template.registerHelper("vm", function () {
  var instance = Template.instance();

  do {
    if (instance.viewmodel)
      return instance.viewmodel;
  }
  while (instance = instance.parent());
});
```

**Comment by ManuelDeLeon** [comment]
I have to do a few tests but if it works the way I think it does then it's a great idea and I'll change the way I define helpers.

**Comment by ManuelDeLeon** [comment]
Now that I think of it, I'm questioning the wisdom of forcing you to
specify which properties are available as helper methods. I think I should
just add all properties as helper methods automatically and be done with
it. That way we don't need the global helper or specifying which properties
are helpers.

**Comment by ManuelDeLeon** [comment]
I may have misunderstood you. Can you post an example of how you use that helper?

**Comment by dalgard** [comment]
I think you understood me perfectly. And I agree with you, all properties should be registered as helpers by default – if developers *really* want to be able to distinguish between Blaze helpers and viewmodel properties, then choosing different names is a more than fair requirement.

That point being clear, we still face the problem of template helpers not being inherited by sub-templates without passing them as template param. This is the main reason for making my global `vm` helper returning the closest viewmodel, if it exists.

**Comment by ManuelDeLeon** [comment]
Now I get it. 

My initial reaction is that I don't think that's a good idea... being able to bind to properties which you don't know when/where/if they're created. I can imagine having a WTF moment after seeing `data-bind: "value: name"` and `name` nowhere to be found on the view model. 

As it stands, ViewModel almost forces you to create your application in small modular and independent components. That's makes the code easy to navigate and reason about. Allowing that kind of inheritance breaks all that.

I know I'm not giving you fact-based reasons (it's more of a feeling) but it has a strong smell. I may change my mind though.

btw, why do you want/need this? What is the scenario you have in mind?

**Comment by dalgard** [comment]
We're pretty much still talking about the `overview`/`filter` example from the other thread, which is the case that I'm trying ViewModel out on. I think it's a sensible scenario – the sub-template has internal view state but also produces some value that is read by the super-template. It applies to everything from individual form controls to pagination widgets and whole filter panels.

Smells are important. On the other hand, I submit that Angular has interaction between nested controllers all the time (don't get me wrong, there's a reason why I'm not simply using Angular).

The whole issue is how the data from the child template's viewmodel is best used within the parent's viewmodel.

Having the child write to the parent probably *is* sort of upside down. The reason why I'm thinking that way, I believe, is that putting `data-bind=` attributes inside sub-templates worked totally fine – up until the point where the sub-templates got its own viewmodel. Then the value went missing from the parent's viewmodel, and for a good reason.

For maximum stringency in developer's use of ViewModel, `data-bind=` attributes inside sub-templates probably shouldn't be parsed attributes at all. The only way of getting data out, then, would be one of the options discussed in the other thread:

https://github.com/ManuelDeLeon/viewmodel/issues/82

**Comment by dalgard** [comment]
Just to be clear, I still think adding all properties as helper methods automatically is a really good idea :+1:

**Comment by dalgard** [comment]
I would happily make a pull request that adds all properties as helper methods, but this kind of API change belongs to the next major version, and I'm not sure how you plan to handle the move to `2.0.0`.

**Comment by ManuelDeLeon** [comment]
> adds all properties as helper methods, but this kind of API change belongs to the next major version

Yeah, that feature is a v2 thing because it changes the way ViewModel works.

> The whole issue is how the data from the child template's viewmodel is best used within the parent's viewmodel.

There are many ways of dealing with this kind of situation and I'm very happy that ViewModel allows you to choose the one you're most comfortable with. For example, the way this is done in React is by passing a function to the child, the child then invokes the functions with whatever parameters it wants and the parent would then update its state.

The same can be done with ViewModel and it takes it one step further. Instead of passing a function that will only serve to update a property, you can pass the parent's property itself.

> I guess having the child write on the parent is sort of upside down.

The fancy term for it is "Inversion of Control".

> data-bind= attributes inside sub-templates probably shouldn't be parsed at all.

What do you mean?

**Comment by dalgard** [comment]
>> I guess having the child write on the parent is sort of upside down.

> The fancy term for it is "Inversion of Control".

I'm not sure I agree. Inversion of control – "don't call us, we'll call you" – is somewhat synonymous with dependency injection. Now, the child *ought to* be a unit in itself and be able to live without any inferred dependencies – whereas the parent always knows about it's children.

By my logic, this means that the child should never have to call the parent (which might not exist), the parent should call the child (which definitely exists).

---

>> data-bind= attributes inside sub-templates probably shouldn't be parsed at all.

> What do you mean?

You mentioned it yourself – inheritance breaks encapsulation. In the case of viewmodels, sub-templates will inherit their parent's viewmodel simply by getting parsed by the ViewModel initialized on the overlying template. The parsing of `data-bind=` attributes on sub-templates currently happens by default unless the sub-template has its own viewmodel.

Besides being a bit confusing, this creates a discrepancy when the properties of the overlying template's viewmodel *can* be used as helpers on the overlying template, but are not present on the sub-template (since this is how Blaze works), where they may be every bit as justified.

This discrepancy can only be lifted by *not* parsing the elements of embedded templates in the first place.

**Comment by ManuelDeLeon** [comment]
>I'm not sure I agree.
Inversion of control – "don't call us, we'll call you" – is somewhat synonymous with dependency injection. Now, the child should be able to stand alone as a unit in itself and live without any inferred dependencies – whereas a parent always knows about it's children.
By my logic, this means that the child should never have to call the parent (which might not exist), the parent should always call the child (which definitely exists).

It's an inversion of control because the parent template doesn't "use" the components, it merely instantiates them. It's the children/components the ones that use the parent in the form of calling its methods and setting its properties.

> The parsing of data-bind= attributes on sub-templates is happening by default – except when the sub-template has its own viewmodel

If I understand you correctly then this is 100% intentional and by design. If you have a `data-bind` in a template then that template should have a view model.

**Comment by dalgard** [comment]
> If you have a data-bind in a template then that template should have a view model.

Exactly my point – that template ought to have been given *its own* viewmodel. Of course, developers can't be trusted to remember these best practices, which is why ViewModel shouldn't parse `data-bind=` attributes on sub-templates in the first place.

> It's the children/components the ones that use the parent in the form of calling its methods and setting its properties.

I guess maybe both our points could be valid in regard to inversion of control. Nevertheless, I still think I made a good argument about the dependency relationship of parent/child.

**Comment by dalgard** [comment]
After debating this with my colleagues, I'm leaning towards an IoC-like pattern, where the parent template instantiates the child template and, in that process, passes a reference to the property on the parent that should be read or written to.

This is pretty much exactly what you are doing in the first part of [this example](https://github.com/ManuelDeLeon/viewmodel/issues/82#issuecomment-129501036) – you pass the actual attribute by reference in a round-about way required by Blaze. In the second part, you use a predetermined property name, which might also have been passed in as a string:

```html
<template name="myOverview">
  {{> myFilter bindTo='filter'}}
</template>

<template name="myFilter">
  <input type="text" data-bind="{{#if bindTo}value: parent.{{bindTo}}{{/if}}">
</template
```

**Comment by ManuelDeLeon** [comment]
> Exactly my point – that template ought to have been given its own viewmodel. Of course, developers can't be trusted to remember this best practice – which leads me to conclude that ViewModel shouldn't parse data-bind= attributes on sub-templates at all.

Ahhh, I can now say with confidence that I get your point. Sorry it took so long. This is something I've been trying to do since day 1 but Blaze doesn't allow it. I can't just parse the elements of one template. Blaze forces me to parse the template and all its children. So for now we're stuck with this situation where if you put a `data-bind` on a child template, without a child view model, it will be picked up by the parent. =/

> Using the same pattern, the name could also be passed in as a string:

Nice! Got a question though, why the `{{#if bindTo}}`? Seems to me that the component will need to be bound to something (making the `if` kinda pointless).

Either way, it's a great use of `parent`. I now have a few more patterns to use:

```
<template name="one">
  {{> two }}
</template>

<template name="two">
  <input data-bind="value: parent.name">
</template>

Template.one.viewmodel({
  name: ''
});

Template.two.viewmodel({
  
});
```

And your example:

```
<template name="one">
  {{> two bindTo="name" }}
</template>

<template name="two">
  <input data-bind="value: parent.{{bindTo}}">
</template>

Template.one.viewmodel({
  name: ''
});

Template.two.viewmodel({
  
});
```

**Comment by dalgard** [comment]
> Ahhh, I can now say with confidence that I get your point. Sorry it took so long.

Sorry for flooding you project with questions ;) But thanks for taking the time. I think everything comes down to MVVM having some fundamental challenges, in spite of it being a great pattern for UI.

I recognize many of these questions from Knockout and Angular, and it's great being able to discuss them.

> I can't just parse the elements of one template. Blaze forces me to parse the template and all its children.

Maybe I'm being naïve, but couldn't you simply check whether the element belongs to the correct template view?

```javascript
template.$("[data-bind]:not([data-bound])").filter(function () {
  return getClosestTemplateView(Blaze.getView(this)) === template;
});

function getClosestTemplateView(view) {
  do if (view.template) return view;
  while (view = view.parentView);
}
```

**Comment by dalgard** [comment]
> Nice! Got a question though, why the {{#if bindTo}}? Seems to me that the component will need to be bound to something (making the if kinda pointless).

I like being able to insert the widget somewhere without actually binding it. An example would be in a style guide.

 
Btw, this is GitHub's markdown syntax for syntax highlighting, in case you didn't know :)

    ```javascript  <-- or html etc.
      var name = function () {};
    ```

**Comment by dalgard** [comment]
On a theoretical level, I think some of the issues with finding the right pattern has to do with wanting components to be generic while using them in a specialized way...

I feel like I've gotten myself into a quagmire a little too quickly with the IoC/`bindTo` approach, unfortunately.

1. It doesn't read well when there are multiple bindings for reading and writing, on top of component settings etc. – `{{> myFilter bindTo='filter' bindTextLoadingTo='filterTextLoading' bindDateLoadingTo='filterDateLoading' showDateField=true ...}}`

2. Having to use a factory when creating the viewmodel instead of a nice, declarative object, is a bummer. Setting up the binding also requires boilerplate code, making things more cumbersome and less readable.

I guess I'll go back to passing in data through named parameters and getting out data through `this.children()`.

Then we'll see what consequences it leads to.
