### ISSUE TITLE
Binding to property on parent viewmodel

### ISSUE THREAD

**Issue by dalgard** [ManuelDeLeon/viewmodel#82]
I feel like I'm missing something simple here.

I have a template `overview` that presents a list of items. At the top of `overview` I have a a sub-template `filter` that contains various fields for filtering the list. The `filter` template has it's own viewmodel that handles various states internal to that template.

How can I update some property on the parent `overview`'s viewmodel each time I, for instance, write something in the search field inside the `filter` template?

I mean, it's easy to update a property on `filter`'s own viewmodel with `data-bind="value: filter"`, but how can I make it propagate to the parent? What confuses me, I think, is that retrieving a value is easy, while putting one is not.

Thanks!

**Comment by ManuelDeLeon** [comment]
The pattern I use is:

```
<template name="overview">
  {{> filter context}}
</template>

<template name="filter">
  <input data-bind="value: text">
</template>
```
```
Template.overview.viewmodel({
  text: '',
  context: function() {
    return {
      text: this.text // Pass by reference
    }
  }
}, 'context');

Template.filter.viewmodel(function(context){
  // Add context properties to this view model
  // in this case 'text'
  return context;
});
```

But now that you mention it, you should be able to simply do:
```
<template name="overview">
  {{> filter }}
</template>

<template name="filter">
  <input data-bind="value: parent.text">
</template>
```
```
Template.overview.viewmodel({
  text: ''
});

Template.filter.viewmodel({
});
```

I'll update ViewModel.

I'd be careful not to over use it though. Seems to me that if the filter view model is responsible for the filters then whomever needs the filters should talk to the filter view model for that data. Something like `ViewModel.byId("filters").text()`

**Comment by ManuelDeLeon** [comment]
btw, check out this part of the documentation: http://viewmodel.meteor.com/#dataContextBk

**Comment by ManuelDeLeon** [comment]
Update to 1.9.0, you're now able to do the following:

```
<template name="overview">
  {{> filter }}
</template>

<template name="filter">
  <input data-bind="value: parent.text">
</template>

Template.overview.viewmodel({
  text: ''
});

Template.filter.viewmodel({
});
```

**Comment by dalgard** [comment]
In regard to the first pattern you mention – I was actually considering this, but I thought that it wouldn't work, since inside `context`, `this.text` is a function – and I still haven't gotten my head around how a function can be used to write data to the viewmodel.

Like, when I inspect the scope inside some function on the viewmodel that is called by a setter such as `data-bind="value: text">`, the actual data is nowhere to be seen, neither as a parameter or on `this`.

---

The addition of `parent` in 1.9.0 is a brilliant preliminary move – thanks so much.

I'll continue to explore the patterns and anti-patterns here, and writing directly to some random overlying scope may easily prove to be a bad idea. On the other hand, grabbing a viewmodel by id doesn't seem right, either,

I think we'll end up with a nice solution, though. You answer in [the other issue](https://github.com/ManuelDeLeon/viewmodel/issues/81) could be it.

Thanks again for the great work!

**Comment by ManuelDeLeon** [comment]
> inside context, this.text is a function – and I still haven't gotten my head around how a function can be used to write data to the viewmodel directly from the template.

It works because every member of a view model is function. When you declare a view model you use plain properties (`text: ''`) but to get a value you use `.text()` and to set a value you use `.text('ABC')`. So when you pass the context you're passing an object with one function that is actually a reference to the `text` function that can be used to set or get the value on the parent.

Let me know if you need more help with this because it's at the core of how ViewModel works.

> when I inspect the scope inside some function on the viewmodel that is called by a setter such as data-bind="value: text">, the actual data is nowhere to be seen, neither as a parameter or on this.

I need an example because I don't follow =/

> The addition of parent in 1.9.0 is a brilliant preliminary move – thanks so much.

.parent() isn't new. The change I made isn't specific to `parent`. I made it so you can bind to sub properties. In your case it just so happens that you're binding to a sub property of `parent`.

>  grabbing a viewmodel by id doesn't seem right

Check out "A tree of templates" under "Passing Data Contexts" (http://viewmodel.meteor.com/#dataContextBk)

**Comment by dalgard** [comment]
> Check out "A tree of templates" under "Passing Data Contexts" (http://viewmodel.meteor.com/#dataContextBk)

I gave the section a second review, when you posted it before, but I am still confused in regard to viewmodel properties being functions. I think I can explain why:

From what you write – `.text()` getting the value and `.text(value)` setting it, which is also clear from the docs – I would expect to be able to do something like this:

```html
<input type="text" data-bind="value: text">
```

```javascript
.viewmodel({
  text: function (new_value) {
    // When used as setter, new_value would be the new value from the input field,
    // otherwise return the old value
    if (new_value) some_var_in_scope = new_value;
    else return some_var_in_scope;
  }
});
```

However, the function isn't called with `new_value` when I type something into the input field. Neither does the new value exist as a property of `this`.

Do you see what I mean?

**Comment by dalgard** [comment]
It would be awesome if we could end up with a clear answer in regard to my `overview`/`filter` example (continuing the discussion from the other issue https://github.com/ManuelDeLeon/viewmodel/issues/81#issuecomment-129607658).

The central question is how to best use data from a child viewmodel in the parent. You've given an example of how to bind the element inside the sub-template/child viewmodel directly to the parent viewmodel, but I can see why this direction in the coupling is not optimal:

One should be able to insert a template anywhere and have it work as a self-contained unit without it knowing anything about of the overlying scope/viewmodel – and on the other hand, you always deliberately include a sub-template inside another and can thus guarantee the presence of it's viewmodel.

This means that the correct way of getting data out of the embedded sub-template's viewmodel is through `this.children().list()[<index>].prop()` (preferably without the `.list()` part).

What throws me a bit about this method is that if I happen to switch around the order of the embedded templates inside the parent, `<index>` no longer corresponds correctly and must be updated.

A better way would be to use the name that is already an optional feature of any viewmodel as a selector inside `this.children()`, like this:

```javascript
Template.myFilter.viewmodel("myFilter", {
  text: "",
  caseSensitive: false
});
```

```javascript
Template.myOverview.viewmodel({
  currentFilter: function () {
    return this.children("myFilter")[0];  // There could be more than one...
  }
});
```

**Comment by dalgard** [comment]
Instead of `children()` returning an array, even when it is passed an id, it might be sane to make this part of the API match `ViewModel.byId()`.

In practice, this means that `this.children(id)` should return the `first` child with `id`.

If the same sub-template is used more than once, it is the developer's responsibility to make sure their viewmodels get a unique id based on each data context.

**Comment by dalgard** [comment]
I'd be happy to create pull requests for the features we are talking about.

**Comment by ManuelDeLeon** [comment]
> I'd be happy to create a pull requests for a children() function that filters by id.

I have to think about this one because grabbing a child by it's id is equivalent to `ViewModel.byId("childId")`

**Comment by ManuelDeLeon** [comment]
(scheduled for v2)

**Comment by dalgard** [comment]
I'm sorry, but I just realized that I still don't understand the way properties are converted to functions, especially in regard to the `value` binding.

The question is:

How come, if I bind an input field to a property that is a function, that function isn't called with the new value when the input field changes?

**Comment by ManuelDeLeon** [comment]
> How come, if I bind an input field to a property that is a function, that function isn't called with the new value when the input field changes?

That should work for you. Here's an example:

```html
<template name="info">
  Name: <input data-bind="value: name">
</template>
```
```js
Session.setDefault("name", '');
Template.info.viewmodel({
  name: function(newName){
    if (newName) {
      Session.set("name", newName);
    } else {
      return Session.get("name");
    }
  }
});
```

In this example I'm almost replicating what ViewModel does for properties (ViewModel doesn't use session variables for this).

**Comment by dalgard** [comment]
All of a sudden that totally works. I wonder what I did wrong when I tried it the other times... But that's awesome – makes much more sense to me.

**Comment by avalanche1** [comment]
Can't this be achieved w\o Session? I thought vm.methods were naturally reactive sources...
