### ISSUE TITLE
Method for getting child viewmodels

### ISSUE THREAD

**Issue by dalgard** [ManuelDeLeon/viewmodel#84]
When calling `this.children()` inside a viewmodel property, the returned array isn't reactive. If I try to use a property that calls the child viewmodel *before* the point in the template where the child template is initialized, I'll probably get a `TypeError: can't read property <> of undefined` – and the value isn't updated subsequently.

The problem is easily fixed, since we're dealing with a `ReactiveArray` (nice move!), by writing `this.children().list()` instead.

However, I propose that in [viewmodel.coffee#L48](https://github.com/ManuelDeLeon/viewmodel/blob/master/viewmodel.coffee#L48) you make `this.children()` reactive by returning the result of `list()` directly:

```coffeescript
@children = -> self._vm_children.list()
```

**Comment by ManuelDeLeon** [comment]
Thanks for the heads up. I could have sworn it was reactive already. I'll check it out.

**Comment by ManuelDeLeon** [comment]
I'm confused. If you go to http://viewmodel.meteor.com/#arraysBk then open the console and enter:

```
Tracker.autorun(function() { console.log("total: " + ViewModel.byId("arrayList").children().length); })
```

If you add a name to the list (you can do this in the UI) the autorun function does re-run, thus .children() is reactive.

**Comment by dalgard** [comment]
Strange that it works for you – in my case nothing happened until I used `.list()`. This corresponds with the section explaining the [.list method](http://reactivearray.meteor.com/#listBk) in the docs for ReactiveArray – together with [viewmodel.coffee#L48](https://github.com/ManuelDeLeon/viewmodel/blob/master/viewmodel.coffee#L48) clearly just returning the bare ReactiveArray.

**Comment by dalgard** [comment]
In any case, I actually expected there to be a `get()` method on the ReactiveArray that was returned by `children()`. This method is what makes ReactiveDict, ReactiveVar, and TemplateVar be reactive, so off the bat, I thought I should write `this.children().get(<index>)` :)

I think it would be a logical addition to ReactiveArray's API. https://github.com/ManuelDeLeon/ReactiveArray/issues/4

**Comment by dalgard** [comment]
I think this issue would be resolved by my pull request to ReactiveArray – reactivity would then be achieved simply through using `get()` on the returned array.

https://github.com/ManuelDeLeon/ReactiveArray/pull/5

**Comment by ManuelDeLeon** [comment]
You've given me a lot to think about so I'll answer different posts at different times. Feel free to continue giving me your thoughts =)

I'll start with this one. 

v 1.9.1 updated the children method to 1) be reactive and 2) accept the name of children's template you want to pull or a bool predicate function you can use to test whether or not you want the child to be returned. See http://viewmodel.meteor.com/#childrenBk

About the `.get(index)` method.

I don't think it fits well for the array object because we're talking about a collection of objects. ReactiveVar deals with 1 value at a time. ReactiveDict is basically a collection of ReactiveVars so it falls in the same category.

A reactive array is akin to a collection. If you have a People collection, the People variable by itself isn't reactive. It's when you call .find that you get the reactivity. With the array you get it when you call `.list()` or `.depend()`.

**Comment by dalgard** [comment]
Thanks for considering this (and for the quick reply). I'm continuing this discussion in the issue on ReactiveArray: https://github.com/ManuelDeLeon/ReactiveArray/issues/4

**Comment by dalgard** [comment]
I only just realized that the name passed to `this.children(name)` in your 1.9.1 extension is of the template, not the id of the viewmodel.

I think it should be `this.children(id)` for two reasons:

1. It's nice to keep things separate and the names of templates aren't really used anywhere else in ViewModel land.

2. More importantly, getting the child viewmodel by id makes it possible to include a template multiple times and then finding the right one based on its programmatically generated id (https://github.com/ManuelDeLeon/viewmodel/issues/86):

```html
<template name="myPage">
  {{> myPanel id='first'}}
  {{> myPanel id='second'}}
</template>
```

```javascript
Template.myPanel.viewmodel(function (data) {
  return "panel__" + data.id;
}, {
  prop: ""
});

Template.myPage.viewmodel({
  firstPanelProp: function () {
    return this.children("panel__first").prop();
  }
});
```

**Comment by dalgard** [comment]
This code works perfectly for what I want, when inserted in `viewmodel.coffee`:

```coffeescript
    @byId = (id) ->
      list = @_vm_children?.list()
      test = if _.isFunction id then id else (vm) -> vm._vm_id is '_vm_' + id

      return (vm for vm in list when test(vm))
```

However, I prefer not to moderate your package, so I've added the method via ViewModel's prototype instead in my project:

```javascript
ViewModel.prototype.byId = function (id) {
  var list = this._vm_children && this._vm_children.list(),
      test = _.isFunction(id) ? id : function (vm) {
        return vm._vm_id === "_vm_" + id;
      };

  return _.filter(list, test);
};
```

**Comment by ManuelDeLeon** [comment]
> I think it's nicer to keep things separate and not use template names anywhere in ViewModel land.

The thing is that ViewModel already works side by side with Blaze so I think it's better to make the best use of that relationship. Not to pretend that it doesn't exist.

> To be honest, I don't think that's very useful – the relevant thing isn't the template, it is the template's viewmodel.

They can both be useful. Sometimes you have a view model that have two different kinds of children, say products and customers. In those situations it's very convenient to be able to say "give me all the children that are products" without using a lambda. 

For v2 I'm actually thinking of getting rid of `byId` and `byTemplate`, and use `find` and `findOne` instead. They would take a string, object, or function. With a string `find` will work as `byTemplate`, `findOne` would work as `byId`. With an object they would the return the matching view model(s). With a function it will be treated as the predicate to use to retrieve the matching view model(s).

> I'd simply like to have the byId() method scoped to the current viewmodel's immediate children. And it would be rather elegant to simply call it this.byId(id), I think.

I have to disagree on that one. If you want to match sub view models then you should use the `.children` method. Besides, it would mean that `byId` wouldn't be able to grab a view model that's not a child.

**Comment by dalgard** [comment]
The thing is, that I'm at no point interested in referencing a *template* – I always want the template's viewmodel. Seeing that viewmodels can be given ids, I think it's a good idea to keep the two concepts – template names and viewmodel ids – separate.

This separation has a couple of advantages:

1. I don't have to look deep into my viewmodel code when renaming a template.
2. I can use names that are more appropriate in viewmodel land than their templates' names.
3. **I can even go so far as to use the same viewmodel name on different templates**. Imagine that I have three different types of filter panels, but all of them produce a regex – then I can name all of their viewmodels "filter", and the parent viewmodel can get out the value and not care which template was used (when not doing IoC) with `this.findOne("filter").regex()`.

**Comment by dalgard** [comment]
I like the idea of having one method for retrieving an array of viewmodels (`find()`) and another for getting the first one (`findOne()`).

But I think you made a good choice when using the names "parent" and "child" – it's easy to understand. So I'd much rather see the two functions be named `children()` and `child()`.

**Comment by dalgard** [comment]
> I have to disagree on that one. If you want to match sub view models then you should use the .children method. Besides, it would mean that byId wouldn't be able to grab a view model that's not a child.

I didn't express myself clearly before – I don't suggest changing the global `ViewModel.byId()` method, simply having a method with the same signature and return value on each viewmodel, where it would be scoped to the child viewmodels.

**Comment by ManuelDeLeon** [comment]
We would still have `parent`. `children`, and probably `child` to retrieve sub view models. `find` and `findOne` are going to be static methods of `ViewModel` to retrieve _any_ view model.

That covers all the basis. You can grab a single child or vm by id, template name, and free query. You can also grab children or multiple vms by template name, and free query. When using a query you can give the vms a category and then query by that.

**Comment by dalgard** [comment]
Sounds like the methods I'm wishing for – great.

I'm a little unsure about your opinion on the actual interface of each method. From the argument I just made about viewmodel ids (which I'd like to call "viewmodel names", since they don't have to be unique), I'd like them to be the primary selector you pass to the methods.

I don't mind, of course, that it's possible to use template names if you don't want to think up and assign a name to each viewmodel, but yeah.

The `ViewModel.prototype.child` method that I've added in my current project has this signature: `child(name[, index=0])`. So, in case there are a before and after date field in my view, I can get them like this:

```javascript
var from_date = this.child("date").date(),
    to_date = this.child("date", 1).date();
```

**Comment by ManuelDeLeon** [comment]
If you give the same id to multiple view models you're going to run into trouble when a hot code push occurs and ViewModel tries to preserve the state.

**Comment by dalgard** [comment]
For me, that's a problem with ViewModel, for the reason I described above. Feel like I've got a really good pattern going with this, after several attempts.

**Comment by ManuelDeLeon** [comment]
What you're doing is very fragile. The index can change if you move the elements on the page. As for using non unique values for the id's, as open minded as I'd like to be, I don't think you'll be able to convince me that it's a good idea. I think it's much better to add a category of some sort to your view models and then pull them by that property, grab by template name, give the view models unique names ('fromDate'/'toDate'), or any combination of those.

btw, I do use id, unique id, name, and unique name interchangeably. I'll be more careful on v2.

**Comment by dalgard** [comment]
I think "very fragile" is a considerable overstatement; with a name, there will be a very limited number of selected elements, and having to choose between them based on an index, just like one would with any other returned array, e.g. those based on template names, is a good options with views up to a certain size.

All in all, it's just a quick way of getting something that you might have gone through the trouble of assigning a unique id to programmatically. It's less code and will work fine in most cases.

I'll make an example for you tomorrow or the day after that shows the simplicity and power that this pattern has brought to my current views.

**Comment by ManuelDeLeon** [comment]
Okay let's see it, make an example like that and also with "vanilla" ViewModel.

**Comment by dalgard** [comment]
Here are the two examples. There isn't much difference between them – the point is that I like the general pattern, and the interface I use with `child` makes the most sense to me. I think it's more extensible and perhaps slightly more self-explaining/robust.

[ViewModel example: Child method](http://meteorpad.com/pad/5zB6vqttY3ELGGoXb/ViewModel%20example:%20Child%20method)
[ViewModel example: Vanilla](http://meteorpad.com/pad/9xeX9ReE3RXyojywb/ViewModel%20example:%20Vanilla)

**Comment by ManuelDeLeon** [comment]
To me that's making the case for `.child` (which I already agree it's a good idea), not for giving non unique ids to view models.

**Comment by dalgard** [comment]
The point is still what I wrote about in https://github.com/ManuelDeLeon/viewmodel/issues/84#issuecomment-131136331
