### ISSUE TITLE
Idea: Use the new viewmodel as context for factory functions

### ISSUE THREAD

**Issue by dalgard** [ManuelDeLeon/viewmodel#86]
A new viewmodel can be created using a factory function like this:

```javascript
new ViewModel(function (data) {
  return { prop: "" };
});
```

Giving access to the template data like this is a great idea – good work.

A cool addition would be to have our newly created, empty viewmodel as the context (`this`) inside the factory.

This would allow adding properties to the new viewmodel using methods instead of the declarative approach, as well as other things. Some of the possibilities are not necessarily best practices, but might be warranted by some cases.

Furthermore – if the new viewmodel was the context, it could have a method like `this.setId()`, which could be called in order to give the viewmodel an id programmatically.

I realize that it's already possible to set the id by returning a string from the first factory function argument, but this pattern is highly unusual and I'm afraid many people will miss it.

---

P.S. Being able to add an id programmatically is nice when embedding a sub-template more than once:

```html
<template name="myPage">
  {{> myPanel id='first'}}
  {{> myPanel id='second'}}
</template>
```

```javascript
Template.myPanel.viewmodel(function (data) {
  // Example of updated API
  this.setId("myPanel__" + data.id);

  return { prop: "" };
});

Template.myPage.viewmodel({
  firstPanel: function () {
    return ViewModel.byId("myPanel__first");  // or this.children("myPanel__first")
  }
});
```

**Comment by dalgard** [comment]
I'd be happy to create a pull request this feature.

**Comment by dalgard** [comment]
An alternative – but less elegant – solution would be for ViewModel to check whether the result from a factory is actually a ViewModel (instead of a plain object). Then this should be used instead of creating a new one.

```javascript
Template.myPage.viewmodel(function () {
  var vm = new ViewModel;

  vm.setId("page");
  vm.extend({ prop: "" });

  return vm;
});
```

**Comment by ManuelDeLeon** [comment]
Well, I'm trying to simplify things. That's why on v2 when declaring view models I'll drop the first parameter being the vm name and the last parameter the helper methods.

This is unneeded because if you want that level control you can always do:

```js
Template.myPage.onCreated(function(){
  var vm = new ViewModel;
  vm.setId("page");
  vm.extend({ prop: "" });
  this.vm = vm;
})
```

As far as I can tell this pattern is not used but if by some reason it is then I'd implement it so you'd receive the view model as a parameter (to simplify things, as always).

```js
Template.myPage.viewmodel(function (data, vm) {
  vm.setId("page");
  vm.extend({ prop: "" });
});
```
