### ISSUE TITLE
byId() only returns first instance

### ISSUE THREAD

**Issue by dalgard** [ManuelDeLeon/viewmodel#87]
When the same template with a named viewmodel is inserted multiple times, `ViewModel.all` has multiple viewmodel references with the same id.

When I want to get one of these using `ViewModel.byId(id)`, it only returns the first viewmodel on the list.

Making sure that each instance gets a unique id *is* possible, for instance, by assigning the id based on the template's data context – but in any case, the documentation doesn't say anything about multiple viewmodels with the same id.

I'm not sure if anything should be done about this, just wanted to point out the lack of documentation. Thanks.

**Comment by ManuelDeLeon** [comment]
Thanks for the heads up. I updated the documentation.

As a convenience `.byId` returns the first view model for a template. That way you don't have to give it a name if you only have one instance of that template. If there are multiple instances then you need to use `.byTemplate` to get all of them.

**Comment by dalgard** [comment]
To me it seems really strange that you can pass a template name to `byId()`.

I would expect that method to simply run through `ViewModel.all` and return either 1) the first viewmodel where id matches, or 2) an array with 0 or more viewmodels where id matches.

I'd expect `byTemplate()` to work in exactly the same way with template names.

I'm a bit ambivalent in regard to the return value:

1. There might be more than one viewmodel that matches, or there might be zero. This calls for an array.
2. On the other hand, in almost all cases there would only be a single match, which makes it inconvenient having to write `[0]` (or `.get(0)` or `.first()`) every time.

In any case, the result should be reactive, and I guess depending on- and returning a reactive array makes most sense.

**Comment by ManuelDeLeon** [comment]
> To me, it seems really strange that one can pass a template name to byId().

I think it's a nice way to reference view models that are only used once. So if you have:

```js
Template.login.viewmodel({
  username: ''
})
```

You can then reference it by `login` without having to give it a name explicitly.

**Comment by dalgard** [comment]
https://github.com/ManuelDeLeon/viewmodel/issues/84
