### ISSUE TITLE
Interface for changing the id of a viewmodel

### ISSUE THREAD

**Issue by dalgard** [ManuelDeLeon/viewmodel#88]
I'd like to be able to do `myviewmodel.setId(new_id)`. This should rerun all computations that depend on `byId()` and `children()`. The feature would make it easier to work with ids programmatically.

**Comment by ManuelDeLeon** [comment]
That's not going to be possible without some major rework of ViewModel's internals. ids must be set when you create the view model and not change because if they do it would break the automatic state save and reload upon hot code pushes. Maybe for v2.

Why do you want it?

**Comment by dalgard** [comment]
I probably shouldn't have created an issue with this. I'm just trying out various ways of using ViewModel, as you've noticed, and the function would be nice in case of a more procedural approach.

https://github.com/ManuelDeLeon/viewmodel/issues/86
