### ISSUE TITLE
ViewModel doesn't update when the data context of a #with statement changes

### ISSUE THREAD

**Issue by santiagopuentep** [ManuelDeLeon/viewmodel#89]
I have these templates:

```
<template name="main">
	{{#with root}}
		{{> child}}
	{{/with}}
</template>

<template name="child">
	<div>{{getText}}</div>
</template>
```

With this helper:
```
Template['main'].viewmodel({
	root: function() {
		var itemId = FlowRouter.getParam("_id");
		return  ItemsList.findOne(itemId);
	},
});
```

If I change the value of the _id of the route the child template doesn't update if I use viewmodel but it does if I use a regular template helper.

```
// this works
Template['child'].helpers({
	getText: function () {
		return ItemsList.findOne(this._id);
	},
});

// this doesn't
Template['child'].viewmodel(
	function (data) {
		return {
			getText: function () {
				return ItemsList.findOne(data._id);
			}
		};
	},
	['getText']
);
```

The problem I think is that the viewmodel doesn't get recreated when the data context of the #with statement changes. Is there a way to go around this?

Thanks!

**Comment by ManuelDeLeon** [comment]
Yeah, don't use `with` and use `FlowRouter.getParam("_id")` in `getText` of your view model.

**Comment by santiagopuentep** [comment]
Shouldn't it work with `#with`? If the data changes shouldn't a new viewmodel get created?

The problem is that this example is oversimplified, in the real app I need to be able to change routes and re-render the `child` template with an id from `FlowRouter.getParam('_id');` and I even need to be able to access the viewmodel by id (which I put as the viewmodel's unique name). The `child` template can as well have other `child` templates inside it so I can't hardcode the id directly from `FlowRouter`.

What I mean is that I need to be able to change the id to render and the template should change to one that uses that Id to build itself up.

**Comment by santiagopuentep** [comment]
I was able to finally solve the problem using en `each` statement in the `main` template instead of `with` and returning a cursor in the `root` helper instead of the item itself. Now it updates on route change.

It would be great to know it the `with` statement problem is a bug of viewmodel to know how to handle it if I ever need it again.

Thanks!

**Comment by dalgard** [comment]
+1 For tracking down this problem. Seems like it should have worked.

**Comment by ManuelDeLeon** [comment]
The thing is that this isn't really a bug but a difference in how Blaze and ViewModel work. You're basically comparing apples to oranges.

For example, the most normal thing is to put `People.find().fetch()` inside an autorun and have that function re-run when the cursor changes. Yet the same will not re-run if you put it inside a publication. That's because they operate in different ways.

Back to ViewModel, it works differently than Blaze. 

The gist of it is that as far as ViewModel is concerned you're initializing the view model with a static/non-reactive value. Since Blaze doesn't re-render the template when the `with` data changes, ViewModel keeps the static/non-reactive value. To get the reactivity you need to initialize the view model with a function that uses a reactive value.

I don't know how FlowRouter works, but if `FlowRouter.getParam("_id")` is reactive then you need to use that inside a function in the view model, not simply pass the (non-reactive) result to it.

Check out these threads:
http://viewmodelboard.meteor.com/comments/GRiBWwaSkTgaR59Td
https://github.com/ManuelDeLeon/viewmodel/issues/46
https://github.com/ManuelDeLeon/viewmodel/issues/74

**Comment by santiagopuentep** [comment]
I understand that the viewmodel starts with a non reactive object but how can I do to have the `child` viewmodel change when the `with` changes? I don't see how to make it work. Isn't there a way to make the with reactive as it should? Otherwise is very misleading and problematic I think.

`FlowRouter.getParam("_id")` is reactive, and I'm using it in the `root` function but I can't use it in the `child` viewmodel because I need it to be completely rebuilt on data context change (even the viewmodel name that uses the id).

**Comment by ManuelDeLeon** [comment]
Let's forget about ViewModel for a second. How would you get such reactivity with good old Blaze?

Given the following:
```html
<body>
  {{#with person }}
    {{greeting}}
  {{/with}}
</body>
```
```js
Session.setDefault("person", { name: "Alan" });

Template.body.helpers({
  person: function() {
    return Session.get("person");
  },
  greeting: function () {
    return "Hello " + "Alan";
  }
});
```

What do you put instead of `"Alan"` that would make `greeting` reactive regarding the person used by the `with`? That is, if I change the person object via `Session.set("person", { name: "Bert" })`, the `greeting` function returns "Hello Bert" to the UI.

**Comment by ManuelDeLeon** [comment]
I'll answer my own question: you use `this.name`. The thing to notice is that you can't access `this` from anywhere but a helper method. You can't put an autorun for it on created or rendered. It's a Blaze sleight of hand (so much that the Blaze 2.0 proposal wants to do away with it). 

The bottom line is that to obtain reactivity you need to use a reactive source.

**Comment by santiagopuentep** [comment]
Sorry manuel, I still don't undesrtand how to solve it using a `with`. I understand that ViewModel starts with non reactive data but in my example at the top how would you make it work?

I had to change the `with` with and `each` and return a cursor for the root to get the result I want, but that's hacking it, it would be great to know how to do that in a `with`.

This ticket is closed, I couldn't answer before, but I would really love to undestand this.

**Comment by ManuelDeLeon** [comment]
Option 1) You drop the #with and put the contents of 'root' in a function
of the child view model.

Option 2) You drop the #with and create a view model for the parent (if you
don't have one already) and from the child you call this.parent().root() to
get the reactive value.

**Comment by santiagopuentep** [comment]
That wouldn't solve the problem of recreating the viewmodel on root value change, but don't worry, I'm using an `each` statement and it works fine.

Thanks for the help anyway!

**Comment by ManuelDeLeon** [comment]
It does work...

```html
<template name="parent">
  <h1>Parent</h1>
  Name: <input data-bind="value: name">
  <button data-bind="click: update">Update</button>
  {{> child }}
</template>

<template name="child">
  <h1>Child</h1>
  Parent Name: <span data-bind="text: parentName"></span>
</template>
```

Here's option 1 (child in control of the reactive value)

```js
Session.setDefault("parent", { name: '' });

Template.parent.viewmodel({
  name: '',
  update: function() {
    Session.set("parent", { name: this.name() });
  }
});

Template.child.viewmodel({
  parentName: function() {
    return Session.get("parent").name;
  }
});
```

Here's option 2 (parent in control of the reactive value)

```js
Session.setDefault("parent", { name: '' });

Template.parent.viewmodel({
  name: '',
  update: function() {
    Session.set("parent", { name: this.name() });
  },
  data: function(){
    return Session.get("parent")
  }
});

Template.child.viewmodel({
  parentName: function() {
    return this.parent().data().name;
  }
});
```

In both cases `Session.get("parent")` is the equivalent of `ItemsList.findOne(FlowRouter.getParam("_id"))`.

**Comment by santiagopuentep** [comment]
I think we are talking about different things. The changes in the reactive value I understand but what I don't is how to have the child template recreated/rerendered when the `parent` value changes in your example.

If the "parent" value changes I want the child template to be removed and a new one to be created. This is because the child template in my example can't get it's id from outside (like by asking the parent for the id) because of what my project needs. The parent needs to create the child based on the id, and reactively recreate it if the id changes. That's why I was using a `with`.

In your last example the chlid template always stays the same but changes it's internal values based on a reactive variable.

**Comment by ManuelDeLeon** [comment]
That's the thing, whatever reactive value triggers the change in the `#with` can be used to change the properties of the child (reactively, without recreating the template).

**Comment by santiagopuentep** [comment]
Ok, thanks manuel.
