### ISSUE TITLE
Undocumented autorun hook

### ISSUE THREAD

**Issue by dalgard** [ManuelDeLeon/viewmodel#91]
I happened to spot in another issue thread that there is a special `autorun` hook and was immediately able improve the readability of my code – great!

```javascript
// Before
Template.myPage.viewmodel({
  onRendered: function (instance) {
    instance.autorun(function () {
      ...
    }.bind(this));
  }
});

// After
Template.myPage.viewmodel({
  autorun: function () {
    ...
  }
});
```

Shouldn't this hook be in the documentation?

**Comment by dalgard** [comment]
By the way, how come `this.templateInstance` isn't present yet inside `autorun`? I can just write `Template.instance()`, but I think the other thing looks nicer.

**Comment by dalgard** [comment]
I can confirm that this code works with the current version, but I'm sure a better way could be found.

```javascript
autorun: function () {
  var instance = this.templateInstance || Template.instance(),
      data = Blaze.getData(instance.view);

  // This code reruns when the template data is changed
}
```

**Comment by ManuelDeLeon** [comment]
Thanks. I updated the documentation: http://viewmodel.meteor.com/#autorunsBk

I'll see about the template instance later on.

**Comment by dalgard** [comment]
It appears that ViewModel's `autorun` runs before the `onCreated` hook. This means that I can't access the template's DOM yet inside the hook. Things like initializing a jQuery widget is thus ruled out.

Would you consider putting the autorun after `onRendered` instead?

**Comment by ManuelDeLeon** [comment]
I don't see why not. Update to 1.9.3. Autoruns are now executed on rendered before bind.

If you need to run it after the bind then use afterBind:
```js
Template.body.viewmodel({
  afterBind: function(t) {
    t.autorun(function(){
      // Do Something
    });
  }
})
```

**Comment by dalgard** [comment]
Thanks! It also solves the thing about `this.templateInstance` not being present. Good job :+1:

**Comment by dalgard** [comment]
It might be an idea to be able to assign an array of functions to `autorun`, instead of having to call `viewmodel()` with multiple definition objects. Just a thought.

**Comment by ManuelDeLeon** [comment]
That's a good idea. Autoruns can now be declared with an array of functions (1.9.4) and I updated the documentation.

I'll leave this item open because I still haven't thought of the whole instance issue.

**Comment by dalgard** [comment]
That was quick. Great!

If you're referring to the presence of `this.templateInstance`, it was solved by using `onRendered`.

**Comment by takopus-tako** [comment]
>Thanks. I updated the documentation: http://viewmodel.meteor.com/#autorunsBk

bad link

**Comment by Maxhodges** [comment]
>Thanks. I updated the documentation: http://viewmodel.meteor.com/#autorunsBk

bad link. is it documented somewhere else? I'm having a bit of trouble trying to understand it all.

**Comment by ManuelDeLeon** [comment]
The documentation moved to https://viewmodel.org
