### ISSUE TITLE
Using plain array as value

### ISSUE THREAD

**Issue by dalgard** [ManuelDeLeon/viewmodel#92]
I have a field in my viewmodel that is an array of results. It is being used in multiple places, so I don't want the code that generates the results running each time the field is retrieved.

Instead, I'm updating the field based on other fields inside an autorun.

The problem is, that the other functions that depend on the field don't seem to rerun when I update the value using `this.results(some_new_array)`.

I suspect the reason has to do with ReactiveArray – is there some way that a native array can be used as a primitive value?

**Comment by ManuelDeLeon** [comment]
As you know arrays are automatically converted to ReactiveArrays. If you don't want this to happen you have to wrap it in a function:

```js
Template.body.viewmodel({
  names: function() {
	if(!this._names) this._names = [];
	return this._names;
  }
})
```
> the other functions that depend on the field don't seem to rerun when I update the value using this.results(some_new_array).

That's because you're replacing the ReactiveArray with a non reactive one. You need to add the new elements just like you would in a regular array:

```js
ReactiveArray.prototype.push.apply(this.results(), some_new_array);
```

**Comment by dalgard** [comment]
I understand. I still don't quite get the thing about functions, though – how do I write to a property that is a function? Do I call the function with the new value and store it on a variable in the function's closure or on the viewmodel itself?

**Comment by dalgard** [comment]
What worries me about using the methods on the ReactiveArray is that `clear()` triggers a `changed` event for every item that was in the array (and one at the end, I think).

**Comment by dalgard** [comment]
I almost forgot – there's also the major obstacle that if I retrieve the array with `this.results()` inside my autorun, the field will register itself as a dependency.

**Comment by ManuelDeLeon** [comment]
>  how do I write to a property that is a function?

All properties are functions with ViewModel. If you declare the view model with a value (`names: []`) ViewModel will wrap it in a function for you. If you declare it with a function ViewModel won't do anything with it. That's why in my example I declared the `names` property as a function that returns a plain array. You can do the same with other values like primitives.

> Do I call the function with the new value and store it on a variable in the function's closure or on the viewmodel instance?

It depends on the value. For primitives you call the function with the new value. For arrays you "pull" the array and then add/remove elements: `this.names().push("Alan")`

> What causes the functions that depend on the value to rerun, then?

A function is reactive if it uses a reactive source (a property or function that calls Tracker's depend). So in the case of my previous example with `names`, it's not reactive because I'm just using a plain array inside the function.

> What worries me about using the methods on the ReactiveArray, btw, is that clear() triggers a changed event for every item that was in the array (plus one at the end).

Meteor's dependencies don't resolve until the next JavaScript cycle. That means nothing will happen  while the clear loop is running. In other words, your screen will only update once if you add/remove elements from the array in a loop.

> there's also the much bigger obstacle that if I retrieve the array with this.results() inside my autorun, the field will register itself as a dependency, leading to an infinite loop.

You'd get the same effect if you modify any reactive value that you depend on in the same autorun. The solution is simple: don't modify what you depend on in the same autorun. In this case don't add/remove items in an array inside an autorun.

**Comment by dalgard** [comment]
So, the picture that remains is that updating any property inside an autorun is fine – *unless* it is an array. That's not good...

I wonder what we can do about it?

Until later, I guess the best solution is to attach a ReactiveVar directly to the viewmodel instance.

**Comment by dalgard** [comment]
In regard to properties that are declared with a function – wouldn't it be great if bindings that set a new value (such as `value` and `checked`) would call the function with the new value?

Then, after the function finishes, a `changed` event on the property could be triggered automatically.

**Comment by ManuelDeLeon** [comment]
> So, the picture that remains is that updating any property inside an autorun is fine – unless it is an array. That's not good...

It's not a problem of using an array, it's a problem of creating a circular reference. For example:

```js
Template.body.viewmodel({
  number: 0,
  autorun: function() {
	var num = this.number(); // Depend on number
	console.log(num); // Use number
	this.number(num + 1); // Update the property this autorun depends on
  }
})
```

That is the functional equivalent of adding items to a reactive array inside an autorun. You're changing the object that you depend on so the autorun executes again. Just like with recursive functions, you need a way to prevent an infinite recursion. Something like "add this item if it's not on the array already".

> wouldn't it be great if bindings that set a new value (such as value and checked) would call the function with the new value?

They already do. I gave an example on another thread (don't remember which).

**Comment by dalgard** [comment]
> It's not a problem of using an array, it's a problem of creating a circular reference.

I think they are two separate problems. I'm talking about the scenario where I just want the array treated like any other primitive value.

```javascript
Template.body.viewmodel({
  result: [],
  autorun: function () {
    // Dependencies
    var regex = Session.get("filter_regex"),
        items = MyItems.find().fetch();

    items = _.filter(items, function (item) {
      return regex.test(item);
    });

    this.result(items);
  }
})
```

**Comment by ManuelDeLeon** [comment]
What's wrong with the following?

```js
Template.body.viewmodel({
  result: function () {
    var regex = Session.get("filterRegex"),
        items = MyItems.find().fetch();
    return _.filter(items, function (item) {
      return regex.test(item);
    });
  }
})
```

**Comment by dalgard** [comment]
The problem is that the function runs every time the value is retrieved for presentation or other purposes. That's not good if filtering takes, for instance, 300 ms each time and the value is used in three or four places.

**Comment by ManuelDeLeon** [comment]
My Meteor install broke so I can't test it right now but I'm pretty sure this will work:

```js
Template.body.viewmodel({
  result: [],
  autorun: function () {
    var regex = Session.get("filterRegex"),
        items = MyItems.find().fetch();
    var filtered = _.filter(items, function (item) {
      return regex.test(item);
    });
    this.result.clear();
    ReactiveArray.prototype.push.apply(this.result, filtered);
  }
})
```

**Comment by dalgard** [comment]
`this.result` is wrapped in a function, so the ReactiveArray first has to be retrieved before it can be cleared and pushed to. And retrieving it creates an infinite loop.

**Comment by ManuelDeLeon** [comment]
Nope, this.result IS the reactive array. ViewModel makes it reactive if you
call it with parentheses.

Another undocumented feature =(

I'll update the documentation.

**Comment by dalgard** [comment]
Something must be wrong – when I inspect `this.result` inside `autorun` I get a `function vm.(anonymous function)(e)` like always.

**Comment by ManuelDeLeon** [comment]
Yeah I just noticed a problem between the chair and my keyboard. Let me get
back to you on this.

**Comment by ManuelDeLeon** [comment]
Sorry, that was a pattern that was available at the beginning but removed it in favor of using `Tracker.nonreactive`.

```js
Session.setDefault("people", [{ name: "Alan" }]);
Template.body.viewmodel({
  people: [],
  autorun: function () {
    var self = this;
    var peeps = Session.get("people");

    var peopleArray;
    Tracker.nonreactive(function(){
      peopleArray = self.people();
    });
    peopleArray.clear();
    ReactiveArray.prototype.push.apply(peopleArray, peeps);
    peopleArray.changed();
  }
}, 'people');
```

http://meteorpad.com/pad/96BAqaYMf9Jbn7DnT/Leaderboard
