### ISSUE TITLE
Click handler does not work with {{ #if }}

### ISSUE THREAD

**Issue by artin-phares** [ManuelDeLeon/viewmodel#93]
Hi, I have following template

```html
{{#if someFlag}}
   <a href='#' data-bind='click: action1'>action 1</a>
{{else}}
   <a href='#' data-bind='click: action2'>action 2</a>
{{/if}}

<a href='#' data-bind='click: action3'>action 3</a>
```
1. <code>someFlag</code> is true by default, and <code>action1</code> triggered successfully.
2. <code>action3</code> works great with any value of <code>someFlag</code> (as expected).
3. when <code>someFlag</code> becomes <code>false</code>, button <code>action2</code> appears, but clicking on it does nothing.

Looks like <code>click</code> handler is not applied after partial template render.

Anything wrong with my workflow?
Is this known issue? Any workaround?

**Comment by ManuelDeLeon** [comment]
http://viewmodelboard.meteor.com/posts/rrpagb6DnciFQde8J/f-a-q
