### ISSUE TITLE
Highlight Changing Fields ?

### ISSUE THREAD

**Issue by deanius** [ManuelDeLeon/viewmodel#94]
Could I do something like this upon ViewModel applying changes to the DOM ? What would be the way to hook in ? 
```
viewmodel.onChange( domElements ) {
   $(domElements).effect('bounce');
}
```

**Comment by dalgard** [comment]
ViewModel can't really know about which DOM elements change as the result of an updated property – the value of properties can be used anywhere in your application, including as regular Blaze helpers.

*You*, on the other hand, have a pretty good idea about which elements change.

I would do it like this:

```javascript
Template.login.viewmodel({
  prop: "",

  autorun: function () {
    // Depend on prop
    this.prop();

    this.templateInstance.$(".selector).effect("bounce");
  }
});
```

**Comment by deanius** [comment]
thanks again.

**Comment by ManuelDeLeon** [comment]
If you're bouncing the element that's changing you can just do:

```html
<body>
  Bounce: <input type="checkbox" data-bind="change: bounce">
</body>
```
```js
Template.body.viewmodel({
  bounce: function(e){
    $(e.target).effect('bounce');
  }
});
```

If you're bouncing one element based on another you then need an autorun like dalgard mentioned.

**Comment by deanius** [comment]
The data-bound change is really elegant, thanks.
