### ISSUE TITLE
Wrap function properties to make them reactive

### ISSUE THREAD

**Issue by dalgard** [ManuelDeLeon/viewmodel#95]
Writing to properties declared as functions is possible – for instance, the `value` binding calls the function with the new value – but retrieving the value back isn't reactive by default.

This means that it's up to the developer to store the value reactively, like in `Session` or in a `ReactiveVar` on the viewmodel instance.

Wouldn't it be better if functions, just like primitive values, were automatically wrapped in an outer function that fired a `depend()` when called without an argument, and a `changed()` when called with one?

Values could then simply be stored in private properties on the viewmodel instance without going through the ceremony (;)) of setting up a `ReactiveVar` inside an `onCreated` hook.

**Comment by ManuelDeLeon** [comment]
That pattern is interesting but it's the exception. You rarely need to do a two way bind between an element and a function. By far the most common scenario for a function is to be bound 1-way to an element. Another thing is that you may not want your function to be reactive.

**Comment by avalanche1** [comment]
+1
