### ISSUE TITLE
Get data context reactively

### ISSUE THREAD

**Issue by dalgard** [ManuelDeLeon/viewmodel#96]
I've added this to my project in order to get the data context of the current template instance reactively:

```javascript
ViewModel.prototype.getData = function () {
  return Blaze.getData(this.templateInstance.view)
};
```

I think this should be part of the package, but I wonder whether there is a smoother way of doing it.

Any thoughts?

**Comment by SparserLogic** [comment]
Looks nice but wouldn't any writes to this data bypass the ViewModel event system and cause the templating to break?

**Comment by dalgard** [comment]
I'm not sure, but would like to understand any caveats with this method. Writing to the data... The dependency that `getData` registers gets invalidated every time the data context is updated, like `{{> mySubtemplate myData=theValueOfThisHelperMayChangeForSomeReason}}`.

**Comment by SparserLogic** [comment]
Let me ask you this: what use cases have you encountered for this pattern?

**Comment by dalgard** [comment]
For instance, I have a paginator widget on my page, which is instantiated like this: `{{> paginator items=mycollection.count}}`

**Comment by SparserLogic** [comment]
Computed properties make perfect sense for this.

**Comment by dalgard** [comment]
Could you be more specific? Computed properties?

I'm talking about the need for any component that is configured with named template parameters to be able to reactively update when those parameters change.

**Comment by ManuelDeLeon** [comment]
computed == functions with dependencies

**Comment by dalgard** [comment]
Yes, exactly. If one of the dependencies is a named parameter, that one needs to be retrieved reactively, like in my example. It's not enough to write `this.templateInstance.data` if the data changes.

**Comment by dalgard** [comment]
I found what in my view is the more canonical way:

```javascript
ViewModel.prototype.getData = function () {
  return this.templateInstance.view.templateInstance().data;
};
```

It seems clear that ViewModel's `this.templateInstance` should have been equal to the view's `templateInstance()` method from the beginning, so that the data retrieved is reactive.

**Comment by artin-phares** [comment]
@dalgard Wow. I've spent almost whole day today to get reactive data context...
<code>Template.parentData()</code> sometimes throws 'There is no current view'-error.
 <code>this.templateInstance.view.templateInstance().data</code> works nicely.
I'm interested in some helper for this from-the-box too.
