### ISSUE TITLE
Recursive ViewModel support?

### ISSUE THREAD

**Issue by SparserLogic** [ManuelDeLeon/viewmodel#97]
Has this been tested? Are there any BKMs?

I would really like to start converting to this clean solution but I have a nested tree of comments/replies that I'm concerned will cause problems. Things like event binding break in Meteor when you use recursive templating.

Has this been tested with a similar pattern? How well does it work?

**Comment by ManuelDeLeon** [comment]
This is a slightly modified version of the comment system I use for meteorcasts (e.g. https://www.meteorcasts.net/ep/6 )

# commentsBlock
You drop this wherever you want comments. It provides the top level textarea to post comments. You can drop it anywhere that has an _id. In my case I put a `{{> commentsBlock }}` on each episode and also on a help section.

```html
<template name="commentsBlock">
  <div class="ui segment">
    <a name="comments"></a>
    <h1>Comments</h1>
    <form class="ui reply form" data-bind="if: hasUser">
      <div class="labeled field">
        <a class="ui top right ribbon label">Markdown</a>
        <textarea data-bind="value: newComment, focused: newCommentFocused"></textarea>
      </div>
      <div class="ui labeled submit icon button" data-bind="class: { blue : newComment }, click: addComment">
        <i class="icon edit"></i> Add Comment
      </div>
    </form>
    <p data-bind="if: !hasUser">
      Sign in to add a comment...
    </p>
    {{> comments }}
  </div>
</template>
```

```coffee
Template.commentsBlock.viewmodel
  _id: -> @parent()._id()
  newComment: ''
  newCommentFocused: false
  addComment: ->
    return if !@newComment()
    Comments.insert
      episodeId: @_id()
      parentComment: @_id()
      message: @newComment()
    @newComment ''
  hasUser: -> Meteor.user()?
  onCreated: (t) ->
    that = this
    t.autorun -> t.subscribe('comments', that._id())
, 'notSubscribed'
```

# comments
This is the list of comments directly below the parent.

```html
<template name="comments">
  {{#if hasComments }}
  <div class="ui comments long">
    {{#each commentList}}
      {{> comment}}
    {{/each }}
  </div>
  {{/if }}
</template>
```

```coffee
Template.comments.viewmodel
  commentList: -> Comments.find({ parentComment: @parent()._id() }, { sort: { createdAt: -1 } })
  hasComments: -> Comments.findOne({ parentComment: @parent()._id?() })?
, ['hasComments', 'commentList']
```

# comment
A single comment. Notice how it ends with `{{> comments }}` to display any comments below this one (recursively).

```html
<template name="comment">
  <div class="comment">
    <a class="avatar">
      <img data-bind="src: avatar">
    </a>
    <div class="content">
      <a class="author" data-bind="text: author"></a>
      <div class="metadata">
        <span class="date" data-bind="text: date"></span>
      </div>

      <div class="text" >
{{#markdown}}
{{message}}
{{/markdown}}
      </div>

      <div class="actions" data-bind="if: hasUser">
        <a class="reply" data-bind="toggle: showReply">Reply</a>
      </div>
      <form class="ui reply form" data-bind="if: showReply">

        <div class="labeled field">
          <a class="ui top right ribbon label" href="https://en.wikipedia.org/wiki/Markdown#Example" target="_blank">Markdown</a>
          <textarea data-bind="value: newComment"></textarea>
        </div>
        <div class="ui labeled submit icon button" data-bind="class: { blue : newComment }, click: addComment">
          <i class="icon edit"></i> Add Reply
        </div>
      </form>
    </div>
    {{> comments }}
  </div>
</template>
```

```coffee
Template.comment.viewmodel ( (data) -> 'comment_' + data._id ) ,((data) -> data),
  date: -> @createdAt()?.toRelativeTime(Client.serverTime.get()) or "Just Now";
  newComment: ''
  addComment: ->
    return if !@newComment()
    Comments.insert
      episodeId: @episodeId()
      parentComment: @_id()
      message: @newComment()
    @newComment ''
    @showReply false
  showReply: false
  hasUser: -> Meteor.user()?
, 'message'
```

**Comment by dalgard** [comment]
Why does event binding break with recursive templating – because of bubbling? How does ViewModel alleviate this problem, more precisely?

**Comment by SparserLogic** [comment]
> Why does event binding break with recursive templating – because of bubbling?

Yes. Events bubble to all parents. To fix this in normal Blaze I had to rely on jQuery binding during render using selectors with unique ids in them.

I had been hoping that, if each nested element was maintaining its own internal events, that a viewmodel might trigger that event without bubbling up a DOM one.

**Comment by ManuelDeLeon** [comment]
> Why does event binding break with recursive templating – because of bubbling? How does ViewModel alleviate this problem, more precisely?

> Yes. Events bubble to all parents. To fix this in normal Blaze I had to rely on jQuery binding during render using selectors with unique ids in them.

With ViewModel, events don't 'bubble up'. You declare the action that needs to execute when an event happens. There's a 1 to 1 link between an element's event and the function that runs. You don't have the Blaze/JQuery situation where an event is fired and then some listener picks it up.

**Comment by SparserLogic** [comment]
Fantastic.

That feature alone is probably enough to get me to switch, thank you!
