### ISSUE TITLE
Extending built-in views

### ISSUE THREAD

**Issue by dalgard** [ManuelDeLeon/viewmodel#98]
Did you ever consider extending the built-in views `#each`, `#if` etc. in order to support binding of new elements inside them?

**Comment by mordra** [comment]
+1, I've gone back to using `themeteorites:blaze-magic-events` with viewmodel just so I don't have to declare child template/js to handle simple click events from the child.

Actually spent a bit of time trying to get es-search working with this but was unable to after I realised that not only does the `+esEach` create new child templates, the `+esEach` itself IS a new template so I couldn't even pass my context into the child templates as I was trying to.

It'll be good to be able to rebind elements as they appear in lists or being generated dynamically by templates.

**Comment by ManuelDeLeon** [comment]
This is a hard one from a practical and philosophical point of view. For starters it's very hard to implement in a decent way (so it only updates/adds/removes the templates needed). Then there's the issue of encouraging small components (which ViewModel does right now).

But I understand the sentiment %100 percent. Specially when the html inside the loop is tiny. My rule of thumb is if there's any kind of logic I create a new template/view model, if it's just a matter of displaying a property I use good old Blaze:

```html
{{#each people}}
  <li>{{name}}</li>
{{/each}}
```

So for now I'm erring on the side of caution and not implementing it.

**Comment by dalgard** [comment]
Perfectly understandable.
