### ISSUE TITLE
Properties not saved when setting them in 'onDestroyed'

### ISSUE THREAD

**Issue by Kratos714** [ManuelDeLeon/viewmodel#99]
Hi, have a look at https://github.com/Kratos714/mvvm-test (be sure to test the two branches)

When I declare a ViewModel by hand, using `new ViewModel`, if I set a property in the `Template.name.onDestroyed` method, it's not saved in the Session.

It's even worst with the normal syntax `Template.name.viewmodel` : When I switch to another page, the `_vm_xxx` variable in Session is set to `undefined`

Did I make a mistake somewhere ?

**Comment by ManuelDeLeon** [comment]
What is it that you're trying to do?

As far as I can tell everything is working the way it should.

With `new ViewModel` the view model is destroyed on the same JS cycle as the onDestroyed so the view model doesn't have a chance to set the session variable.

With `Template.name.viewmodel` the session variable is set to undefined right before the view model is destroyed (on `onDestroyed`)

**Comment by Kratos714** [comment]
My bad, I thought that like hot code pushes, viewmodels were persisting across pages.
Thanks for the answer !

**Comment by ManuelDeLeon** [comment]
Nope, you get a new view model every time a new template is created.
